/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

module spi_flash_ctrl(wb_clk_i, wb_rst_ni, wb_adr_i, wb_dat_i, wb_dat_o, wb_sel_i, wb_we_i, wb_stb_i, wb_cyc_i, wb_ack_o, wb_err_o, flash_sck_o, flash_mosi_o, flash_miso_i, flash_cs_o, flash_wp_o, flash_hold_o);
  input wb_clk_i;
  wire wb_clk_i;
  input wb_rst_ni;
  wire wb_rst_ni;
  input [31:0] wb_adr_i;
  wire [31:0] wb_adr_i;
  input [31:0] wb_dat_i;
  wire [31:0] wb_dat_i;
  output [31:0] wb_dat_o;
  wire [31:0] wb_dat_o;
  input [3:0] wb_sel_i;
  wire [3:0] wb_sel_i;
  input wb_we_i;
  wire wb_we_i;
  input wb_stb_i;
  wire wb_stb_i;
  input wb_cyc_i;
  wire wb_cyc_i;
  output wb_ack_o;
  wire wb_ack_o;
  output wb_err_o;
  wire wb_err_o;
  output flash_sck_o;
  wire flash_sck_o;
  output flash_mosi_o;
  wire flash_mosi_o;
  input flash_miso_i;
  wire flash_miso_i;
  output flash_cs_o;
  wire flash_cs_o;
  output flash_wp_o;
  wire flash_wp_o;
  output flash_hold_o;
  wire flash_hold_o;
  wire _000_;
  wire [31:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire [2:0] addr_byte_cnt;
  wire [23:0] addr_reg;
  wire [2:0] bit_cnt;
  wire [7:0] cmd_reg;
  wire ctrl_fast_mode;
  wire ctrl_go;
  wire [2:0] fsm_state;
  wire [7:0] rddata_reg;
  wire [7:0] rx_shift;
  wire sck_toggle;
  wire [7:0] shift_reg;
  wire [7:0] txdata_reg;
  wire [3:0] wb_offset;
  sky130_fd_sc_hd__clkinv_1 _253_ (
    .A(sck_toggle),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(wb_cyc_i),
    .B(wb_stb_i),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _255_ (
    .A(wb_ack_o),
    .B(_079_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor3_1 _256_ (
    .A(wb_we_i),
    .B(wb_ack_o),
    .C(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__or3_1 _257_ (
    .A(wb_we_i),
    .B(wb_ack_o),
    .C(_079_),
    .X(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _258_ (
    .A(wb_adr_i[0]),
    .B(wb_adr_i[1]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(wb_adr_i[2]),
    .B(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _260_ (
    .A(wb_adr_i[3]),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__and3_1 _261_ (
    .A(addr_reg[20]),
    .B(_080_),
    .C(_084_),
    .X(_001_[20])
  );
  sky130_fd_sc_hd__and3_1 _262_ (
    .A(addr_reg[19]),
    .B(_080_),
    .C(_084_),
    .X(_001_[19])
  );
  sky130_fd_sc_hd__and3_1 _263_ (
    .A(addr_reg[18]),
    .B(_080_),
    .C(_084_),
    .X(_001_[18])
  );
  sky130_fd_sc_hd__and3_1 _264_ (
    .A(addr_reg[17]),
    .B(_080_),
    .C(_084_),
    .X(_001_[17])
  );
  sky130_fd_sc_hd__and3_1 _265_ (
    .A(addr_reg[16]),
    .B(_080_),
    .C(_084_),
    .X(_001_[16])
  );
  sky130_fd_sc_hd__and3_1 _266_ (
    .A(addr_reg[15]),
    .B(_080_),
    .C(_084_),
    .X(_001_[15])
  );
  sky130_fd_sc_hd__and3_1 _267_ (
    .A(addr_reg[14]),
    .B(_080_),
    .C(_084_),
    .X(_001_[14])
  );
  sky130_fd_sc_hd__and3_1 _268_ (
    .A(addr_reg[13]),
    .B(_080_),
    .C(_084_),
    .X(_001_[13])
  );
  sky130_fd_sc_hd__and3_1 _269_ (
    .A(addr_reg[12]),
    .B(_080_),
    .C(_084_),
    .X(_001_[12])
  );
  sky130_fd_sc_hd__and3_1 _270_ (
    .A(addr_reg[11]),
    .B(_080_),
    .C(_084_),
    .X(_001_[11])
  );
  sky130_fd_sc_hd__and3_1 _271_ (
    .A(addr_reg[10]),
    .B(_080_),
    .C(_084_),
    .X(_001_[10])
  );
  sky130_fd_sc_hd__and3_1 _272_ (
    .A(addr_reg[9]),
    .B(_080_),
    .C(_084_),
    .X(_001_[9])
  );
  sky130_fd_sc_hd__and3_1 _273_ (
    .A(addr_reg[8]),
    .B(_080_),
    .C(_084_),
    .X(_001_[8])
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(wb_adr_i[3]),
    .B(_082_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__and3_1 _275_ (
    .A(wb_adr_i[2]),
    .B(wb_adr_i[3]),
    .C(_082_),
    .X(_086_)
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(wb_adr_i[2]),
    .B(_085_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor4_1 _277_ (
    .A(wb_adr_i[2]),
    .B(wb_adr_i[3]),
    .C(wb_adr_i[0]),
    .D(wb_adr_i[1]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a22oi_1 _278_ (
    .A1(addr_reg[7]),
    .A2(_084_),
    .B1(_087_),
    .B2(txdata_reg[7]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a22oi_1 _279_ (
    .A1(rddata_reg[7]),
    .A2(_086_),
    .B1(_088_),
    .B2(cmd_reg[7]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a21oi_1 _280_ (
    .A1(_089_),
    .A2(_090_),
    .B1(_081_),
    .Y(_001_[7])
  );
  sky130_fd_sc_hd__a22oi_1 _281_ (
    .A1(addr_reg[6]),
    .A2(_084_),
    .B1(_087_),
    .B2(txdata_reg[6]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a22oi_1 _282_ (
    .A1(rddata_reg[6]),
    .A2(_086_),
    .B1(_088_),
    .B2(cmd_reg[6]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a21oi_1 _283_ (
    .A1(_091_),
    .A2(_092_),
    .B1(_081_),
    .Y(_001_[6])
  );
  sky130_fd_sc_hd__a22oi_1 _284_ (
    .A1(addr_reg[5]),
    .A2(_084_),
    .B1(_087_),
    .B2(txdata_reg[5]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a22oi_1 _285_ (
    .A1(rddata_reg[5]),
    .A2(_086_),
    .B1(_088_),
    .B2(cmd_reg[5]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a21oi_1 _286_ (
    .A1(_093_),
    .A2(_094_),
    .B1(_081_),
    .Y(_001_[5])
  );
  sky130_fd_sc_hd__a22oi_1 _287_ (
    .A1(addr_reg[4]),
    .A2(_084_),
    .B1(_087_),
    .B2(txdata_reg[4]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a22oi_1 _288_ (
    .A1(rddata_reg[4]),
    .A2(_086_),
    .B1(_088_),
    .B2(cmd_reg[4]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21oi_1 _289_ (
    .A1(_095_),
    .A2(_096_),
    .B1(_081_),
    .Y(_001_[4])
  );
  sky130_fd_sc_hd__a22oi_1 _290_ (
    .A1(addr_reg[3]),
    .A2(_084_),
    .B1(_087_),
    .B2(txdata_reg[3]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a22oi_1 _291_ (
    .A1(rddata_reg[3]),
    .A2(_086_),
    .B1(_088_),
    .B2(cmd_reg[3]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a21oi_1 _292_ (
    .A1(_097_),
    .A2(_098_),
    .B1(_081_),
    .Y(_001_[3])
  );
  sky130_fd_sc_hd__a22oi_1 _293_ (
    .A1(addr_reg[2]),
    .A2(_084_),
    .B1(_087_),
    .B2(txdata_reg[2]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a22oi_1 _294_ (
    .A1(rddata_reg[2]),
    .A2(_086_),
    .B1(_088_),
    .B2(cmd_reg[2]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21oi_1 _295_ (
    .A1(_099_),
    .A2(_100_),
    .B1(_081_),
    .Y(_001_[2])
  );
  sky130_fd_sc_hd__a22oi_1 _296_ (
    .A1(addr_reg[1]),
    .A2(_084_),
    .B1(_087_),
    .B2(txdata_reg[1]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a22oi_1 _297_ (
    .A1(rddata_reg[1]),
    .A2(_086_),
    .B1(_088_),
    .B2(cmd_reg[1]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _298_ (
    .A1(_101_),
    .A2(_102_),
    .B1(_081_),
    .Y(_001_[1])
  );
  sky130_fd_sc_hd__a22oi_1 _299_ (
    .A1(addr_reg[0]),
    .A2(_084_),
    .B1(_087_),
    .B2(txdata_reg[0]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a22oi_1 _300_ (
    .A1(rddata_reg[0]),
    .A2(_086_),
    .B1(_088_),
    .B2(cmd_reg[0]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a21oi_1 _301_ (
    .A1(_103_),
    .A2(_104_),
    .B1(_081_),
    .Y(_001_[0])
  );
  sky130_fd_sc_hd__and3_1 _302_ (
    .A(addr_reg[21]),
    .B(_080_),
    .C(_084_),
    .X(_001_[21])
  );
  sky130_fd_sc_hd__nand2_1 _303_ (
    .A(wb_we_i),
    .B(_000_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__and3_1 _304_ (
    .A(wb_we_i),
    .B(_000_),
    .C(_088_),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_1 _305_ (
    .A0(cmd_reg[6]),
    .A1(wb_dat_i[6]),
    .S(_106_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _306_ (
    .A0(cmd_reg[5]),
    .A1(wb_dat_i[5]),
    .S(_106_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _307_ (
    .A0(cmd_reg[4]),
    .A1(wb_dat_i[4]),
    .S(_106_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _308_ (
    .A0(cmd_reg[3]),
    .A1(wb_dat_i[3]),
    .S(_106_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _309_ (
    .A0(cmd_reg[2]),
    .A1(wb_dat_i[2]),
    .S(_106_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _310_ (
    .A0(cmd_reg[1]),
    .A1(wb_dat_i[1]),
    .S(_106_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _311_ (
    .A0(cmd_reg[0]),
    .A1(wb_dat_i[0]),
    .S(_106_),
    .X(_008_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _312_ (
    .A(fsm_state[0]),
    .SLEEP(fsm_state[2]),
    .X(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _313_ (
    .A(fsm_state[1]),
    .B(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor3_1 _314_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[2]),
    .C(bit_cnt[1]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__or3_1 _315_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[2]),
    .C(bit_cnt[1]),
    .X(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _316_ (
    .A(sck_toggle),
    .B(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(sck_toggle),
    .B(_108_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(_109_),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__mux2_1 _319_ (
    .A0(rx_shift[5]),
    .A1(rddata_reg[6]),
    .S(_113_),
    .X(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(rddata_reg[5]),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _321_ (
    .A(rx_shift[4]),
    .B(_112_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o21ai_0 _322_ (
    .A1(_110_),
    .A2(_115_),
    .B1(_114_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _323_ (
    .A0(rx_shift[3]),
    .A1(rddata_reg[4]),
    .S(_113_),
    .X(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(rddata_reg[3]),
    .B(_113_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(rx_shift[2]),
    .B(_112_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__o21ai_0 _326_ (
    .A1(_110_),
    .A2(_117_),
    .B1(_116_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(rddata_reg[2]),
    .B(_113_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(rx_shift[1]),
    .B(_112_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o21ai_0 _329_ (
    .A1(_110_),
    .A2(_119_),
    .B1(_118_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(rddata_reg[1]),
    .B(_113_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(rx_shift[0]),
    .B(_112_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o21ai_0 _332_ (
    .A1(_110_),
    .A2(_121_),
    .B1(_120_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(rddata_reg[0]),
    .B(_113_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(flash_miso_i),
    .B(_112_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__o21ai_0 _335_ (
    .A1(_110_),
    .A2(_123_),
    .B1(_122_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor3_1 _336_ (
    .A(wb_adr_i[3]),
    .B(_083_),
    .C(_105_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__mux2_1 _337_ (
    .A0(addr_reg[22]),
    .A1(wb_dat_i[22]),
    .S(_124_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _338_ (
    .A0(addr_reg[21]),
    .A1(wb_dat_i[21]),
    .S(_124_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _339_ (
    .A0(addr_reg[20]),
    .A1(wb_dat_i[20]),
    .S(_124_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _340_ (
    .A0(addr_reg[19]),
    .A1(wb_dat_i[19]),
    .S(_124_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _341_ (
    .A0(addr_reg[18]),
    .A1(wb_dat_i[18]),
    .S(_124_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _342_ (
    .A0(addr_reg[17]),
    .A1(wb_dat_i[17]),
    .S(_124_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _343_ (
    .A0(addr_reg[16]),
    .A1(wb_dat_i[16]),
    .S(_124_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _344_ (
    .A0(addr_reg[15]),
    .A1(wb_dat_i[15]),
    .S(_124_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _345_ (
    .A0(addr_reg[14]),
    .A1(wb_dat_i[14]),
    .S(_124_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _346_ (
    .A0(addr_reg[13]),
    .A1(wb_dat_i[13]),
    .S(_124_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _347_ (
    .A0(addr_reg[12]),
    .A1(wb_dat_i[12]),
    .S(_124_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _348_ (
    .A0(addr_reg[11]),
    .A1(wb_dat_i[11]),
    .S(_124_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _349_ (
    .A0(addr_reg[10]),
    .A1(wb_dat_i[10]),
    .S(_124_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _350_ (
    .A0(addr_reg[9]),
    .A1(wb_dat_i[9]),
    .S(_124_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _351_ (
    .A0(addr_reg[8]),
    .A1(wb_dat_i[8]),
    .S(_124_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _352_ (
    .A0(addr_reg[7]),
    .A1(wb_dat_i[7]),
    .S(_124_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _353_ (
    .A0(addr_reg[6]),
    .A1(wb_dat_i[6]),
    .S(_124_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _354_ (
    .A0(addr_reg[5]),
    .A1(wb_dat_i[5]),
    .S(_124_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _355_ (
    .A0(addr_reg[4]),
    .A1(wb_dat_i[4]),
    .S(_124_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _356_ (
    .A0(addr_reg[3]),
    .A1(wb_dat_i[3]),
    .S(_124_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _357_ (
    .A0(addr_reg[2]),
    .A1(wb_dat_i[2]),
    .S(_124_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _358_ (
    .A0(addr_reg[1]),
    .A1(wb_dat_i[1]),
    .S(_124_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _359_ (
    .A0(addr_reg[0]),
    .A1(wb_dat_i[0]),
    .S(_124_),
    .X(_038_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _360_ (
    .A(_107_),
    .SLEEP(fsm_state[1]),
    .X(_125_)
  );
  sky130_fd_sc_hd__nand2b_1 _361_ (
    .A_N(fsm_state[1]),
    .B(_107_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _362_ (
    .A(cmd_reg[1]),
    .B(cmd_reg[0]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand4bb_1 _363_ (
    .A_N(cmd_reg[5]),
    .B_N(cmd_reg[6]),
    .C(cmd_reg[7]),
    .D(cmd_reg[3]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand3_1 _364_ (
    .A(cmd_reg[1]),
    .B(cmd_reg[4]),
    .C(cmd_reg[0]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__or4_1 _365_ (
    .A(cmd_reg[5]),
    .B(cmd_reg[6]),
    .C(cmd_reg[7]),
    .D(cmd_reg[4]),
    .X(_130_)
  );
  sky130_fd_sc_hd__nor2_1 _366_ (
    .A(cmd_reg[1]),
    .B(cmd_reg[3]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__or3b_1 _367_ (
    .A(cmd_reg[1]),
    .B(cmd_reg[3]),
    .C_N(cmd_reg[0]),
    .X(_132_)
  );
  sky130_fd_sc_hd__o22ai_1 _368_ (
    .A1(_128_),
    .A2(_129_),
    .B1(_130_),
    .B2(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2b_1 _369_ (
    .A_N(cmd_reg[0]),
    .B(cmd_reg[1]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nor4_1 _370_ (
    .A(cmd_reg[2]),
    .B(cmd_reg[3]),
    .C(_130_),
    .D(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nor3_1 _371_ (
    .A(cmd_reg[2]),
    .B(_127_),
    .C(_130_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__or3_1 _372_ (
    .A(cmd_reg[2]),
    .B(_127_),
    .C(_130_),
    .X(_137_)
  );
  sky130_fd_sc_hd__nor4_1 _373_ (
    .A(cmd_reg[6]),
    .B(cmd_reg[7]),
    .C(cmd_reg[4]),
    .D(cmd_reg[0]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__and4b_1 _374_ (
    .A_N(cmd_reg[2]),
    .B(_131_),
    .C(_138_),
    .D(cmd_reg[5]),
    .X(_139_)
  );
  sky130_fd_sc_hd__a2111oi_0 _375_ (
    .A1(cmd_reg[2]),
    .A2(_133_),
    .B1(_135_),
    .C1(_136_),
    .D1(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _376_ (
    .A(_125_),
    .B(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor3b_1 _377_ (
    .A(fsm_state[2]),
    .B(fsm_state[0]),
    .C_N(fsm_state[1]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__or3b_1 _378_ (
    .A(fsm_state[2]),
    .B(fsm_state[0]),
    .C_N(fsm_state[1]),
    .X(_143_)
  );
  sky130_fd_sc_hd__nor2_1 _379_ (
    .A(addr_byte_cnt[0]),
    .B(addr_byte_cnt[1]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor3_1 _380_ (
    .A(addr_byte_cnt[2]),
    .B(addr_byte_cnt[0]),
    .C(addr_byte_cnt[1]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__or3_1 _381_ (
    .A(addr_byte_cnt[2]),
    .B(addr_byte_cnt[0]),
    .C(addr_byte_cnt[1]),
    .X(_146_)
  );
  sky130_fd_sc_hd__nor2_1 _382_ (
    .A(_125_),
    .B(_142_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _383_ (
    .A(_126_),
    .B(_143_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o2111ai_1 _384_ (
    .A1(_143_),
    .A2(_146_),
    .B1(_148_),
    .C1(_141_),
    .D1(_111_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _385_ (
    .A(addr_byte_cnt[1]),
    .B(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand2_1 _386_ (
    .A(_109_),
    .B(_142_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(sck_toggle),
    .B(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand2_1 _388_ (
    .A(_111_),
    .B(_142_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__xnor2_1 _389_ (
    .A(addr_byte_cnt[0]),
    .B(addr_byte_cnt[1]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nand3_1 _390_ (
    .A(_146_),
    .B(_152_),
    .C(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _391_ (
    .A(_110_),
    .B(_140_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor3_1 _392_ (
    .A(_110_),
    .B(_126_),
    .C(_140_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _393_ (
    .A(_078_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand3_1 _394_ (
    .A(_150_),
    .B(_155_),
    .C(_158_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _395_ (
    .A(addr_byte_cnt[0]),
    .B(_149_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o31ai_1 _396_ (
    .A1(addr_byte_cnt[0]),
    .A2(_145_),
    .A3(_153_),
    .B1(_159_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a31oi_1 _397_ (
    .A1(_109_),
    .A2(_136_),
    .A3(_145_),
    .B1(fsm_state[0]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__or4b_1 _398_ (
    .A(fsm_state[2]),
    .B(sck_toggle),
    .C(_160_),
    .D_N(fsm_state[1]),
    .X(_161_)
  );
  sky130_fd_sc_hd__a22o_1 _399_ (
    .A1(rx_shift[5]),
    .A2(_112_),
    .B1(_161_),
    .B2(rx_shift[6]),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _400_ (
    .A(rx_shift[5]),
    .B(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2_1 _401_ (
    .A(_115_),
    .B(_162_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a22o_1 _402_ (
    .A1(rx_shift[3]),
    .A2(_112_),
    .B1(_161_),
    .B2(rx_shift[4]),
    .X(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(rx_shift[3]),
    .B(_161_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _404_ (
    .A(_117_),
    .B(_163_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _405_ (
    .A(rx_shift[2]),
    .B(_161_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(_119_),
    .B(_164_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _407_ (
    .A(rx_shift[1]),
    .B(_161_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(_121_),
    .B(_165_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _409_ (
    .A(rx_shift[0]),
    .B(_161_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _410_ (
    .A(_123_),
    .B(_166_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor3_1 _411_ (
    .A(wb_adr_i[2]),
    .B(_085_),
    .C(_105_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__mux2_1 _412_ (
    .A0(txdata_reg[6]),
    .A1(wb_dat_i[6]),
    .S(_167_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _413_ (
    .A0(txdata_reg[5]),
    .A1(wb_dat_i[5]),
    .S(_167_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _414_ (
    .A0(txdata_reg[4]),
    .A1(wb_dat_i[4]),
    .S(_167_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _415_ (
    .A0(txdata_reg[3]),
    .A1(wb_dat_i[3]),
    .S(_167_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _416_ (
    .A0(txdata_reg[2]),
    .A1(wb_dat_i[2]),
    .S(_167_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _417_ (
    .A0(txdata_reg[1]),
    .A1(wb_dat_i[1]),
    .S(_167_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _418_ (
    .A0(txdata_reg[0]),
    .A1(wb_dat_i[0]),
    .S(_167_),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _419_ (
    .A(fsm_state[0]),
    .B(fsm_state[1]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__xor2_1 _420_ (
    .A(fsm_state[2]),
    .B(_168_),
    .X(_169_)
  );
  sky130_fd_sc_hd__nor2_1 _421_ (
    .A(sck_toggle),
    .B(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _422_ (
    .A(_108_),
    .B(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _423_ (
    .A(shift_reg[6]),
    .B(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nand2b_1 _424_ (
    .A_N(fsm_state[0]),
    .B(fsm_state[2]),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nor2_1 _425_ (
    .A(fsm_state[1]),
    .B(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__o21ai_0 _426_ (
    .A1(_135_),
    .A2(_146_),
    .B1(_109_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a21oi_1 _427_ (
    .A1(_142_),
    .A2(_175_),
    .B1(_174_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__o21ai_0 _428_ (
    .A1(_126_),
    .A2(_156_),
    .B1(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand3_1 _429_ (
    .A(txdata_reg[6]),
    .B(_135_),
    .C(_145_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nor3b_1 _430_ (
    .A(addr_byte_cnt[2]),
    .B(addr_byte_cnt[1]),
    .C_N(addr_byte_cnt[0]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor3b_1 _431_ (
    .A(addr_byte_cnt[2]),
    .B(addr_byte_cnt[0]),
    .C_N(addr_byte_cnt[1]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__a22oi_1 _432_ (
    .A1(addr_reg[14]),
    .A2(_179_),
    .B1(_180_),
    .B2(addr_reg[22]),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a21oi_1 _433_ (
    .A1(_178_),
    .A2(_181_),
    .B1(_151_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a221oi_1 _434_ (
    .A1(addr_reg[22]),
    .A2(_157_),
    .B1(_177_),
    .B2(shift_reg[5]),
    .C1(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__o21ai_0 _435_ (
    .A1(sck_toggle),
    .A2(_183_),
    .B1(_172_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _436_ (
    .A(shift_reg[5]),
    .B(_171_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand3_1 _437_ (
    .A(txdata_reg[5]),
    .B(_135_),
    .C(_145_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a22oi_1 _438_ (
    .A1(addr_reg[13]),
    .A2(_179_),
    .B1(_180_),
    .B2(addr_reg[21]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a21oi_1 _439_ (
    .A1(_185_),
    .A2(_186_),
    .B1(_151_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a221oi_1 _440_ (
    .A1(addr_reg[21]),
    .A2(_157_),
    .B1(_177_),
    .B2(shift_reg[4]),
    .C1(_187_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__o21ai_0 _441_ (
    .A1(sck_toggle),
    .A2(_188_),
    .B1(_184_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(shift_reg[4]),
    .B(_171_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand3_1 _443_ (
    .A(txdata_reg[4]),
    .B(_135_),
    .C(_145_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__a22oi_1 _444_ (
    .A1(addr_reg[12]),
    .A2(_179_),
    .B1(_180_),
    .B2(addr_reg[20]),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a21oi_1 _445_ (
    .A1(_190_),
    .A2(_191_),
    .B1(_151_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__a221oi_1 _446_ (
    .A1(addr_reg[20]),
    .A2(_157_),
    .B1(_177_),
    .B2(shift_reg[3]),
    .C1(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__o21ai_0 _447_ (
    .A1(sck_toggle),
    .A2(_193_),
    .B1(_189_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _448_ (
    .A(shift_reg[3]),
    .B(_171_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand3_1 _449_ (
    .A(txdata_reg[3]),
    .B(_135_),
    .C(_145_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__a22oi_1 _450_ (
    .A1(addr_reg[11]),
    .A2(_179_),
    .B1(_180_),
    .B2(addr_reg[19]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _451_ (
    .A1_N(_175_),
    .A2_N(_142_),
    .B1(_126_),
    .B2(_156_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__a21oi_1 _452_ (
    .A1(_195_),
    .A2(_196_),
    .B1(_151_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__a221o_1 _453_ (
    .A1(addr_reg[19]),
    .A2(_157_),
    .B1(_174_),
    .B2(shift_reg[2]),
    .C1(_198_),
    .X(_199_)
  );
  sky130_fd_sc_hd__a21oi_1 _454_ (
    .A1(shift_reg[2]),
    .A2(_197_),
    .B1(_199_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__o21ai_0 _455_ (
    .A1(sck_toggle),
    .A2(_200_),
    .B1(_194_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _456_ (
    .A(shift_reg[2]),
    .B(_171_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand3_1 _457_ (
    .A(txdata_reg[2]),
    .B(_135_),
    .C(_145_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__a22oi_1 _458_ (
    .A1(addr_reg[10]),
    .A2(_179_),
    .B1(_180_),
    .B2(addr_reg[18]),
    .Y(_203_)
  );
  sky130_fd_sc_hd__a21oi_1 _459_ (
    .A1(_202_),
    .A2(_203_),
    .B1(_151_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__a221o_1 _460_ (
    .A1(addr_reg[18]),
    .A2(_157_),
    .B1(_174_),
    .B2(shift_reg[1]),
    .C1(_204_),
    .X(_205_)
  );
  sky130_fd_sc_hd__a21oi_1 _461_ (
    .A1(shift_reg[1]),
    .A2(_197_),
    .B1(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o21ai_0 _462_ (
    .A1(sck_toggle),
    .A2(_206_),
    .B1(_201_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _463_ (
    .A(shift_reg[1]),
    .B(_171_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand3_1 _464_ (
    .A(txdata_reg[1]),
    .B(_135_),
    .C(_145_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__a22oi_1 _465_ (
    .A1(addr_reg[9]),
    .A2(_179_),
    .B1(_180_),
    .B2(addr_reg[17]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__a21oi_1 _466_ (
    .A1(_208_),
    .A2(_209_),
    .B1(_151_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__a221oi_1 _467_ (
    .A1(addr_reg[17]),
    .A2(_157_),
    .B1(_177_),
    .B2(shift_reg[0]),
    .C1(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o21ai_0 _468_ (
    .A1(sck_toggle),
    .A2(_211_),
    .B1(_207_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _469_ (
    .A(_152_),
    .B(_180_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nand2_1 _470_ (
    .A(_158_),
    .B(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__a32oi_1 _471_ (
    .A1(txdata_reg[0]),
    .A2(_135_),
    .A3(_145_),
    .B1(_179_),
    .B2(addr_reg[8]),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor2_1 _472_ (
    .A(_153_),
    .B(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__a221o_1 _473_ (
    .A1(shift_reg[0]),
    .A2(_171_),
    .B1(_213_),
    .B2(addr_reg[16]),
    .C1(_215_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nand3_1 _474_ (
    .A(_109_),
    .B(_125_),
    .C(_140_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nor3_1 _475_ (
    .A(_135_),
    .B(_136_),
    .C(_146_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand3_1 _476_ (
    .A(_109_),
    .B(_142_),
    .C(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__o21ai_0 _477_ (
    .A1(fsm_state[1]),
    .A2(_173_),
    .B1(_108_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o21ai_0 _478_ (
    .A1(sck_toggle),
    .A2(_109_),
    .B1(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__a21oi_1 _479_ (
    .A1(sck_toggle),
    .A2(_148_),
    .B1(_169_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand4_1 _480_ (
    .A(_216_),
    .B(_218_),
    .C(_220_),
    .D(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand2_1 _481_ (
    .A(bit_cnt[1]),
    .B(_222_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__xor2_1 _482_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .X(_224_)
  );
  sky130_fd_sc_hd__o22ai_1 _483_ (
    .A1(_151_),
    .A2(_217_),
    .B1(_224_),
    .B2(_109_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nand2_1 _484_ (
    .A(_170_),
    .B(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nand3_1 _485_ (
    .A(_158_),
    .B(_223_),
    .C(_226_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o32a_1 _486_ (
    .A1(sck_toggle),
    .A2(bit_cnt[0]),
    .A3(_109_),
    .B1(_153_),
    .B2(_217_),
    .X(_227_)
  );
  sky130_fd_sc_hd__a21oi_1 _487_ (
    .A1(_158_),
    .A2(_227_),
    .B1(_169_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__a21o_1 _488_ (
    .A1(bit_cnt[0]),
    .A2(_222_),
    .B1(_228_),
    .X(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _489_ (
    .A1(sck_toggle),
    .A2(_148_),
    .B1(_219_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__a21oi_1 _490_ (
    .A1(_142_),
    .A2(_146_),
    .B1(_110_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o22ai_1 _491_ (
    .A1(_111_),
    .A2(_229_),
    .B1(_230_),
    .B2(_147_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand2_1 _492_ (
    .A(fsm_state[1]),
    .B(_231_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nand3_1 _493_ (
    .A(_111_),
    .B(_142_),
    .C(_145_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__o211ai_1 _494_ (
    .A1(_137_),
    .A2(_233_),
    .B1(_232_),
    .C1(_158_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand3_1 _495_ (
    .A(_111_),
    .B(_125_),
    .C(_140_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nand2_1 _496_ (
    .A(_111_),
    .B(_219_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__o21ai_0 _497_ (
    .A1(_135_),
    .A2(_233_),
    .B1(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__a21oi_1 _498_ (
    .A1(fsm_state[0]),
    .A2(_231_),
    .B1(_236_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nand2_1 _499_ (
    .A(_234_),
    .B(_237_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a21boi_0 _500_ (
    .A1(fsm_state[2]),
    .A2(_231_),
    .B1_N(_235_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__o211ai_1 _501_ (
    .A1(_136_),
    .A2(_233_),
    .B1(_234_),
    .C1(_238_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _502_ (
    .A0(txdata_reg[7]),
    .A1(wb_dat_i[7]),
    .S(_167_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _503_ (
    .A(shift_reg[7]),
    .B(_171_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nand3_1 _504_ (
    .A(txdata_reg[7]),
    .B(_135_),
    .C(_145_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__a22oi_1 _505_ (
    .A1(addr_reg[15]),
    .A2(_179_),
    .B1(_180_),
    .B2(addr_reg[23]),
    .Y(_241_)
  );
  sky130_fd_sc_hd__a21oi_1 _506_ (
    .A1(_240_),
    .A2(_241_),
    .B1(_151_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__a221oi_1 _507_ (
    .A1(addr_reg[23]),
    .A2(_157_),
    .B1(_177_),
    .B2(shift_reg[6]),
    .C1(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__o21ai_0 _508_ (
    .A1(sck_toggle),
    .A2(_243_),
    .B1(_239_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _509_ (
    .A(fsm_state[1]),
    .B(_107_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a21o_1 _510_ (
    .A1(_173_),
    .A2(_244_),
    .B1(flash_cs_o),
    .X(_069_)
  );
  sky130_fd_sc_hd__o21ai_0 _511_ (
    .A1(_148_),
    .A2(_174_),
    .B1(_171_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__o21ai_0 _512_ (
    .A1(_148_),
    .A2(_174_),
    .B1(shift_reg[7]),
    .Y(_246_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _513_ (
    .A1_N(flash_mosi_o),
    .A2_N(_245_),
    .B1(_246_),
    .B2(_078_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__and3_1 _514_ (
    .A(addr_reg[22]),
    .B(_080_),
    .C(_084_),
    .X(_001_[22])
  );
  sky130_fd_sc_hd__nand3_1 _515_ (
    .A(fsm_state[2]),
    .B(fsm_state[1]),
    .C(flash_sck_o),
    .Y(_247_)
  );
  sky130_fd_sc_hd__o21ai_0 _516_ (
    .A1(_078_),
    .A2(_169_),
    .B1(_247_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _517_ (
    .A(_144_),
    .B(_153_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__o21a_1 _518_ (
    .A1(_149_),
    .A2(_248_),
    .B1(addr_byte_cnt[2]),
    .X(_072_)
  );
  sky130_fd_sc_hd__and3_1 _519_ (
    .A(addr_reg[23]),
    .B(_080_),
    .C(_084_),
    .X(_001_[23])
  );
  sky130_fd_sc_hd__mux2_1 _520_ (
    .A0(addr_reg[23]),
    .A1(wb_dat_i[23]),
    .S(_124_),
    .X(_073_)
  );
  sky130_fd_sc_hd__o21a_1 _521_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[1]),
    .B1(bit_cnt[2]),
    .X(_249_)
  );
  sky130_fd_sc_hd__o21ai_0 _522_ (
    .A1(_157_),
    .A2(_249_),
    .B1(_170_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nand2_1 _523_ (
    .A(bit_cnt[2]),
    .B(_222_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__o211ai_1 _524_ (
    .A1(_153_),
    .A2(_217_),
    .B1(_250_),
    .C1(_251_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _525_ (
    .A0(rx_shift[6]),
    .A1(rddata_reg[7]),
    .S(_113_),
    .X(_075_)
  );
  sky130_fd_sc_hd__o211ai_1 _526_ (
    .A1(fsm_state[0]),
    .A2(fsm_state[1]),
    .B1(sck_toggle),
    .C1(fsm_state[2]),
    .Y(_252_)
  );
  sky130_fd_sc_hd__o21ai_0 _527_ (
    .A1(sck_toggle),
    .A2(_169_),
    .B1(_252_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__mux2_1 _528_ (
    .A0(cmd_reg[7]),
    .A1(wb_dat_i[7]),
    .S(_106_),
    .X(_077_)
  );
  sky130_fd_sc_hd__dfrtp_1 _529_ (
    .CLK(wb_clk_i),
    .D(_015_),
    .Q(rddata_reg[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _530_ (
    .CLK(wb_clk_i),
    .D(_014_),
    .Q(rddata_reg[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _531_ (
    .CLK(wb_clk_i),
    .D(_013_),
    .Q(rddata_reg[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _532_ (
    .CLK(wb_clk_i),
    .D(_012_),
    .Q(rddata_reg[3]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _533_ (
    .CLK(wb_clk_i),
    .D(_011_),
    .Q(rddata_reg[4]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _534_ (
    .CLK(wb_clk_i),
    .D(_010_),
    .Q(rddata_reg[5]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _535_ (
    .CLK(wb_clk_i),
    .D(_009_),
    .Q(rddata_reg[6]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _536_ (
    .CLK(wb_clk_i),
    .D(_075_),
    .Q(rddata_reg[7]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _537_ (
    .CLK(wb_clk_i),
    .D(_076_),
    .Q(sck_toggle),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _538_ (
    .CLK(wb_clk_i),
    .D(_008_),
    .Q(cmd_reg[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _539_ (
    .CLK(wb_clk_i),
    .D(_007_),
    .Q(cmd_reg[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _540_ (
    .CLK(wb_clk_i),
    .D(_006_),
    .Q(cmd_reg[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _541_ (
    .CLK(wb_clk_i),
    .D(_005_),
    .Q(cmd_reg[3]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _542_ (
    .CLK(wb_clk_i),
    .D(_004_),
    .Q(cmd_reg[4]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _543_ (
    .CLK(wb_clk_i),
    .D(_003_),
    .Q(cmd_reg[5]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _544_ (
    .CLK(wb_clk_i),
    .D(_002_),
    .Q(cmd_reg[6]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _545_ (
    .CLK(wb_clk_i),
    .D(_077_),
    .Q(cmd_reg[7]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _546_ (
    .CLK(wb_clk_i),
    .D(_001_[0]),
    .Q(wb_dat_o[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _547_ (
    .CLK(wb_clk_i),
    .D(_001_[1]),
    .Q(wb_dat_o[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _548_ (
    .CLK(wb_clk_i),
    .D(_001_[2]),
    .Q(wb_dat_o[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _549_ (
    .CLK(wb_clk_i),
    .D(_001_[3]),
    .Q(wb_dat_o[3]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _550_ (
    .CLK(wb_clk_i),
    .D(_001_[4]),
    .Q(wb_dat_o[4]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _551_ (
    .CLK(wb_clk_i),
    .D(_001_[5]),
    .Q(wb_dat_o[5]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _552_ (
    .CLK(wb_clk_i),
    .D(_001_[6]),
    .Q(wb_dat_o[6]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _553_ (
    .CLK(wb_clk_i),
    .D(_001_[7]),
    .Q(wb_dat_o[7]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _554_ (
    .CLK(wb_clk_i),
    .D(_001_[8]),
    .Q(wb_dat_o[8]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _555_ (
    .CLK(wb_clk_i),
    .D(_001_[9]),
    .Q(wb_dat_o[9]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _556_ (
    .CLK(wb_clk_i),
    .D(_001_[10]),
    .Q(wb_dat_o[10]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _557_ (
    .CLK(wb_clk_i),
    .D(_001_[11]),
    .Q(wb_dat_o[11]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _558_ (
    .CLK(wb_clk_i),
    .D(_001_[12]),
    .Q(wb_dat_o[12]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _559_ (
    .CLK(wb_clk_i),
    .D(_001_[13]),
    .Q(wb_dat_o[13]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _560_ (
    .CLK(wb_clk_i),
    .D(_001_[14]),
    .Q(wb_dat_o[14]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _561_ (
    .CLK(wb_clk_i),
    .D(_001_[15]),
    .Q(wb_dat_o[15]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _562_ (
    .CLK(wb_clk_i),
    .D(_001_[16]),
    .Q(wb_dat_o[16]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _563_ (
    .CLK(wb_clk_i),
    .D(_001_[17]),
    .Q(wb_dat_o[17]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _564_ (
    .CLK(wb_clk_i),
    .D(_001_[18]),
    .Q(wb_dat_o[18]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _565_ (
    .CLK(wb_clk_i),
    .D(_001_[19]),
    .Q(wb_dat_o[19]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _566_ (
    .CLK(wb_clk_i),
    .D(_001_[20]),
    .Q(wb_dat_o[20]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _567_ (
    .CLK(wb_clk_i),
    .D(_001_[21]),
    .Q(wb_dat_o[21]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _568_ (
    .CLK(wb_clk_i),
    .D(_001_[22]),
    .Q(wb_dat_o[22]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _569_ (
    .CLK(wb_clk_i),
    .D(_001_[23]),
    .Q(wb_dat_o[23]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _570_ (
    .CLK(wb_clk_i),
    .D(_000_),
    .Q(wb_ack_o),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _571_ (
    .CLK(wb_clk_i),
    .D(_065_),
    .Q(fsm_state[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _572_ (
    .CLK(wb_clk_i),
    .D(_064_),
    .Q(fsm_state[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _573_ (
    .CLK(wb_clk_i),
    .D(_066_),
    .Q(fsm_state[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _574_ (
    .CLK(wb_clk_i),
    .D(_070_),
    .Q(flash_mosi_o),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _575_ (
    .CLK(wb_clk_i),
    .D(_063_),
    .Q(bit_cnt[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _576_ (
    .CLK(wb_clk_i),
    .D(_062_),
    .Q(bit_cnt[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _577_ (
    .CLK(wb_clk_i),
    .D(_074_),
    .Q(bit_cnt[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _578_ (
    .CLK(wb_clk_i),
    .D(_061_),
    .Q(shift_reg[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _579_ (
    .CLK(wb_clk_i),
    .D(_060_),
    .Q(shift_reg[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _580_ (
    .CLK(wb_clk_i),
    .D(_059_),
    .Q(shift_reg[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _581_ (
    .CLK(wb_clk_i),
    .D(_058_),
    .Q(shift_reg[3]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _582_ (
    .CLK(wb_clk_i),
    .D(_057_),
    .Q(shift_reg[4]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _583_ (
    .CLK(wb_clk_i),
    .D(_056_),
    .Q(shift_reg[5]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _584_ (
    .CLK(wb_clk_i),
    .D(_055_),
    .Q(shift_reg[6]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _585_ (
    .CLK(wb_clk_i),
    .D(_068_),
    .Q(shift_reg[7]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _586_ (
    .CLK(wb_clk_i),
    .D(_054_),
    .Q(txdata_reg[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _587_ (
    .CLK(wb_clk_i),
    .D(_053_),
    .Q(txdata_reg[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _588_ (
    .CLK(wb_clk_i),
    .D(_052_),
    .Q(txdata_reg[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _589_ (
    .CLK(wb_clk_i),
    .D(_051_),
    .Q(txdata_reg[3]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _590_ (
    .CLK(wb_clk_i),
    .D(_050_),
    .Q(txdata_reg[4]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _591_ (
    .CLK(wb_clk_i),
    .D(_049_),
    .Q(txdata_reg[5]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _592_ (
    .CLK(wb_clk_i),
    .D(_048_),
    .Q(txdata_reg[6]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _593_ (
    .CLK(wb_clk_i),
    .D(_067_),
    .Q(txdata_reg[7]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _594_ (
    .CLK(wb_clk_i),
    .D(_069_),
    .Q(flash_cs_o),
    .SET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _595_ (
    .CLK(wb_clk_i),
    .D(_047_),
    .Q(rx_shift[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _596_ (
    .CLK(wb_clk_i),
    .D(_046_),
    .Q(rx_shift[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _597_ (
    .CLK(wb_clk_i),
    .D(_045_),
    .Q(rx_shift[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _598_ (
    .CLK(wb_clk_i),
    .D(_044_),
    .Q(rx_shift[3]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _599_ (
    .CLK(wb_clk_i),
    .D(_043_),
    .Q(rx_shift[4]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _600_ (
    .CLK(wb_clk_i),
    .D(_042_),
    .Q(rx_shift[5]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _601_ (
    .CLK(wb_clk_i),
    .D(_041_),
    .Q(rx_shift[6]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _602_ (
    .CLK(wb_clk_i),
    .D(_071_),
    .Q(flash_sck_o),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _603_ (
    .CLK(wb_clk_i),
    .D(_040_),
    .Q(addr_byte_cnt[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _604_ (
    .CLK(wb_clk_i),
    .D(_039_),
    .Q(addr_byte_cnt[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _605_ (
    .CLK(wb_clk_i),
    .D(_072_),
    .Q(addr_byte_cnt[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _606_ (
    .CLK(wb_clk_i),
    .D(_038_),
    .Q(addr_reg[0]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _607_ (
    .CLK(wb_clk_i),
    .D(_037_),
    .Q(addr_reg[1]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _608_ (
    .CLK(wb_clk_i),
    .D(_036_),
    .Q(addr_reg[2]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _609_ (
    .CLK(wb_clk_i),
    .D(_035_),
    .Q(addr_reg[3]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _610_ (
    .CLK(wb_clk_i),
    .D(_034_),
    .Q(addr_reg[4]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _611_ (
    .CLK(wb_clk_i),
    .D(_033_),
    .Q(addr_reg[5]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _612_ (
    .CLK(wb_clk_i),
    .D(_032_),
    .Q(addr_reg[6]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _613_ (
    .CLK(wb_clk_i),
    .D(_031_),
    .Q(addr_reg[7]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _614_ (
    .CLK(wb_clk_i),
    .D(_030_),
    .Q(addr_reg[8]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _615_ (
    .CLK(wb_clk_i),
    .D(_029_),
    .Q(addr_reg[9]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _616_ (
    .CLK(wb_clk_i),
    .D(_028_),
    .Q(addr_reg[10]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _617_ (
    .CLK(wb_clk_i),
    .D(_027_),
    .Q(addr_reg[11]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _618_ (
    .CLK(wb_clk_i),
    .D(_026_),
    .Q(addr_reg[12]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _619_ (
    .CLK(wb_clk_i),
    .D(_025_),
    .Q(addr_reg[13]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _620_ (
    .CLK(wb_clk_i),
    .D(_024_),
    .Q(addr_reg[14]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _621_ (
    .CLK(wb_clk_i),
    .D(_023_),
    .Q(addr_reg[15]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _622_ (
    .CLK(wb_clk_i),
    .D(_022_),
    .Q(addr_reg[16]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _623_ (
    .CLK(wb_clk_i),
    .D(_021_),
    .Q(addr_reg[17]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _624_ (
    .CLK(wb_clk_i),
    .D(_020_),
    .Q(addr_reg[18]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _625_ (
    .CLK(wb_clk_i),
    .D(_019_),
    .Q(addr_reg[19]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _626_ (
    .CLK(wb_clk_i),
    .D(_018_),
    .Q(addr_reg[20]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _627_ (
    .CLK(wb_clk_i),
    .D(_017_),
    .Q(addr_reg[21]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _628_ (
    .CLK(wb_clk_i),
    .D(_016_),
    .Q(addr_reg[22]),
    .RESET_B(wb_rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _629_ (
    .CLK(wb_clk_i),
    .D(_073_),
    .Q(addr_reg[23]),
    .RESET_B(wb_rst_ni)
  );
  assign _001_[31:24] = 8'h00;
  assign wb_offset = wb_adr_i[3:0];
  assign ctrl_fast_mode = 1'h0;
  assign ctrl_go = 1'h0;
  assign flash_hold_o = 1'h1;
  assign flash_wp_o = 1'h1;
  assign wb_err_o = 1'h0;
  assign wb_dat_o[31:24] = 8'h00;
endmodule
