/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

module irq_ctrl(clk_i, rst_ni, wb_adr_i, wb_dat_i, wb_dat_o, wb_sel_i, wb_we_i, wb_stb_i, wb_cyc_i, wb_ack_o, irq_src_i, m_irq_o);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input [31:0] wb_adr_i;
  wire [31:0] wb_adr_i;
  input [31:0] wb_dat_i;
  wire [31:0] wb_dat_i;
  output [31:0] wb_dat_o;
  wire [31:0] wb_dat_o;
  input [3:0] wb_sel_i;
  wire [3:0] wb_sel_i;
  input wb_we_i;
  wire wb_we_i;
  input wb_stb_i;
  wire wb_stb_i;
  input wb_cyc_i;
  wire wb_cyc_i;
  output wb_ack_o;
  wire wb_ack_o;
  input [15:0] irq_src_i;
  wire [15:0] irq_src_i;
  output m_irq_o;
  wire m_irq_o;
  wire [15:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire [15:0] enable;
  wire [15:0] irq_sync1;
  wire [15:0] irq_sync2;
  wire [15:0] pending;
  wire [1:0] \prio[0] ;
  wire [1:0] \prio[10] ;
  wire [1:0] \prio[11] ;
  wire [1:0] \prio[12] ;
  wire [1:0] \prio[13] ;
  wire [1:0] \prio[14] ;
  wire [1:0] \prio[15] ;
  wire [1:0] \prio[1] ;
  wire [1:0] \prio[2] ;
  wire [1:0] \prio[3] ;
  wire [1:0] \prio[4] ;
  wire [1:0] \prio[5] ;
  wire [1:0] \prio[6] ;
  wire [1:0] \prio[7] ;
  wire [1:0] \prio[8] ;
  wire [1:0] \prio[9] ;
  wire [1:0] threshold;
  sky130_fd_sc_hd__clkinv_1 _265_ (
    .A(\prio[13] [1]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__clkinv_1 _266_ (
    .A(\prio[11] [1]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__clkinv_1 _267_ (
    .A(\prio[9] [1]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _268_ (
    .A(\prio[0] [1]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _269_ (
    .A(\prio[14] [1]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _270_ (
    .A(\prio[10] [1]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _271_ (
    .A(\prio[5] [1]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _272_ (
    .A(\prio[8] [1]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _273_ (
    .A(\prio[1] [1]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__clkinv_1 _274_ (
    .A(\prio[3] [1]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__clkinv_1 _275_ (
    .A(threshold[0]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _276_ (
    .A(\prio[4] [1]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(wb_cyc_i),
    .B(wb_stb_i),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _278_ (
    .A(wb_ack_o),
    .B(_081_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3_1 _279_ (
    .A(wb_we_i),
    .B(wb_ack_o),
    .C(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _280_ (
    .A(wb_adr_i[2]),
    .SLEEP(wb_adr_i[3]),
    .X(_083_)
  );
  sky130_fd_sc_hd__and3_1 _281_ (
    .A(wb_adr_i[4]),
    .B(_082_),
    .C(_083_),
    .X(_084_)
  );
  sky130_fd_sc_hd__nand2b_1 _282_ (
    .A_N(\prio[12] [1]),
    .B(threshold[1]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2b_1 _283_ (
    .A_N(threshold[1]),
    .B(\prio[12] [1]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand3_1 _284_ (
    .A(pending[12]),
    .B(enable[12]),
    .C(_086_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a31oi_1 _285_ (
    .A1(\prio[12] [0]),
    .A2(_079_),
    .A3(_085_),
    .B1(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2b_1 _286_ (
    .A_N(threshold[0]),
    .B(\prio[13] [0]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__maj3_1 _287_ (
    .A(_069_),
    .B(threshold[1]),
    .C(_089_),
    .X(_090_)
  );
  sky130_fd_sc_hd__and3_1 _288_ (
    .A(enable[13]),
    .B(pending[13]),
    .C(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(_088_),
    .B(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2b_1 _290_ (
    .A_N(threshold[0]),
    .B(\prio[14] [0]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__maj3_1 _291_ (
    .A(_073_),
    .B(threshold[1]),
    .C(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nand3_1 _292_ (
    .A(pending[14]),
    .B(enable[14]),
    .C(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2b_1 _293_ (
    .A_N(\prio[15] [1]),
    .B(threshold[1]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2b_1 _294_ (
    .A_N(threshold[1]),
    .B(\prio[15] [1]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand3_1 _295_ (
    .A(enable[15]),
    .B(pending[15]),
    .C(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a31oi_1 _296_ (
    .A1(\prio[15] [0]),
    .A2(_079_),
    .A3(_096_),
    .B1(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__clkinv_1 _297_ (
    .A(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(_095_),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _299_ (
    .A(\prio[10] [0]),
    .B(_079_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__maj3_1 _300_ (
    .A(_074_),
    .B(threshold[1]),
    .C(_102_),
    .X(_103_)
  );
  sky130_fd_sc_hd__nand3_1 _301_ (
    .A(pending[10]),
    .B(enable[10]),
    .C(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(\prio[11] [0]),
    .B(_079_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__maj3_1 _303_ (
    .A(_070_),
    .B(threshold[1]),
    .C(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__nand3_1 _304_ (
    .A(enable[11]),
    .B(pending[11]),
    .C(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _305_ (
    .A(_104_),
    .B(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21oi_1 _306_ (
    .A1(_092_),
    .A2(_101_),
    .B1(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(\prio[8] [0]),
    .B(_079_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__maj3_1 _308_ (
    .A(_076_),
    .B(threshold[1]),
    .C(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nand3_1 _309_ (
    .A(pending[8]),
    .B(enable[8]),
    .C(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(\prio[9] [0]),
    .B(_079_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__maj3_1 _311_ (
    .A(_071_),
    .B(threshold[1]),
    .C(_113_),
    .X(_114_)
  );
  sky130_fd_sc_hd__nand3_1 _312_ (
    .A(enable[9]),
    .B(pending[9]),
    .C(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _313_ (
    .A(_112_),
    .B(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2b_1 _314_ (
    .A_N(\prio[6] [1]),
    .B(threshold[1]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2b_1 _315_ (
    .A_N(threshold[1]),
    .B(\prio[6] [1]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand3_1 _316_ (
    .A(pending[6]),
    .B(enable[6]),
    .C(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a31oi_1 _317_ (
    .A1(\prio[6] [0]),
    .A2(_079_),
    .A3(_117_),
    .B1(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2b_1 _318_ (
    .A_N(\prio[7] [1]),
    .B(threshold[1]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2b_1 _319_ (
    .A_N(threshold[1]),
    .B(\prio[7] [1]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand3_1 _320_ (
    .A(enable[7]),
    .B(pending[7]),
    .C(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a31oi_1 _321_ (
    .A1(\prio[7] [0]),
    .A2(_079_),
    .A3(_121_),
    .B1(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_1 _322_ (
    .A(_120_),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o21ai_0 _323_ (
    .A1(_109_),
    .A2(_116_),
    .B1(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(\prio[4] [0]),
    .B(_079_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__maj3_1 _325_ (
    .A(_080_),
    .B(threshold[1]),
    .C(_127_),
    .X(_128_)
  );
  sky130_fd_sc_hd__nand3_1 _326_ (
    .A(pending[4]),
    .B(enable[4]),
    .C(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(\prio[5] [0]),
    .B(_079_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__maj3_1 _328_ (
    .A(_075_),
    .B(threshold[1]),
    .C(_130_),
    .X(_131_)
  );
  sky130_fd_sc_hd__nand3_1 _329_ (
    .A(enable[5]),
    .B(pending[5]),
    .C(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2b_1 _330_ (
    .A_N(\prio[2] [1]),
    .B(threshold[1]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2b_1 _331_ (
    .A_N(threshold[1]),
    .B(\prio[2] [1]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand3_1 _332_ (
    .A(enable[2]),
    .B(pending[2]),
    .C(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a31oi_1 _333_ (
    .A1(\prio[2] [0]),
    .A2(_079_),
    .A3(_133_),
    .B1(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(\prio[3] [0]),
    .B(_079_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__maj3_1 _335_ (
    .A(_078_),
    .B(threshold[1]),
    .C(_137_),
    .X(_138_)
  );
  sky130_fd_sc_hd__nand3_1 _336_ (
    .A(enable[3]),
    .B(pending[3]),
    .C(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand2b_1 _337_ (
    .A_N(_136_),
    .B(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a31oi_1 _338_ (
    .A1(_126_),
    .A2(_129_),
    .A3(_132_),
    .B1(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nand2_1 _339_ (
    .A(\prio[0] [0]),
    .B(_079_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__maj3_1 _340_ (
    .A(_072_),
    .B(threshold[1]),
    .C(_142_),
    .X(_143_)
  );
  sky130_fd_sc_hd__nand3_1 _341_ (
    .A(pending[0]),
    .B(enable[0]),
    .C(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(\prio[1] [0]),
    .B(_079_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__maj3_1 _343_ (
    .A(_077_),
    .B(threshold[1]),
    .C(_145_),
    .X(_146_)
  );
  sky130_fd_sc_hd__nand3_1 _344_ (
    .A(pending[1]),
    .B(enable[1]),
    .C(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(_144_),
    .B(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2_1 _346_ (
    .A(_141_),
    .B(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(_084_),
    .B(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__clkinv_1 _348_ (
    .A(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21oi_1 _349_ (
    .A1(_095_),
    .A2(_099_),
    .B1(_091_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _350_ (
    .A1(_088_),
    .A2(_152_),
    .B1(_107_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21bo_1 _351_ (
    .A1(_104_),
    .A2(_153_),
    .B1_N(_115_),
    .X(_154_)
  );
  sky130_fd_sc_hd__a21oi_1 _352_ (
    .A1(_112_),
    .A2(_154_),
    .B1(_124_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o21ai_0 _353_ (
    .A1(_120_),
    .A2(_155_),
    .B1(_132_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a21boi_0 _354_ (
    .A1(_129_),
    .A2(_156_),
    .B1_N(_139_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o21ai_0 _355_ (
    .A1(_136_),
    .A2(_157_),
    .B1(_147_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _356_ (
    .A(_144_),
    .B(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand3_1 _357_ (
    .A(_092_),
    .B(_095_),
    .C(_100_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _358_ (
    .A(_108_),
    .B(_116_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _359_ (
    .A(_160_),
    .B(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__and3_1 _360_ (
    .A(_125_),
    .B(_129_),
    .C(_132_),
    .X(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _361_ (
    .A(_140_),
    .B(_148_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _362_ (
    .A(_084_),
    .B(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a21oi_1 _363_ (
    .A1(_162_),
    .A2(_163_),
    .B1(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a21o_1 _364_ (
    .A1(_162_),
    .A2(_163_),
    .B1(_165_),
    .X(_167_)
  );
  sky130_fd_sc_hd__and2_0 _365_ (
    .A(_163_),
    .B(_164_),
    .X(_168_)
  );
  sky130_fd_sc_hd__nor3_1 _366_ (
    .A(_108_),
    .B(_116_),
    .C(_160_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nor3b_1 _367_ (
    .A(_169_),
    .B(_165_),
    .C_N(_163_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand3b_1 _368_ (
    .A_N(_169_),
    .B(_168_),
    .C(_084_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_1 _369_ (
    .A(pending[14]),
    .B(irq_sync2[14]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a41oi_1 _370_ (
    .A1(_151_),
    .A2(_159_),
    .A3(_166_),
    .A4(_170_),
    .B1(_172_),
    .Y(_000_[14])
  );
  sky130_fd_sc_hd__and3_1 _371_ (
    .A(_084_),
    .B(_144_),
    .C(_158_),
    .X(_173_)
  );
  sky130_fd_sc_hd__nand3_1 _372_ (
    .A(_084_),
    .B(_144_),
    .C(_158_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _373_ (
    .A(pending[13]),
    .B(irq_sync2[13]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a41oi_1 _374_ (
    .A1(_150_),
    .A2(_166_),
    .A3(_170_),
    .A4(_173_),
    .B1(_175_),
    .Y(_000_[13])
  );
  sky130_fd_sc_hd__nor2_1 _375_ (
    .A(pending[12]),
    .B(irq_sync2[12]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__a41oi_1 _376_ (
    .A1(_150_),
    .A2(_166_),
    .A3(_170_),
    .A4(_174_),
    .B1(_176_),
    .Y(_000_[12])
  );
  sky130_fd_sc_hd__nor2_1 _377_ (
    .A(pending[11]),
    .B(irq_sync2[11]),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a41oi_1 _378_ (
    .A1(_149_),
    .A2(_167_),
    .A3(_170_),
    .A4(_173_),
    .B1(_177_),
    .Y(_000_[11])
  );
  sky130_fd_sc_hd__nor2_1 _379_ (
    .A(pending[10]),
    .B(irq_sync2[10]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a41oi_1 _380_ (
    .A1(_151_),
    .A2(_159_),
    .A3(_167_),
    .A4(_170_),
    .B1(_178_),
    .Y(_000_[10])
  );
  sky130_fd_sc_hd__nor2_1 _381_ (
    .A(pending[9]),
    .B(irq_sync2[9]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a41oi_1 _382_ (
    .A1(_150_),
    .A2(_167_),
    .A3(_170_),
    .A4(_173_),
    .B1(_179_),
    .Y(_000_[9])
  );
  sky130_fd_sc_hd__nor2_1 _383_ (
    .A(pending[8]),
    .B(irq_sync2[8]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__a41oi_1 _384_ (
    .A1(_150_),
    .A2(_167_),
    .A3(_170_),
    .A4(_174_),
    .B1(_180_),
    .Y(_000_[8])
  );
  sky130_fd_sc_hd__nor2_1 _385_ (
    .A(pending[7]),
    .B(irq_sync2[7]),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a41oi_1 _386_ (
    .A1(_149_),
    .A2(_166_),
    .A3(_171_),
    .A4(_173_),
    .B1(_181_),
    .Y(_000_[7])
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(pending[6]),
    .B(irq_sync2[6]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a41oi_1 _388_ (
    .A1(_151_),
    .A2(_159_),
    .A3(_166_),
    .A4(_171_),
    .B1(_182_),
    .Y(_000_[6])
  );
  sky130_fd_sc_hd__nor2_1 _389_ (
    .A(pending[5]),
    .B(irq_sync2[5]),
    .Y(_183_)
  );
  sky130_fd_sc_hd__a41oi_1 _390_ (
    .A1(_150_),
    .A2(_166_),
    .A3(_171_),
    .A4(_173_),
    .B1(_183_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__nor2_1 _391_ (
    .A(pending[4]),
    .B(irq_sync2[4]),
    .Y(_184_)
  );
  sky130_fd_sc_hd__a41oi_1 _392_ (
    .A1(_150_),
    .A2(_166_),
    .A3(_171_),
    .A4(_174_),
    .B1(_184_),
    .Y(_000_[4])
  );
  sky130_fd_sc_hd__nor2_1 _393_ (
    .A(pending[3]),
    .B(irq_sync2[3]),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a41oi_1 _394_ (
    .A1(_149_),
    .A2(_167_),
    .A3(_171_),
    .A4(_173_),
    .B1(_185_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__nor2_1 _395_ (
    .A(pending[2]),
    .B(irq_sync2[2]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a41oi_1 _396_ (
    .A1(_151_),
    .A2(_159_),
    .A3(_167_),
    .A4(_171_),
    .B1(_186_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nor2_1 _397_ (
    .A(pending[1]),
    .B(irq_sync2[1]),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a41oi_1 _398_ (
    .A1(_150_),
    .A2(_167_),
    .A3(_171_),
    .A4(_173_),
    .B1(_187_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nor2_1 _399_ (
    .A(pending[0]),
    .B(irq_sync2[0]),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand4_1 _400_ (
    .A(pending[0]),
    .B(enable[0]),
    .C(_084_),
    .D(_167_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor3_1 _401_ (
    .A(_149_),
    .B(_170_),
    .C(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__a21oi_1 _402_ (
    .A1(_159_),
    .A2(_190_),
    .B1(_188_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__nor3b_1 _403_ (
    .A(wb_adr_i[2]),
    .B(wb_adr_i[4]),
    .C_N(wb_adr_i[3]),
    .Y(_191_)
  );
  sky130_fd_sc_hd__and3_1 _404_ (
    .A(wb_we_i),
    .B(_002_),
    .C(_191_),
    .X(_192_)
  );
  sky130_fd_sc_hd__mux2_1 _405_ (
    .A0(\prio[1] [0]),
    .A1(wb_dat_i[2]),
    .S(_192_),
    .X(_003_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _406_ (
    .A(_083_),
    .SLEEP(wb_adr_i[4]),
    .X(_193_)
  );
  sky130_fd_sc_hd__and3_1 _407_ (
    .A(wb_we_i),
    .B(_002_),
    .C(_193_),
    .X(_194_)
  );
  sky130_fd_sc_hd__mux2_1 _408_ (
    .A0(enable[14]),
    .A1(wb_dat_i[14]),
    .S(_194_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _409_ (
    .A0(enable[13]),
    .A1(wb_dat_i[13]),
    .S(_194_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _410_ (
    .A0(enable[12]),
    .A1(wb_dat_i[12]),
    .S(_194_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _411_ (
    .A0(enable[11]),
    .A1(wb_dat_i[11]),
    .S(_194_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _412_ (
    .A0(enable[10]),
    .A1(wb_dat_i[10]),
    .S(_194_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _413_ (
    .A0(enable[9]),
    .A1(wb_dat_i[9]),
    .S(_194_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _414_ (
    .A0(enable[8]),
    .A1(wb_dat_i[8]),
    .S(_194_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _415_ (
    .A0(enable[7]),
    .A1(wb_dat_i[7]),
    .S(_194_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _416_ (
    .A0(enable[6]),
    .A1(wb_dat_i[6]),
    .S(_194_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _417_ (
    .A0(enable[5]),
    .A1(wb_dat_i[5]),
    .S(_194_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _418_ (
    .A0(enable[4]),
    .A1(wb_dat_i[4]),
    .S(_194_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _419_ (
    .A0(enable[3]),
    .A1(wb_dat_i[3]),
    .S(_194_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _420_ (
    .A0(enable[2]),
    .A1(wb_dat_i[2]),
    .S(_194_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _421_ (
    .A0(enable[1]),
    .A1(wb_dat_i[1]),
    .S(_194_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _422_ (
    .A0(enable[0]),
    .A1(wb_dat_i[0]),
    .S(_194_),
    .X(_018_)
  );
  sky130_fd_sc_hd__and3b_1 _423_ (
    .A_N(wb_adr_i[4]),
    .B(wb_adr_i[2]),
    .C(wb_adr_i[3]),
    .X(_195_)
  );
  sky130_fd_sc_hd__and3_1 _424_ (
    .A(wb_we_i),
    .B(_002_),
    .C(_195_),
    .X(_196_)
  );
  sky130_fd_sc_hd__mux2_1 _425_ (
    .A0(\prio[9] [0]),
    .A1(wb_dat_i[2]),
    .S(_196_),
    .X(_019_)
  );
  sky130_fd_sc_hd__nor3b_1 _426_ (
    .A(wb_adr_i[3]),
    .B(wb_adr_i[2]),
    .C_N(wb_adr_i[4]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nand3_1 _427_ (
    .A(wb_we_i),
    .B(_002_),
    .C(_197_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor2_1 _428_ (
    .A(wb_dat_i[0]),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a21oi_1 _429_ (
    .A1(_079_),
    .A2(_198_),
    .B1(_199_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _430_ (
    .A0(\prio[5] [0]),
    .A1(wb_dat_i[10]),
    .S(_192_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _431_ (
    .A0(\prio[2] [0]),
    .A1(wb_dat_i[4]),
    .S(_192_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _432_ (
    .A0(\prio[7] [0]),
    .A1(wb_dat_i[14]),
    .S(_192_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _433_ (
    .A0(\prio[13] [0]),
    .A1(wb_dat_i[10]),
    .S(_196_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _434_ (
    .A0(\prio[3] [0]),
    .A1(wb_dat_i[6]),
    .S(_192_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _435_ (
    .A0(\prio[15] [0]),
    .A1(wb_dat_i[14]),
    .S(_196_),
    .X(_026_)
  );
  sky130_fd_sc_hd__nor3_1 _436_ (
    .A(wb_adr_i[3]),
    .B(wb_adr_i[2]),
    .C(wb_adr_i[4]),
    .Y(_200_)
  );
  sky130_fd_sc_hd__a22oi_1 _437_ (
    .A1(\prio[7] [0]),
    .A2(_191_),
    .B1(_200_),
    .B2(pending[14]),
    .Y(_201_)
  );
  sky130_fd_sc_hd__a22oi_1 _438_ (
    .A1(enable[14]),
    .A2(_193_),
    .B1(_195_),
    .B2(\prio[15] [0]),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nor2_1 _439_ (
    .A(wb_dat_o[14]),
    .B(_082_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__a31oi_1 _440_ (
    .A1(_082_),
    .A2(_201_),
    .A3(_202_),
    .B1(_203_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _441_ (
    .A(\prio[3] [0]),
    .B(_191_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor2_1 _442_ (
    .A(wb_dat_o[6]),
    .B(_082_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__a222oi_1 _443_ (
    .A1(enable[6]),
    .A2(_193_),
    .B1(_195_),
    .B2(\prio[11] [0]),
    .C1(_200_),
    .C2(pending[6]),
    .Y(_206_)
  );
  sky130_fd_sc_hd__a31oi_1 _444_ (
    .A1(_082_),
    .A2(_204_),
    .A3(_206_),
    .B1(_205_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a22oi_1 _445_ (
    .A1(\prio[2] [0]),
    .A2(_191_),
    .B1(_195_),
    .B2(\prio[10] [0]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__a22oi_1 _446_ (
    .A1(enable[4]),
    .A2(_193_),
    .B1(_200_),
    .B2(pending[4]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nor2_1 _447_ (
    .A(wb_dat_o[4]),
    .B(_082_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__a31oi_1 _448_ (
    .A1(_082_),
    .A2(_207_),
    .A3(_208_),
    .B1(_209_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _449_ (
    .A(\prio[9] [0]),
    .B(_195_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__a222oi_1 _450_ (
    .A1(\prio[1] [0]),
    .A2(_191_),
    .B1(_193_),
    .B2(enable[2]),
    .C1(_200_),
    .C2(pending[2]),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand3_1 _451_ (
    .A(_082_),
    .B(_210_),
    .C(_211_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__o22a_1 _452_ (
    .A1(wb_dat_o[2]),
    .A2(_082_),
    .B1(_166_),
    .B2(_212_),
    .X(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _453_ (
    .A(wb_dat_o[0]),
    .B(_082_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nand2_1 _454_ (
    .A(\prio[0] [0]),
    .B(_191_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__a222oi_1 _455_ (
    .A1(\prio[8] [0]),
    .A2(_195_),
    .B1(_197_),
    .B2(threshold[0]),
    .C1(_200_),
    .C2(pending[0]),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nand3_1 _456_ (
    .A(_082_),
    .B(_214_),
    .C(_215_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__a21oi_1 _457_ (
    .A1(enable[0]),
    .A2(_193_),
    .B1(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__a21oi_1 _458_ (
    .A1(_174_),
    .A2(_217_),
    .B1(_213_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a22oi_1 _459_ (
    .A1(enable[12]),
    .A2(_193_),
    .B1(_200_),
    .B2(pending[12]),
    .Y(_218_)
  );
  sky130_fd_sc_hd__a22oi_1 _460_ (
    .A1(\prio[6] [0]),
    .A2(_191_),
    .B1(_195_),
    .B2(\prio[14] [0]),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nor2_1 _461_ (
    .A(wb_dat_o[12]),
    .B(_082_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__a31oi_1 _462_ (
    .A1(_082_),
    .A2(_218_),
    .A3(_219_),
    .B1(_220_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a22oi_1 _463_ (
    .A1(\prio[4] [0]),
    .A2(_191_),
    .B1(_200_),
    .B2(pending[8]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__a22oi_1 _464_ (
    .A1(enable[8]),
    .A2(_193_),
    .B1(_195_),
    .B2(\prio[12] [0]),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nor2_1 _465_ (
    .A(wb_dat_o[8]),
    .B(_082_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__a31oi_1 _466_ (
    .A1(_082_),
    .A2(_221_),
    .A3(_222_),
    .B1(_223_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _467_ (
    .A(\prio[5] [0]),
    .B(_191_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nor2_1 _468_ (
    .A(wb_dat_o[10]),
    .B(_082_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__a222oi_1 _469_ (
    .A1(enable[10]),
    .A2(_193_),
    .B1(_195_),
    .B2(\prio[13] [0]),
    .C1(pending[10]),
    .C2(_200_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__a31oi_1 _470_ (
    .A1(_082_),
    .A2(_224_),
    .A3(_226_),
    .B1(_225_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _471_ (
    .A0(\prio[12] [0]),
    .A1(wb_dat_i[8]),
    .S(_196_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _472_ (
    .A0(\prio[14] [0]),
    .A1(wb_dat_i[12]),
    .S(_196_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _473_ (
    .A0(\prio[4] [0]),
    .A1(wb_dat_i[8]),
    .S(_192_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _474_ (
    .A0(\prio[8] [0]),
    .A1(wb_dat_i[0]),
    .S(_196_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _475_ (
    .A0(\prio[0] [0]),
    .A1(wb_dat_i[0]),
    .S(_192_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _476_ (
    .A0(\prio[6] [0]),
    .A1(wb_dat_i[12]),
    .S(_192_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _477_ (
    .A0(\prio[11] [0]),
    .A1(wb_dat_i[6]),
    .S(_196_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _478_ (
    .A0(\prio[10] [0]),
    .A1(wb_dat_i[4]),
    .S(_196_),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _479_ (
    .A(wb_dat_i[1]),
    .B(_196_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__o21ai_0 _480_ (
    .A1(_076_),
    .A2(_196_),
    .B1(_227_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _481_ (
    .A(\prio[9] [1]),
    .B(_195_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__a222oi_1 _482_ (
    .A1(\prio[1] [1]),
    .A2(_191_),
    .B1(_200_),
    .B2(pending[3]),
    .C1(_193_),
    .C2(enable[3]),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand3_1 _483_ (
    .A(_082_),
    .B(_228_),
    .C(_229_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o22a_1 _484_ (
    .A1(wb_dat_o[3]),
    .A2(_082_),
    .B1(_170_),
    .B2(_230_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _485_ (
    .A(wb_dat_i[9]),
    .B(_192_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__o21ai_0 _486_ (
    .A1(_080_),
    .A2(_192_),
    .B1(_231_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _487_ (
    .A(\prio[7] [1]),
    .B(_191_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nor2_1 _488_ (
    .A(wb_dat_o[15]),
    .B(_082_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__a222oi_1 _489_ (
    .A1(enable[15]),
    .A2(_193_),
    .B1(_200_),
    .B2(pending[15]),
    .C1(_195_),
    .C2(\prio[15] [1]),
    .Y(_234_)
  );
  sky130_fd_sc_hd__a31oi_1 _490_ (
    .A1(_082_),
    .A2(_232_),
    .A3(_234_),
    .B1(_233_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _491_ (
    .A(wb_dat_i[13]),
    .B(_196_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__o21ai_0 _492_ (
    .A1(_073_),
    .A2(_196_),
    .B1(_235_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _493_ (
    .A0(\prio[12] [1]),
    .A1(wb_dat_i[9]),
    .S(_196_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _494_ (
    .A(wb_dat_o[1]),
    .B(_082_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand2_1 _495_ (
    .A(enable[1]),
    .B(_193_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__a222oi_1 _496_ (
    .A1(\prio[0] [1]),
    .A2(_191_),
    .B1(_197_),
    .B2(threshold[1]),
    .C1(_200_),
    .C2(pending[1]),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nand3_1 _497_ (
    .A(_082_),
    .B(_237_),
    .C(_238_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__a21oi_1 _498_ (
    .A1(\prio[8] [1]),
    .A2(_195_),
    .B1(_239_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__a21oi_1 _499_ (
    .A1(_150_),
    .A2(_240_),
    .B1(_236_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _500_ (
    .A(\prio[5] [1]),
    .B(_191_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nor2_1 _501_ (
    .A(wb_dat_o[11]),
    .B(_082_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__a222oi_1 _502_ (
    .A1(enable[11]),
    .A2(_193_),
    .B1(_200_),
    .B2(pending[11]),
    .C1(_195_),
    .C2(\prio[13] [1]),
    .Y(_243_)
  );
  sky130_fd_sc_hd__a31oi_1 _503_ (
    .A1(_082_),
    .A2(_241_),
    .A3(_243_),
    .B1(_242_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _504_ (
    .A0(\prio[15] [1]),
    .A1(wb_dat_i[15]),
    .S(_196_),
    .X(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _505_ (
    .A(wb_dat_i[7]),
    .B(_192_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__o21ai_0 _506_ (
    .A1(_078_),
    .A2(_192_),
    .B1(_244_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _507_ (
    .A(wb_dat_i[11]),
    .B(_196_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__o21ai_0 _508_ (
    .A1(_069_),
    .A2(_196_),
    .B1(_245_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _509_ (
    .A(\prio[3] [1]),
    .B(_191_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nor2_1 _510_ (
    .A(wb_dat_o[7]),
    .B(_082_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__a222oi_1 _511_ (
    .A1(enable[7]),
    .A2(_193_),
    .B1(_200_),
    .B2(pending[7]),
    .C1(_195_),
    .C2(\prio[11] [1]),
    .Y(_248_)
  );
  sky130_fd_sc_hd__a31oi_1 _512_ (
    .A1(_082_),
    .A2(_246_),
    .A3(_248_),
    .B1(_247_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _513_ (
    .A0(\prio[7] [1]),
    .A1(wb_dat_i[15]),
    .S(_192_),
    .X(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _514_ (
    .A(wb_dat_i[5]),
    .B(_196_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__o21ai_0 _515_ (
    .A1(_074_),
    .A2(_196_),
    .B1(_249_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _516_ (
    .A0(\prio[6] [1]),
    .A1(wb_dat_i[13]),
    .S(_192_),
    .X(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _517_ (
    .A(wb_dat_i[1]),
    .B(_192_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__o21ai_0 _518_ (
    .A1(_072_),
    .A2(_192_),
    .B1(_250_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a22oi_1 _519_ (
    .A1(\prio[6] [1]),
    .A2(_191_),
    .B1(_200_),
    .B2(pending[13]),
    .Y(_251_)
  );
  sky130_fd_sc_hd__a22oi_1 _520_ (
    .A1(enable[13]),
    .A2(_193_),
    .B1(_195_),
    .B2(\prio[14] [1]),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nor2_1 _521_ (
    .A(wb_dat_o[13]),
    .B(_082_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__a31oi_1 _522_ (
    .A1(_082_),
    .A2(_251_),
    .A3(_252_),
    .B1(_253_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _523_ (
    .A(_168_),
    .B(_169_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _524_ (
    .A(pending[15]),
    .B(irq_sync2[15]),
    .Y(_254_)
  );
  sky130_fd_sc_hd__a41oi_1 _525_ (
    .A1(_149_),
    .A2(_166_),
    .A3(_170_),
    .A4(_173_),
    .B1(_254_),
    .Y(_000_[15])
  );
  sky130_fd_sc_hd__mux2_1 _526_ (
    .A0(\prio[2] [1]),
    .A1(wb_dat_i[5]),
    .S(_192_),
    .X(_060_)
  );
  sky130_fd_sc_hd__a22oi_1 _527_ (
    .A1(\prio[2] [1]),
    .A2(_191_),
    .B1(_195_),
    .B2(\prio[10] [1]),
    .Y(_255_)
  );
  sky130_fd_sc_hd__a22oi_1 _528_ (
    .A1(enable[5]),
    .A2(_193_),
    .B1(_200_),
    .B2(pending[5]),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nor2_1 _529_ (
    .A(wb_dat_o[5]),
    .B(_082_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__a31oi_1 _530_ (
    .A1(_082_),
    .A2(_255_),
    .A3(_256_),
    .B1(_257_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _531_ (
    .A(wb_dat_i[11]),
    .B(_192_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__o21ai_0 _532_ (
    .A1(_075_),
    .A2(_192_),
    .B1(_258_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _533_ (
    .A0(wb_dat_i[1]),
    .A1(threshold[1]),
    .S(_198_),
    .X(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _534_ (
    .A(wb_dat_i[3]),
    .B(_196_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__o21ai_0 _535_ (
    .A1(_071_),
    .A2(_196_),
    .B1(_259_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _536_ (
    .A(wb_dat_i[7]),
    .B(_196_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__o21ai_0 _537_ (
    .A1(_070_),
    .A2(_196_),
    .B1(_260_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _538_ (
    .A0(enable[15]),
    .A1(wb_dat_i[15]),
    .S(_194_),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _539_ (
    .A(wb_dat_i[3]),
    .B(_192_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__o21ai_0 _540_ (
    .A1(_077_),
    .A2(_192_),
    .B1(_261_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _541_ (
    .A(\prio[4] [1]),
    .B(_191_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nor2_1 _542_ (
    .A(wb_dat_o[9]),
    .B(_082_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__a222oi_1 _543_ (
    .A1(enable[9]),
    .A2(_193_),
    .B1(_200_),
    .B2(pending[9]),
    .C1(_195_),
    .C2(\prio[12] [1]),
    .Y(_264_)
  );
  sky130_fd_sc_hd__a31oi_1 _544_ (
    .A1(_082_),
    .A2(_262_),
    .A3(_264_),
    .B1(_263_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__dfstp_2 _545_ (
    .CLK(clk_i),
    .D(_042_),
    .Q(\prio[10] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _546_ (
    .CLK(clk_i),
    .D(_056_),
    .Q(\prio[10] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _547_ (
    .CLK(clk_i),
    .D(_041_),
    .Q(\prio[11] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _548_ (
    .CLK(clk_i),
    .D(_065_),
    .Q(\prio[11] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _549_ (
    .CLK(clk_i),
    .D(_040_),
    .Q(\prio[6] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _550_ (
    .CLK(clk_i),
    .D(_057_),
    .Q(\prio[6] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _551_ (
    .CLK(clk_i),
    .D(_039_),
    .Q(\prio[0] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _552_ (
    .CLK(clk_i),
    .D(_058_),
    .Q(\prio[0] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _553_ (
    .CLK(clk_i),
    .D(_038_),
    .Q(\prio[8] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _554_ (
    .CLK(clk_i),
    .D(_043_),
    .Q(\prio[8] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _555_ (
    .CLK(clk_i),
    .D(_037_),
    .Q(\prio[4] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _556_ (
    .CLK(clk_i),
    .D(_045_),
    .Q(\prio[4] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _557_ (
    .CLK(clk_i),
    .D(_036_),
    .Q(\prio[14] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _558_ (
    .CLK(clk_i),
    .D(_047_),
    .Q(\prio[14] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _559_ (
    .CLK(clk_i),
    .D(_035_),
    .Q(\prio[12] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _560_ (
    .CLK(clk_i),
    .D(_048_),
    .Q(\prio[12] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _561_ (
    .CLK(clk_i),
    .D(_034_),
    .Q(wb_dat_o[10]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _562_ (
    .CLK(clk_i),
    .D(_050_),
    .Q(wb_dat_o[11]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _563_ (
    .CLK(clk_i),
    .D(_033_),
    .Q(wb_dat_o[8]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _564_ (
    .CLK(clk_i),
    .D(_068_),
    .Q(wb_dat_o[9]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _565_ (
    .CLK(clk_i),
    .D(_032_),
    .Q(wb_dat_o[12]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _566_ (
    .CLK(clk_i),
    .D(_059_),
    .Q(wb_dat_o[13]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _567_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(wb_dat_o[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _568_ (
    .CLK(clk_i),
    .D(_049_),
    .Q(wb_dat_o[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _569_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(wb_dat_o[2]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _570_ (
    .CLK(clk_i),
    .D(_044_),
    .Q(wb_dat_o[3]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _571_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(wb_dat_o[4]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _572_ (
    .CLK(clk_i),
    .D(_061_),
    .Q(wb_dat_o[5]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _573_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(wb_dat_o[6]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _574_ (
    .CLK(clk_i),
    .D(_054_),
    .Q(wb_dat_o[7]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _575_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(wb_dat_o[14]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _576_ (
    .CLK(clk_i),
    .D(_046_),
    .Q(wb_dat_o[15]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _577_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(\prio[15] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _578_ (
    .CLK(clk_i),
    .D(_051_),
    .Q(\prio[15] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _579_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(\prio[3] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _580_ (
    .CLK(clk_i),
    .D(_052_),
    .Q(\prio[3] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _581_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(\prio[13] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _582_ (
    .CLK(clk_i),
    .D(_053_),
    .Q(\prio[13] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _583_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(\prio[7] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _584_ (
    .CLK(clk_i),
    .D(_055_),
    .Q(\prio[7] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _585_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(\prio[2] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _586_ (
    .CLK(clk_i),
    .D(_060_),
    .Q(\prio[2] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _587_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(\prio[5] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _588_ (
    .CLK(clk_i),
    .D(_062_),
    .Q(\prio[5] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _589_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(threshold[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _590_ (
    .CLK(clk_i),
    .D(_063_),
    .Q(threshold[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _591_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(\prio[9] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _592_ (
    .CLK(clk_i),
    .D(_064_),
    .Q(\prio[9] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _593_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(enable[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _594_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(enable[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _595_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(enable[2]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _596_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(enable[3]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _597_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(enable[4]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _598_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(enable[5]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _599_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(enable[6]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _600_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(enable[7]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _601_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(enable[8]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _602_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(enable[9]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _603_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(enable[10]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _604_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(enable[11]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _605_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(enable[12]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _606_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(enable[13]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _607_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(enable[14]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _608_ (
    .CLK(clk_i),
    .D(_066_),
    .Q(enable[15]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _609_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(\prio[1] [0]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _610_ (
    .CLK(clk_i),
    .D(_067_),
    .Q(\prio[1] [1]),
    .SET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _611_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(wb_ack_o),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _612_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(m_irq_o),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _613_ (
    .CLK(clk_i),
    .D(_000_[0]),
    .Q(pending[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _614_ (
    .CLK(clk_i),
    .D(_000_[1]),
    .Q(pending[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _615_ (
    .CLK(clk_i),
    .D(_000_[2]),
    .Q(pending[2]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _616_ (
    .CLK(clk_i),
    .D(_000_[3]),
    .Q(pending[3]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _617_ (
    .CLK(clk_i),
    .D(_000_[4]),
    .Q(pending[4]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _618_ (
    .CLK(clk_i),
    .D(_000_[5]),
    .Q(pending[5]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _619_ (
    .CLK(clk_i),
    .D(_000_[6]),
    .Q(pending[6]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _620_ (
    .CLK(clk_i),
    .D(_000_[7]),
    .Q(pending[7]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _621_ (
    .CLK(clk_i),
    .D(_000_[8]),
    .Q(pending[8]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _622_ (
    .CLK(clk_i),
    .D(_000_[9]),
    .Q(pending[9]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _623_ (
    .CLK(clk_i),
    .D(_000_[10]),
    .Q(pending[10]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _624_ (
    .CLK(clk_i),
    .D(_000_[11]),
    .Q(pending[11]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _625_ (
    .CLK(clk_i),
    .D(_000_[12]),
    .Q(pending[12]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _626_ (
    .CLK(clk_i),
    .D(_000_[13]),
    .Q(pending[13]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _627_ (
    .CLK(clk_i),
    .D(_000_[14]),
    .Q(pending[14]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _628_ (
    .CLK(clk_i),
    .D(_000_[15]),
    .Q(pending[15]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _629_ (
    .CLK(clk_i),
    .D(irq_src_i[0]),
    .Q(irq_sync1[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _630_ (
    .CLK(clk_i),
    .D(irq_src_i[1]),
    .Q(irq_sync1[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _631_ (
    .CLK(clk_i),
    .D(irq_src_i[2]),
    .Q(irq_sync1[2]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _632_ (
    .CLK(clk_i),
    .D(irq_src_i[3]),
    .Q(irq_sync1[3]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _633_ (
    .CLK(clk_i),
    .D(irq_src_i[4]),
    .Q(irq_sync1[4]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _634_ (
    .CLK(clk_i),
    .D(irq_src_i[5]),
    .Q(irq_sync1[5]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _635_ (
    .CLK(clk_i),
    .D(irq_src_i[6]),
    .Q(irq_sync1[6]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _636_ (
    .CLK(clk_i),
    .D(irq_src_i[7]),
    .Q(irq_sync1[7]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _637_ (
    .CLK(clk_i),
    .D(irq_src_i[8]),
    .Q(irq_sync1[8]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _638_ (
    .CLK(clk_i),
    .D(irq_src_i[9]),
    .Q(irq_sync1[9]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _639_ (
    .CLK(clk_i),
    .D(irq_src_i[10]),
    .Q(irq_sync1[10]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _640_ (
    .CLK(clk_i),
    .D(irq_src_i[11]),
    .Q(irq_sync1[11]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _641_ (
    .CLK(clk_i),
    .D(irq_src_i[12]),
    .Q(irq_sync1[12]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _642_ (
    .CLK(clk_i),
    .D(irq_src_i[13]),
    .Q(irq_sync1[13]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _643_ (
    .CLK(clk_i),
    .D(irq_src_i[14]),
    .Q(irq_sync1[14]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _644_ (
    .CLK(clk_i),
    .D(irq_src_i[15]),
    .Q(irq_sync1[15]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _645_ (
    .CLK(clk_i),
    .D(irq_sync1[0]),
    .Q(irq_sync2[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _646_ (
    .CLK(clk_i),
    .D(irq_sync1[1]),
    .Q(irq_sync2[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _647_ (
    .CLK(clk_i),
    .D(irq_sync1[2]),
    .Q(irq_sync2[2]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _648_ (
    .CLK(clk_i),
    .D(irq_sync1[3]),
    .Q(irq_sync2[3]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _649_ (
    .CLK(clk_i),
    .D(irq_sync1[4]),
    .Q(irq_sync2[4]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _650_ (
    .CLK(clk_i),
    .D(irq_sync1[5]),
    .Q(irq_sync2[5]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _651_ (
    .CLK(clk_i),
    .D(irq_sync1[6]),
    .Q(irq_sync2[6]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _652_ (
    .CLK(clk_i),
    .D(irq_sync1[7]),
    .Q(irq_sync2[7]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _653_ (
    .CLK(clk_i),
    .D(irq_sync1[8]),
    .Q(irq_sync2[8]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _654_ (
    .CLK(clk_i),
    .D(irq_sync1[9]),
    .Q(irq_sync2[9]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _655_ (
    .CLK(clk_i),
    .D(irq_sync1[10]),
    .Q(irq_sync2[10]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _656_ (
    .CLK(clk_i),
    .D(irq_sync1[11]),
    .Q(irq_sync2[11]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _657_ (
    .CLK(clk_i),
    .D(irq_sync1[12]),
    .Q(irq_sync2[12]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _658_ (
    .CLK(clk_i),
    .D(irq_sync1[13]),
    .Q(irq_sync2[13]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _659_ (
    .CLK(clk_i),
    .D(irq_sync1[14]),
    .Q(irq_sync2[14]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _660_ (
    .CLK(clk_i),
    .D(irq_sync1[15]),
    .Q(irq_sync2[15]),
    .RESET_B(rst_ni)
  );
  assign wb_dat_o[31:16] = 16'h0000;
endmodule
