/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

module EF_GPIO8(clk, rst_n, io_in, bus_in, io_out, bus_out, io_oe, bus_oe, pin0_hi, pin1_hi, pin2_hi, pin3_hi, pin4_hi, pin5_hi, pin6_hi, pin7_hi, pin0_lo, pin1_lo, pin2_lo, pin3_lo, pin4_lo
, pin5_lo, pin6_lo, pin7_lo, pin0_pe, pin1_pe, pin2_pe, pin3_pe, pin4_pe, pin5_pe, pin6_pe, pin7_pe, pin0_ne, pin1_ne, pin2_ne, pin3_ne, pin4_ne, pin5_ne, pin6_ne, pin7_ne);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [7:0] io_in;
  wire [7:0] io_in;
  output [7:0] bus_in;
  wire [7:0] bus_in;
  output [7:0] io_out;
  wire [7:0] io_out;
  input [7:0] bus_out;
  wire [7:0] bus_out;
  output [7:0] io_oe;
  wire [7:0] io_oe;
  input [7:0] bus_oe;
  wire [7:0] bus_oe;
  output pin0_hi;
  wire pin0_hi;
  output pin1_hi;
  wire pin1_hi;
  output pin2_hi;
  wire pin2_hi;
  output pin3_hi;
  wire pin3_hi;
  output pin4_hi;
  wire pin4_hi;
  output pin5_hi;
  wire pin5_hi;
  output pin6_hi;
  wire pin6_hi;
  output pin7_hi;
  wire pin7_hi;
  output pin0_lo;
  wire pin0_lo;
  output pin1_lo;
  wire pin1_lo;
  output pin2_lo;
  wire pin2_lo;
  output pin3_lo;
  wire pin3_lo;
  output pin4_lo;
  wire pin4_lo;
  output pin5_lo;
  wire pin5_lo;
  output pin6_lo;
  wire pin6_lo;
  output pin7_lo;
  wire pin7_lo;
  output pin0_pe;
  wire pin0_pe;
  output pin1_pe;
  wire pin1_pe;
  output pin2_pe;
  wire pin2_pe;
  output pin3_pe;
  wire pin3_pe;
  output pin4_pe;
  wire pin4_pe;
  output pin5_pe;
  wire pin5_pe;
  output pin6_pe;
  wire pin6_pe;
  output pin7_pe;
  wire pin7_pe;
  output pin0_ne;
  wire pin0_ne;
  output pin1_ne;
  wire pin1_ne;
  output pin2_ne;
  wire pin2_ne;
  output pin3_ne;
  wire pin3_ne;
  output pin4_ne;
  wire pin4_ne;
  output pin5_ne;
  wire pin5_ne;
  output pin6_ne;
  wire pin6_ne;
  output pin7_ne;
  wire pin7_ne;
  wire [7:0] sync_io_in;
  sky130_fd_sc_hd__clkinv_1 _0_ (
    .A(pin7_hi),
    .Y(pin7_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _1_ (
    .A(pin6_hi),
    .Y(pin6_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _2_ (
    .A(pin5_hi),
    .Y(pin5_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(pin4_hi),
    .Y(pin4_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _4_ (
    .A(pin3_hi),
    .Y(pin3_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(pin2_hi),
    .Y(pin2_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _6_ (
    .A(pin1_hi),
    .Y(pin1_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _7_ (
    .A(pin0_hi),
    .Y(pin0_lo)
  );
  ef_util_ned ned_0 (
    .clk(clk),
    .in(pin0_hi),
    .out(pin0_ne)
  );
  ef_util_ned ned_1 (
    .clk(clk),
    .in(pin1_hi),
    .out(pin1_ne)
  );
  ef_util_ned ned_2 (
    .clk(clk),
    .in(pin2_hi),
    .out(pin2_ne)
  );
  ef_util_ned ned_3 (
    .clk(clk),
    .in(pin3_hi),
    .out(pin3_ne)
  );
  ef_util_ned ned_4 (
    .clk(clk),
    .in(pin4_hi),
    .out(pin4_ne)
  );
  ef_util_ned ned_5 (
    .clk(clk),
    .in(pin5_hi),
    .out(pin5_ne)
  );
  ef_util_ned ned_6 (
    .clk(clk),
    .in(pin6_hi),
    .out(pin6_ne)
  );
  ef_util_ned ned_7 (
    .clk(clk),
    .in(pin7_hi),
    .out(pin7_ne)
  );
  ef_util_ped ped_0 (
    .clk(clk),
    .in(pin0_hi),
    .out(pin0_pe)
  );
  ef_util_ped ped_1 (
    .clk(clk),
    .in(pin1_hi),
    .out(pin1_pe)
  );
  ef_util_ped ped_2 (
    .clk(clk),
    .in(pin2_hi),
    .out(pin2_pe)
  );
  ef_util_ped ped_3 (
    .clk(clk),
    .in(pin3_hi),
    .out(pin3_pe)
  );
  ef_util_ped ped_4 (
    .clk(clk),
    .in(pin4_hi),
    .out(pin4_pe)
  );
  ef_util_ped ped_5 (
    .clk(clk),
    .in(pin5_hi),
    .out(pin5_pe)
  );
  ef_util_ped ped_6 (
    .clk(clk),
    .in(pin6_hi),
    .out(pin6_pe)
  );
  ef_util_ped ped_7 (
    .clk(clk),
    .in(pin7_hi),
    .out(pin7_pe)
  );
  ef_util_sync \synchronizer[0]  (
    .clk(clk),
    .in(io_in[0]),
    .out(pin0_hi)
  );
  ef_util_sync \synchronizer[1]  (
    .clk(clk),
    .in(io_in[1]),
    .out(pin1_hi)
  );
  ef_util_sync \synchronizer[2]  (
    .clk(clk),
    .in(io_in[2]),
    .out(pin2_hi)
  );
  ef_util_sync \synchronizer[3]  (
    .clk(clk),
    .in(io_in[3]),
    .out(pin3_hi)
  );
  ef_util_sync \synchronizer[4]  (
    .clk(clk),
    .in(io_in[4]),
    .out(pin4_hi)
  );
  ef_util_sync \synchronizer[5]  (
    .clk(clk),
    .in(io_in[5]),
    .out(pin5_hi)
  );
  ef_util_sync \synchronizer[6]  (
    .clk(clk),
    .in(io_in[6]),
    .out(pin6_hi)
  );
  ef_util_sync \synchronizer[7]  (
    .clk(clk),
    .in(io_in[7]),
    .out(pin7_hi)
  );
  assign sync_io_in = { pin7_hi, pin6_hi, pin5_hi, pin4_hi, pin3_hi, pin2_hi, pin1_hi, pin0_hi };
  assign io_oe = bus_oe;
  assign io_out = bus_out;
  assign bus_in = { pin7_hi, pin6_hi, pin5_hi, pin4_hi, pin3_hi, pin2_hi, pin1_hi, pin0_hi };
endmodule

module EF_GPIO8_WB(clk_i, rst_i, adr_i, dat_i, dat_o, sel_i, cyc_i, stb_i, ack_o, we_i, IRQ, io_in, io_out, io_oe);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input [31:0] adr_i;
  wire [31:0] adr_i;
  input [31:0] dat_i;
  wire [31:0] dat_i;
  output [31:0] dat_o;
  wire [31:0] dat_o;
  input [3:0] sel_i;
  wire [3:0] sel_i;
  input cyc_i;
  wire cyc_i;
  input stb_i;
  wire stb_i;
  output ack_o;
  wire ack_o;
  input we_i;
  wire we_i;
  output IRQ;
  wire IRQ;
  input [7:0] io_in;
  wire [7:0] io_in;
  output [7:0] io_out;
  wire [7:0] io_out;
  output [7:0] io_oe;
  wire [7:0] io_oe;
  wire [31:0] _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire [7:0] DATAI_WIRE;
  wire [7:0] DATAO_REG;
  wire [7:0] DIR_REG;
  wire [0:0] GCLK_REG;
  wire [31:0] IC_REG;
  wire [31:0] IM_REG;
  wire [0:0] P0HI;
  wire [0:0] P0LO;
  wire [0:0] P0NE;
  wire [0:0] P0PE;
  wire [0:0] P1HI;
  wire [0:0] P1LO;
  wire [0:0] P1NE;
  wire [0:0] P1PE;
  wire [0:0] P2HI;
  wire [0:0] P2LO;
  wire [0:0] P2NE;
  wire [0:0] P2PE;
  wire [0:0] P3HI;
  wire [0:0] P3LO;
  wire [0:0] P3NE;
  wire [0:0] P3PE;
  wire [0:0] P4HI;
  wire [0:0] P4LO;
  wire [0:0] P4NE;
  wire [0:0] P4PE;
  wire [0:0] P5HI;
  wire [0:0] P5LO;
  wire [0:0] P5NE;
  wire [0:0] P5PE;
  wire [0:0] P6HI;
  wire [0:0] P6LO;
  wire [0:0] P6NE;
  wire [0:0] P6PE;
  wire [0:0] P7HI;
  wire [0:0] P7LO;
  wire [0:0] P7NE;
  wire [0:0] P7PE;
  wire [31:0] RIS_REG;
  wire [7:0] bus_in;
  wire [7:0] bus_oe;
  wire [7:0] bus_out;
  wire clk;
  wire clk_g;
  wire clk_gated_en;
  wire [0:0] pin0_hi;
  wire [0:0] pin0_lo;
  wire [0:0] pin0_ne;
  wire [0:0] pin0_pe;
  wire [0:0] pin1_hi;
  wire [0:0] pin1_lo;
  wire [0:0] pin1_ne;
  wire [0:0] pin1_pe;
  wire [0:0] pin2_hi;
  wire [0:0] pin2_lo;
  wire [0:0] pin2_ne;
  wire [0:0] pin2_pe;
  wire [0:0] pin3_hi;
  wire [0:0] pin3_lo;
  wire [0:0] pin3_ne;
  wire [0:0] pin3_pe;
  wire [0:0] pin4_hi;
  wire [0:0] pin4_lo;
  wire [0:0] pin4_ne;
  wire [0:0] pin4_pe;
  wire [0:0] pin5_hi;
  wire [0:0] pin5_lo;
  wire [0:0] pin5_ne;
  wire [0:0] pin5_pe;
  wire [0:0] pin6_hi;
  wire [0:0] pin6_lo;
  wire [0:0] pin6_ne;
  wire [0:0] pin6_pe;
  wire [0:0] pin7_hi;
  wire [0:0] pin7_lo;
  wire [0:0] pin7_ne;
  wire [0:0] pin7_pe;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _0414_ (
    .A(RIS_REG[4]),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__clkinv_1 _0415_ (
    .A(IM_REG[8]),
    .Y(_0198_)
  );
  sky130_fd_sc_hd__clkinv_1 _0416_ (
    .A(IM_REG[20]),
    .Y(_0199_)
  );
  sky130_fd_sc_hd__clkinv_1 _0417_ (
    .A(rst_i),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__nor2_1 _0418_ (
    .A(RIS_REG[28]),
    .B(pin4_ne),
    .Y(_0200_)
  );
  sky130_fd_sc_hd__nor2_1 _0419_ (
    .A(IC_REG[28]),
    .B(_0200_),
    .Y(_0196_)
  );
  sky130_fd_sc_hd__nor2_1 _0420_ (
    .A(RIS_REG[27]),
    .B(pin3_ne),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__nor2_1 _0421_ (
    .A(IC_REG[27]),
    .B(_0201_),
    .Y(_0195_)
  );
  sky130_fd_sc_hd__nand4_1 _0422_ (
    .A(adr_i[10]),
    .B(adr_i[9]),
    .C(adr_i[8]),
    .D(adr_i[15]),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__nand4_1 _0423_ (
    .A(adr_i[14]),
    .B(adr_i[13]),
    .C(adr_i[12]),
    .D(adr_i[11]),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__nor2_1 _0424_ (
    .A(_0202_),
    .B(_0203_),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__nor2_1 _0425_ (
    .A(adr_i[0]),
    .B(adr_i[1]),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__nor4_1 _0426_ (
    .A(adr_i[0]),
    .B(adr_i[1]),
    .C(adr_i[3]),
    .D(adr_i[2]),
    .Y(_0206_)
  );
  sky130_fd_sc_hd__nand2_1 _0427_ (
    .A(cyc_i),
    .B(stb_i),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__nand3_1 _0428_ (
    .A(we_i),
    .B(cyc_i),
    .C(stb_i),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__nor4_1 _0429_ (
    .A(adr_i[6]),
    .B(adr_i[7]),
    .C(adr_i[5]),
    .D(_0208_),
    .Y(_0209_)
  );
  sky130_fd_sc_hd__nand4_1 _0430_ (
    .A(adr_i[4]),
    .B(_0204_),
    .C(_0206_),
    .D(_0209_),
    .Y(_0210_)
  );
  sky130_fd_sc_hd__mux2_1 _0431_ (
    .A0(dat_i[0]),
    .A1(GCLK_REG),
    .S(_0210_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__nor4_1 _0432_ (
    .A(adr_i[6]),
    .B(adr_i[7]),
    .C(adr_i[4]),
    .D(adr_i[5]),
    .Y(_0211_)
  );
  sky130_fd_sc_hd__and3_1 _0433_ (
    .A(adr_i[3]),
    .B(_0205_),
    .C(_0211_),
    .X(_0212_)
  );
  sky130_fd_sc_hd__nand3_1 _0434_ (
    .A(adr_i[3]),
    .B(_0205_),
    .C(_0211_),
    .Y(_0213_)
  );
  sky130_fd_sc_hd__nor4_1 _0435_ (
    .A(adr_i[10]),
    .B(adr_i[9]),
    .C(adr_i[8]),
    .D(adr_i[15]),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__nor4_1 _0436_ (
    .A(adr_i[14]),
    .B(adr_i[13]),
    .C(adr_i[12]),
    .D(adr_i[11]),
    .Y(_0215_)
  );
  sky130_fd_sc_hd__nand2_1 _0437_ (
    .A(_0214_),
    .B(_0215_),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__nor3_1 _0438_ (
    .A(adr_i[2]),
    .B(_0213_),
    .C(_0216_),
    .Y(_0217_)
  );
  sky130_fd_sc_hd__or3_1 _0439_ (
    .A(adr_i[2]),
    .B(_0213_),
    .C(_0216_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0440_ (
    .A(_0208_),
    .SLEEP(_0218_),
    .X(_0219_)
  );
  sky130_fd_sc_hd__mux2_1 _0441_ (
    .A0(dat_i[7]),
    .A1(DIR_REG[7]),
    .S(_0219_),
    .X(_0193_)
  );
  sky130_fd_sc_hd__nor2_1 _0442_ (
    .A(RIS_REG[31]),
    .B(pin7_ne),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__nor2_1 _0443_ (
    .A(IC_REG[31]),
    .B(_0220_),
    .Y(_0192_)
  );
  sky130_fd_sc_hd__and3_1 _0444_ (
    .A(_0204_),
    .B(_0206_),
    .C(_0211_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__nand2_1 _0445_ (
    .A(_0206_),
    .B(_0211_),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__nor4bb_1 _0446_ (
    .A(_0202_),
    .B(_0203_),
    .C_N(_0206_),
    .D_N(_0211_),
    .Y(_0223_)
  );
  sky130_fd_sc_hd__nand3_1 _0447_ (
    .A(_0204_),
    .B(_0206_),
    .C(_0211_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__nor2_1 _0448_ (
    .A(_0208_),
    .B(_0224_),
    .Y(_0225_)
  );
  sky130_fd_sc_hd__mux2_1 _0449_ (
    .A0(IM_REG[31]),
    .A1(dat_i[31]),
    .S(_0225_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__nor4b_1 _0450_ (
    .A(adr_i[0]),
    .B(adr_i[1]),
    .C(adr_i[3]),
    .D_N(adr_i[2]),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__nand2_1 _0451_ (
    .A(_0211_),
    .B(_0226_),
    .Y(_0227_)
  );
  sky130_fd_sc_hd__nor2_1 _0452_ (
    .A(_0216_),
    .B(_0227_),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__nand4_1 _0453_ (
    .A(_0211_),
    .B(_0214_),
    .C(_0215_),
    .D(_0226_),
    .Y(_0229_)
  );
  sky130_fd_sc_hd__nor2_1 _0454_ (
    .A(_0208_),
    .B(_0229_),
    .Y(_0230_)
  );
  sky130_fd_sc_hd__mux2_1 _0455_ (
    .A0(DATAO_REG[7]),
    .A1(dat_i[7]),
    .S(_0230_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__nor2_1 _0456_ (
    .A(RIS_REG[25]),
    .B(pin1_ne),
    .Y(_0231_)
  );
  sky130_fd_sc_hd__nor2_1 _0457_ (
    .A(IC_REG[25]),
    .B(_0231_),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__nor2_1 _0458_ (
    .A(RIS_REG[26]),
    .B(pin2_ne),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__nor2_1 _0459_ (
    .A(IC_REG[26]),
    .B(_0232_),
    .Y(_0188_)
  );
  sky130_fd_sc_hd__nor2_1 _0460_ (
    .A(RIS_REG[29]),
    .B(pin5_ne),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__nor2_1 _0461_ (
    .A(IC_REG[29]),
    .B(_0233_),
    .Y(_0187_)
  );
  sky130_fd_sc_hd__nor2_1 _0462_ (
    .A(RIS_REG[30]),
    .B(pin6_ne),
    .Y(_0234_)
  );
  sky130_fd_sc_hd__nor2_1 _0463_ (
    .A(IC_REG[30]),
    .B(_0234_),
    .Y(_0186_)
  );
  sky130_fd_sc_hd__nor2_1 _0464_ (
    .A(RIS_REG[0]),
    .B(pin0_hi),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__nor2_1 _0465_ (
    .A(IC_REG[0]),
    .B(_0235_),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__nor2_1 _0466_ (
    .A(RIS_REG[1]),
    .B(pin1_hi),
    .Y(_0236_)
  );
  sky130_fd_sc_hd__nor2_1 _0467_ (
    .A(IC_REG[1]),
    .B(_0236_),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__nor2_1 _0468_ (
    .A(RIS_REG[2]),
    .B(pin2_hi),
    .Y(_0237_)
  );
  sky130_fd_sc_hd__nor2_1 _0469_ (
    .A(IC_REG[2]),
    .B(_0237_),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__nor2_1 _0470_ (
    .A(RIS_REG[3]),
    .B(pin3_hi),
    .Y(_0238_)
  );
  sky130_fd_sc_hd__nor2_1 _0471_ (
    .A(IC_REG[3]),
    .B(_0238_),
    .Y(_0182_)
  );
  sky130_fd_sc_hd__nor2_1 _0472_ (
    .A(RIS_REG[4]),
    .B(pin4_hi),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__nor2_1 _0473_ (
    .A(IC_REG[4]),
    .B(_0239_),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__nor2_1 _0474_ (
    .A(RIS_REG[5]),
    .B(pin5_hi),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__nor2_1 _0475_ (
    .A(IC_REG[5]),
    .B(_0240_),
    .Y(_0180_)
  );
  sky130_fd_sc_hd__nor2_1 _0476_ (
    .A(RIS_REG[6]),
    .B(pin6_hi),
    .Y(_0241_)
  );
  sky130_fd_sc_hd__nor2_1 _0477_ (
    .A(IC_REG[6]),
    .B(_0241_),
    .Y(_0179_)
  );
  sky130_fd_sc_hd__nor2_1 _0478_ (
    .A(RIS_REG[7]),
    .B(pin7_hi),
    .Y(_0242_)
  );
  sky130_fd_sc_hd__nor2_1 _0479_ (
    .A(IC_REG[7]),
    .B(_0242_),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__nor2_1 _0480_ (
    .A(RIS_REG[8]),
    .B(pin0_lo),
    .Y(_0243_)
  );
  sky130_fd_sc_hd__nor2_1 _0481_ (
    .A(IC_REG[8]),
    .B(_0243_),
    .Y(_0177_)
  );
  sky130_fd_sc_hd__nor2_1 _0482_ (
    .A(RIS_REG[9]),
    .B(pin1_lo),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__nor2_1 _0483_ (
    .A(IC_REG[9]),
    .B(_0244_),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__nor2_1 _0484_ (
    .A(RIS_REG[10]),
    .B(pin2_lo),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__nor2_1 _0485_ (
    .A(IC_REG[10]),
    .B(_0245_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__nor2_1 _0486_ (
    .A(RIS_REG[11]),
    .B(pin3_lo),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__nor2_1 _0487_ (
    .A(IC_REG[11]),
    .B(_0246_),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__nor2_1 _0488_ (
    .A(RIS_REG[12]),
    .B(pin4_lo),
    .Y(_0247_)
  );
  sky130_fd_sc_hd__nor2_1 _0489_ (
    .A(IC_REG[12]),
    .B(_0247_),
    .Y(_0173_)
  );
  sky130_fd_sc_hd__nor2_1 _0490_ (
    .A(RIS_REG[13]),
    .B(pin5_lo),
    .Y(_0248_)
  );
  sky130_fd_sc_hd__nor2_1 _0491_ (
    .A(IC_REG[13]),
    .B(_0248_),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__nor2_1 _0492_ (
    .A(RIS_REG[14]),
    .B(pin6_lo),
    .Y(_0249_)
  );
  sky130_fd_sc_hd__nor2_1 _0493_ (
    .A(IC_REG[14]),
    .B(_0249_),
    .Y(_0171_)
  );
  sky130_fd_sc_hd__nor2_1 _0494_ (
    .A(RIS_REG[15]),
    .B(pin7_lo),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__nor2_1 _0495_ (
    .A(IC_REG[15]),
    .B(_0250_),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__nor2_1 _0496_ (
    .A(RIS_REG[16]),
    .B(pin0_pe),
    .Y(_0251_)
  );
  sky130_fd_sc_hd__nor2_1 _0497_ (
    .A(IC_REG[16]),
    .B(_0251_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__nor2_1 _0498_ (
    .A(RIS_REG[17]),
    .B(pin1_pe),
    .Y(_0252_)
  );
  sky130_fd_sc_hd__nor2_1 _0499_ (
    .A(IC_REG[17]),
    .B(_0252_),
    .Y(_0168_)
  );
  sky130_fd_sc_hd__nor2_1 _0500_ (
    .A(RIS_REG[18]),
    .B(pin2_pe),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__nor2_1 _0501_ (
    .A(IC_REG[18]),
    .B(_0253_),
    .Y(_0167_)
  );
  sky130_fd_sc_hd__nor2_1 _0502_ (
    .A(RIS_REG[19]),
    .B(pin3_pe),
    .Y(_0254_)
  );
  sky130_fd_sc_hd__nor2_1 _0503_ (
    .A(IC_REG[19]),
    .B(_0254_),
    .Y(_0166_)
  );
  sky130_fd_sc_hd__nor2_1 _0504_ (
    .A(RIS_REG[20]),
    .B(pin4_pe),
    .Y(_0255_)
  );
  sky130_fd_sc_hd__nor2_1 _0505_ (
    .A(IC_REG[20]),
    .B(_0255_),
    .Y(_0165_)
  );
  sky130_fd_sc_hd__nor2_1 _0506_ (
    .A(RIS_REG[21]),
    .B(pin5_pe),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__nor2_1 _0507_ (
    .A(IC_REG[21]),
    .B(_0256_),
    .Y(_0164_)
  );
  sky130_fd_sc_hd__nor2_1 _0508_ (
    .A(RIS_REG[22]),
    .B(pin6_pe),
    .Y(_0257_)
  );
  sky130_fd_sc_hd__nor2_1 _0509_ (
    .A(IC_REG[22]),
    .B(_0257_),
    .Y(_0163_)
  );
  sky130_fd_sc_hd__nor2_1 _0510_ (
    .A(RIS_REG[23]),
    .B(pin7_pe),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__nor2_1 _0511_ (
    .A(IC_REG[23]),
    .B(_0258_),
    .Y(_0162_)
  );
  sky130_fd_sc_hd__nor2_1 _0512_ (
    .A(RIS_REG[24]),
    .B(pin0_ne),
    .Y(_0259_)
  );
  sky130_fd_sc_hd__nor2_1 _0513_ (
    .A(IC_REG[24]),
    .B(_0259_),
    .Y(_0161_)
  );
  sky130_fd_sc_hd__mux2_1 _0514_ (
    .A0(DATAO_REG[0]),
    .A1(dat_i[0]),
    .S(_0230_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__mux2_1 _0515_ (
    .A0(DATAO_REG[1]),
    .A1(dat_i[1]),
    .S(_0230_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__mux2_1 _0516_ (
    .A0(DATAO_REG[2]),
    .A1(dat_i[2]),
    .S(_0230_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__mux2_1 _0517_ (
    .A0(DATAO_REG[3]),
    .A1(dat_i[3]),
    .S(_0230_),
    .X(_0157_)
  );
  sky130_fd_sc_hd__mux2_1 _0518_ (
    .A0(DATAO_REG[4]),
    .A1(dat_i[4]),
    .S(_0230_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__mux2_1 _0519_ (
    .A0(DATAO_REG[5]),
    .A1(dat_i[5]),
    .S(_0230_),
    .X(_0155_)
  );
  sky130_fd_sc_hd__mux2_1 _0520_ (
    .A0(DATAO_REG[6]),
    .A1(dat_i[6]),
    .S(_0230_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__mux2_1 _0521_ (
    .A0(IM_REG[0]),
    .A1(dat_i[0]),
    .S(_0225_),
    .X(_0153_)
  );
  sky130_fd_sc_hd__mux2_1 _0522_ (
    .A0(IM_REG[1]),
    .A1(dat_i[1]),
    .S(_0225_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__mux2_1 _0523_ (
    .A0(IM_REG[2]),
    .A1(dat_i[2]),
    .S(_0225_),
    .X(_0151_)
  );
  sky130_fd_sc_hd__mux2_1 _0524_ (
    .A0(IM_REG[3]),
    .A1(dat_i[3]),
    .S(_0225_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__mux2_1 _0525_ (
    .A0(IM_REG[4]),
    .A1(dat_i[4]),
    .S(_0225_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__mux2_1 _0526_ (
    .A0(IM_REG[5]),
    .A1(dat_i[5]),
    .S(_0225_),
    .X(_0148_)
  );
  sky130_fd_sc_hd__mux2_1 _0527_ (
    .A0(IM_REG[6]),
    .A1(dat_i[6]),
    .S(_0225_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__mux2_1 _0528_ (
    .A0(IM_REG[7]),
    .A1(dat_i[7]),
    .S(_0225_),
    .X(_0146_)
  );
  sky130_fd_sc_hd__nand2_1 _0529_ (
    .A(dat_i[8]),
    .B(_0225_),
    .Y(_0260_)
  );
  sky130_fd_sc_hd__o21ai_0 _0530_ (
    .A1(_0198_),
    .A2(_0225_),
    .B1(_0260_),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__mux2_1 _0531_ (
    .A0(IM_REG[9]),
    .A1(dat_i[9]),
    .S(_0225_),
    .X(_0144_)
  );
  sky130_fd_sc_hd__mux2_1 _0532_ (
    .A0(IM_REG[10]),
    .A1(dat_i[10]),
    .S(_0225_),
    .X(_0143_)
  );
  sky130_fd_sc_hd__mux2_1 _0533_ (
    .A0(IM_REG[11]),
    .A1(dat_i[11]),
    .S(_0225_),
    .X(_0142_)
  );
  sky130_fd_sc_hd__mux2_1 _0534_ (
    .A0(IM_REG[12]),
    .A1(dat_i[12]),
    .S(_0225_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__mux2_1 _0535_ (
    .A0(IM_REG[13]),
    .A1(dat_i[13]),
    .S(_0225_),
    .X(_0140_)
  );
  sky130_fd_sc_hd__mux2_1 _0536_ (
    .A0(IM_REG[14]),
    .A1(dat_i[14]),
    .S(_0225_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__mux2_1 _0537_ (
    .A0(IM_REG[15]),
    .A1(dat_i[15]),
    .S(_0225_),
    .X(_0138_)
  );
  sky130_fd_sc_hd__mux2_1 _0538_ (
    .A0(IM_REG[16]),
    .A1(dat_i[16]),
    .S(_0225_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__mux2_1 _0539_ (
    .A0(IM_REG[17]),
    .A1(dat_i[17]),
    .S(_0225_),
    .X(_0136_)
  );
  sky130_fd_sc_hd__mux2_1 _0540_ (
    .A0(IM_REG[18]),
    .A1(dat_i[18]),
    .S(_0225_),
    .X(_0135_)
  );
  sky130_fd_sc_hd__mux2_1 _0541_ (
    .A0(IM_REG[19]),
    .A1(dat_i[19]),
    .S(_0225_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__nand2_1 _0542_ (
    .A(dat_i[20]),
    .B(_0225_),
    .Y(_0261_)
  );
  sky130_fd_sc_hd__o21ai_0 _0543_ (
    .A1(_0199_),
    .A2(_0225_),
    .B1(_0261_),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__mux2_1 _0544_ (
    .A0(IM_REG[21]),
    .A1(dat_i[21]),
    .S(_0225_),
    .X(_0132_)
  );
  sky130_fd_sc_hd__mux2_1 _0545_ (
    .A0(IM_REG[22]),
    .A1(dat_i[22]),
    .S(_0225_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__mux2_1 _0546_ (
    .A0(IM_REG[23]),
    .A1(dat_i[23]),
    .S(_0225_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__mux2_1 _0547_ (
    .A0(IM_REG[24]),
    .A1(dat_i[24]),
    .S(_0225_),
    .X(_0129_)
  );
  sky130_fd_sc_hd__mux2_1 _0548_ (
    .A0(IM_REG[25]),
    .A1(dat_i[25]),
    .S(_0225_),
    .X(_0128_)
  );
  sky130_fd_sc_hd__mux2_1 _0549_ (
    .A0(IM_REG[26]),
    .A1(dat_i[26]),
    .S(_0225_),
    .X(_0127_)
  );
  sky130_fd_sc_hd__mux2_1 _0550_ (
    .A0(IM_REG[27]),
    .A1(dat_i[27]),
    .S(_0225_),
    .X(_0126_)
  );
  sky130_fd_sc_hd__mux2_1 _0551_ (
    .A0(IM_REG[28]),
    .A1(dat_i[28]),
    .S(_0225_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__mux2_1 _0552_ (
    .A0(IM_REG[29]),
    .A1(dat_i[29]),
    .S(_0225_),
    .X(_0124_)
  );
  sky130_fd_sc_hd__mux2_1 _0553_ (
    .A0(IM_REG[30]),
    .A1(dat_i[30]),
    .S(_0225_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__mux2_1 _0554_ (
    .A0(dat_i[0]),
    .A1(DIR_REG[0]),
    .S(_0219_),
    .X(_0122_)
  );
  sky130_fd_sc_hd__mux2_1 _0555_ (
    .A0(dat_i[1]),
    .A1(DIR_REG[1]),
    .S(_0219_),
    .X(_0121_)
  );
  sky130_fd_sc_hd__mux2_1 _0556_ (
    .A0(dat_i[2]),
    .A1(DIR_REG[2]),
    .S(_0219_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__mux2_1 _0557_ (
    .A0(dat_i[3]),
    .A1(DIR_REG[3]),
    .S(_0219_),
    .X(_0119_)
  );
  sky130_fd_sc_hd__mux2_1 _0558_ (
    .A0(dat_i[4]),
    .A1(DIR_REG[4]),
    .S(_0219_),
    .X(_0118_)
  );
  sky130_fd_sc_hd__mux2_1 _0559_ (
    .A0(dat_i[5]),
    .A1(DIR_REG[5]),
    .S(_0219_),
    .X(_0117_)
  );
  sky130_fd_sc_hd__mux2_1 _0560_ (
    .A0(dat_i[6]),
    .A1(DIR_REG[6]),
    .S(_0219_),
    .X(_0116_)
  );
  sky130_fd_sc_hd__nor2_1 _0561_ (
    .A(_0216_),
    .B(_0222_),
    .Y(_0262_)
  );
  sky130_fd_sc_hd__nand4_1 _0562_ (
    .A(_0206_),
    .B(_0211_),
    .C(_0214_),
    .D(_0215_),
    .Y(_0263_)
  );
  sky130_fd_sc_hd__nor3_1 _0563_ (
    .A(_0217_),
    .B(_0228_),
    .C(_0262_),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__o21ai_0 _0564_ (
    .A1(IM_REG[26]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__nor4_1 _0565_ (
    .A(adr_i[2]),
    .B(_0202_),
    .C(_0203_),
    .D(_0213_),
    .Y(_0266_)
  );
  sky130_fd_sc_hd__nand3b_1 _0566_ (
    .A_N(adr_i[2]),
    .B(_0204_),
    .C(_0212_),
    .Y(_0267_)
  );
  sky130_fd_sc_hd__and3_1 _0567_ (
    .A(adr_i[2]),
    .B(_0204_),
    .C(_0212_),
    .X(_0268_)
  );
  sky130_fd_sc_hd__nand3_1 _0568_ (
    .A(adr_i[2]),
    .B(_0204_),
    .C(_0212_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__nor4bb_1 _0569_ (
    .A(_0202_),
    .B(_0203_),
    .C_N(_0211_),
    .D_N(_0226_),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__nand3_1 _0570_ (
    .A(_0204_),
    .B(_0211_),
    .C(_0226_),
    .Y(_0271_)
  );
  sky130_fd_sc_hd__nand2_1 _0571_ (
    .A(RIS_REG[26]),
    .B(IM_REG[26]),
    .Y(_0272_)
  );
  sky130_fd_sc_hd__nand2_1 _0572_ (
    .A(_0270_),
    .B(_0272_),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__o221ai_1 _0573_ (
    .A1(RIS_REG[26]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[26]),
    .C1(_0273_),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__nand3_1 _0574_ (
    .A(adr_i[2]),
    .B(_0204_),
    .C(_0212_),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__nor2_1 _0575_ (
    .A(_0265_),
    .B(_0274_),
    .Y(dat_o[26])
  );
  sky130_fd_sc_hd__o21ai_0 _0576_ (
    .A1(IM_REG[25]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__o22ai_1 _0577_ (
    .A1(RIS_REG[25]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[25]),
    .Y(_0277_)
  );
  sky130_fd_sc_hd__nand2_1 _0578_ (
    .A(RIS_REG[25]),
    .B(IM_REG[25]),
    .Y(_0278_)
  );
  sky130_fd_sc_hd__a211oi_1 _0579_ (
    .A1(_0270_),
    .A2(_0278_),
    .B1(_0277_),
    .C1(_0276_),
    .Y(dat_o[25])
  );
  sky130_fd_sc_hd__nand2_1 _0580_ (
    .A(IC_REG[24]),
    .B(_0268_),
    .Y(_0279_)
  );
  sky130_fd_sc_hd__a21oi_1 _0581_ (
    .A1(RIS_REG[24]),
    .A2(_0266_),
    .B1(IM_REG[24]),
    .Y(_0280_)
  );
  sky130_fd_sc_hd__nor2_1 _0582_ (
    .A(_0266_),
    .B(_0270_),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__nand2_1 _0583_ (
    .A(_0267_),
    .B(_0271_),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__a21oi_1 _0584_ (
    .A1(RIS_REG[24]),
    .A2(_0282_),
    .B1(_0221_),
    .Y(_0283_)
  );
  sky130_fd_sc_hd__o21ai_0 _0585_ (
    .A1(_0280_),
    .A2(_0283_),
    .B1(_0279_),
    .Y(dat_o[24])
  );
  sky130_fd_sc_hd__o21ai_0 _0586_ (
    .A1(IM_REG[23]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0284_)
  );
  sky130_fd_sc_hd__o22ai_1 _0587_ (
    .A1(RIS_REG[23]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[23]),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__nand2_1 _0588_ (
    .A(RIS_REG[23]),
    .B(IM_REG[23]),
    .Y(_0286_)
  );
  sky130_fd_sc_hd__a211oi_1 _0589_ (
    .A1(_0270_),
    .A2(_0286_),
    .B1(_0285_),
    .C1(_0284_),
    .Y(dat_o[23])
  );
  sky130_fd_sc_hd__nand2_1 _0590_ (
    .A(IC_REG[22]),
    .B(_0268_),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__a21oi_1 _0591_ (
    .A1(RIS_REG[22]),
    .A2(_0266_),
    .B1(IM_REG[22]),
    .Y(_0288_)
  );
  sky130_fd_sc_hd__a21oi_1 _0592_ (
    .A1(RIS_REG[22]),
    .A2(_0282_),
    .B1(_0221_),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__o21ai_0 _0593_ (
    .A1(_0288_),
    .A2(_0289_),
    .B1(_0287_),
    .Y(dat_o[22])
  );
  sky130_fd_sc_hd__o21ai_0 _0594_ (
    .A1(IM_REG[21]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0290_)
  );
  sky130_fd_sc_hd__o22ai_1 _0595_ (
    .A1(RIS_REG[21]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[21]),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__nand2_1 _0596_ (
    .A(RIS_REG[21]),
    .B(IM_REG[21]),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__a211oi_1 _0597_ (
    .A1(_0270_),
    .A2(_0292_),
    .B1(_0291_),
    .C1(_0290_),
    .Y(dat_o[21])
  );
  sky130_fd_sc_hd__a21oi_1 _0598_ (
    .A1(RIS_REG[20]),
    .A2(_0270_),
    .B1(_0221_),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__a22oi_1 _0599_ (
    .A1(RIS_REG[20]),
    .A2(_0266_),
    .B1(_0268_),
    .B2(IC_REG[20]),
    .Y(_0294_)
  );
  sky130_fd_sc_hd__o21ai_0 _0600_ (
    .A1(_0199_),
    .A2(_0293_),
    .B1(_0294_),
    .Y(dat_o[20])
  );
  sky130_fd_sc_hd__o21ai_0 _0601_ (
    .A1(IM_REG[19]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__o22ai_1 _0602_ (
    .A1(RIS_REG[19]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[19]),
    .Y(_0296_)
  );
  sky130_fd_sc_hd__nand2_1 _0603_ (
    .A(RIS_REG[19]),
    .B(IM_REG[19]),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__a211oi_1 _0604_ (
    .A1(_0270_),
    .A2(_0297_),
    .B1(_0296_),
    .C1(_0295_),
    .Y(dat_o[19])
  );
  sky130_fd_sc_hd__o21ai_0 _0605_ (
    .A1(IM_REG[18]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__o22ai_1 _0606_ (
    .A1(RIS_REG[18]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[18]),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__nand2_1 _0607_ (
    .A(RIS_REG[18]),
    .B(IM_REG[18]),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__a211oi_1 _0608_ (
    .A1(_0270_),
    .A2(_0300_),
    .B1(_0299_),
    .C1(_0298_),
    .Y(dat_o[18])
  );
  sky130_fd_sc_hd__nand2_1 _0609_ (
    .A(IC_REG[17]),
    .B(_0268_),
    .Y(_0301_)
  );
  sky130_fd_sc_hd__a21oi_1 _0610_ (
    .A1(RIS_REG[17]),
    .A2(_0266_),
    .B1(IM_REG[17]),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__a21oi_1 _0611_ (
    .A1(RIS_REG[17]),
    .A2(_0282_),
    .B1(_0221_),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__o21ai_0 _0612_ (
    .A1(_0302_),
    .A2(_0303_),
    .B1(_0301_),
    .Y(dat_o[17])
  );
  sky130_fd_sc_hd__o21ai_0 _0613_ (
    .A1(IM_REG[16]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__o22ai_1 _0614_ (
    .A1(RIS_REG[16]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[16]),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__nand2_1 _0615_ (
    .A(RIS_REG[16]),
    .B(IM_REG[16]),
    .Y(_0306_)
  );
  sky130_fd_sc_hd__a211oi_1 _0616_ (
    .A1(_0270_),
    .A2(_0306_),
    .B1(_0305_),
    .C1(_0304_),
    .Y(dat_o[16])
  );
  sky130_fd_sc_hd__o21ai_0 _0617_ (
    .A1(IM_REG[15]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__o22ai_1 _0618_ (
    .A1(RIS_REG[15]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[15]),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__nand2_1 _0619_ (
    .A(RIS_REG[15]),
    .B(IM_REG[15]),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__a211oi_1 _0620_ (
    .A1(_0270_),
    .A2(_0309_),
    .B1(_0308_),
    .C1(_0307_),
    .Y(dat_o[15])
  );
  sky130_fd_sc_hd__nand2_1 _0621_ (
    .A(IC_REG[14]),
    .B(_0268_),
    .Y(_0310_)
  );
  sky130_fd_sc_hd__a21oi_1 _0622_ (
    .A1(RIS_REG[14]),
    .A2(_0266_),
    .B1(IM_REG[14]),
    .Y(_0311_)
  );
  sky130_fd_sc_hd__a21oi_1 _0623_ (
    .A1(RIS_REG[14]),
    .A2(_0282_),
    .B1(_0221_),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__o21ai_0 _0624_ (
    .A1(_0311_),
    .A2(_0312_),
    .B1(_0310_),
    .Y(dat_o[14])
  );
  sky130_fd_sc_hd__o21ai_0 _0625_ (
    .A1(IM_REG[13]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__o22ai_1 _0626_ (
    .A1(RIS_REG[13]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[13]),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__nand2_1 _0627_ (
    .A(RIS_REG[13]),
    .B(IM_REG[13]),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__a211oi_1 _0628_ (
    .A1(_0270_),
    .A2(_0315_),
    .B1(_0314_),
    .C1(_0313_),
    .Y(dat_o[13])
  );
  sky130_fd_sc_hd__o21ai_0 _0629_ (
    .A1(IM_REG[12]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0316_)
  );
  sky130_fd_sc_hd__o22ai_1 _0630_ (
    .A1(RIS_REG[12]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[12]),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__nand2_1 _0631_ (
    .A(RIS_REG[12]),
    .B(IM_REG[12]),
    .Y(_0318_)
  );
  sky130_fd_sc_hd__a211oi_1 _0632_ (
    .A1(_0270_),
    .A2(_0318_),
    .B1(_0317_),
    .C1(_0316_),
    .Y(dat_o[12])
  );
  sky130_fd_sc_hd__o21ai_0 _0633_ (
    .A1(IM_REG[11]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0319_)
  );
  sky130_fd_sc_hd__o22ai_1 _0634_ (
    .A1(RIS_REG[11]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[11]),
    .Y(_0320_)
  );
  sky130_fd_sc_hd__a21oi_1 _0635_ (
    .A1(RIS_REG[11]),
    .A2(IM_REG[11]),
    .B1(_0271_),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__nor3_1 _0636_ (
    .A(_0319_),
    .B(_0320_),
    .C(_0321_),
    .Y(dat_o[11])
  );
  sky130_fd_sc_hd__o21ai_0 _0637_ (
    .A1(IM_REG[10]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0322_)
  );
  sky130_fd_sc_hd__o22ai_1 _0638_ (
    .A1(RIS_REG[10]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[10]),
    .Y(_0323_)
  );
  sky130_fd_sc_hd__nand2_1 _0639_ (
    .A(RIS_REG[10]),
    .B(IM_REG[10]),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__a211oi_1 _0640_ (
    .A1(_0270_),
    .A2(_0324_),
    .B1(_0323_),
    .C1(_0322_),
    .Y(dat_o[10])
  );
  sky130_fd_sc_hd__o21ai_0 _0641_ (
    .A1(IM_REG[9]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0325_)
  );
  sky130_fd_sc_hd__o22ai_1 _0642_ (
    .A1(RIS_REG[9]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[9]),
    .Y(_0326_)
  );
  sky130_fd_sc_hd__a21oi_1 _0643_ (
    .A1(RIS_REG[9]),
    .A2(IM_REG[9]),
    .B1(_0271_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__nor3_1 _0644_ (
    .A(_0325_),
    .B(_0326_),
    .C(_0327_),
    .Y(dat_o[9])
  );
  sky130_fd_sc_hd__a21oi_1 _0645_ (
    .A1(RIS_REG[8]),
    .A2(_0270_),
    .B1(_0221_),
    .Y(_0328_)
  );
  sky130_fd_sc_hd__a22oi_1 _0646_ (
    .A1(RIS_REG[8]),
    .A2(_0266_),
    .B1(_0268_),
    .B2(IC_REG[8]),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__o21ai_0 _0647_ (
    .A1(_0198_),
    .A2(_0328_),
    .B1(_0329_),
    .Y(dat_o[8])
  );
  sky130_fd_sc_hd__nand2_1 _0648_ (
    .A(bus_in[7]),
    .B(_0262_),
    .Y(_0330_)
  );
  sky130_fd_sc_hd__o21ai_0 _0649_ (
    .A1(DATAO_REG[7]),
    .A2(_0229_),
    .B1(_0263_),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__nor2_1 _0650_ (
    .A(_0221_),
    .B(_0270_),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__nand2_1 _0651_ (
    .A(IM_REG[7]),
    .B(_0223_),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__nand2_1 _0652_ (
    .A(RIS_REG[7]),
    .B(IM_REG[7]),
    .Y(_0334_)
  );
  sky130_fd_sc_hd__nor2_1 _0653_ (
    .A(_0223_),
    .B(_0270_),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__o221ai_1 _0654_ (
    .A1(RIS_REG[7]),
    .A2(_0267_),
    .B1(_0275_),
    .B2(IC_REG[7]),
    .C1(_0335_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0655_ (
    .A1(_0271_),
    .A2(_0334_),
    .B1(_0336_),
    .C1(_0333_),
    .D1(_0218_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__o21ai_0 _0656_ (
    .A1(DIR_REG[7]),
    .A2(_0218_),
    .B1(_0337_),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__o21ai_0 _0657_ (
    .A1(_0331_),
    .A2(_0338_),
    .B1(_0330_),
    .Y(dat_o[7])
  );
  sky130_fd_sc_hd__nor2_1 _0658_ (
    .A(bus_in[6]),
    .B(_0263_),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__a21oi_1 _0659_ (
    .A1(DATAO_REG[6]),
    .A2(_0228_),
    .B1(_0262_),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__and2_0 _0660_ (
    .A(DIR_REG[6]),
    .B(_0217_),
    .X(_0341_)
  );
  sky130_fd_sc_hd__o21ai_0 _0661_ (
    .A1(_0266_),
    .A2(_0270_),
    .B1(RIS_REG[6]),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__o21ai_0 _0662_ (
    .A1(IM_REG[6]),
    .A2(_0335_),
    .B1(_0218_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__o211ai_1 _0663_ (
    .A1(IC_REG[6]),
    .A2(_0275_),
    .B1(_0271_),
    .C1(_0267_),
    .Y(_0344_)
  );
  sky130_fd_sc_hd__a21oi_1 _0664_ (
    .A1(_0342_),
    .A2(_0344_),
    .B1(_0343_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__o21ai_0 _0665_ (
    .A1(_0341_),
    .A2(_0345_),
    .B1(_0229_),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__a21oi_1 _0666_ (
    .A1(_0340_),
    .A2(_0346_),
    .B1(_0339_),
    .Y(dat_o[6])
  );
  sky130_fd_sc_hd__nor2_1 _0667_ (
    .A(bus_in[5]),
    .B(_0263_),
    .Y(_0347_)
  );
  sky130_fd_sc_hd__a21oi_1 _0668_ (
    .A1(DATAO_REG[5]),
    .A2(_0228_),
    .B1(_0262_),
    .Y(_0348_)
  );
  sky130_fd_sc_hd__nor2_1 _0669_ (
    .A(IM_REG[5]),
    .B(_0332_),
    .Y(_0349_)
  );
  sky130_fd_sc_hd__o22ai_1 _0670_ (
    .A1(IC_REG[5]),
    .A2(_0269_),
    .B1(_0281_),
    .B2(RIS_REG[5]),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__o21ai_0 _0671_ (
    .A1(DIR_REG[5]),
    .A2(_0218_),
    .B1(_0229_),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__or3_1 _0672_ (
    .A(_0349_),
    .B(_0350_),
    .C(_0351_),
    .X(_0352_)
  );
  sky130_fd_sc_hd__a21oi_1 _0673_ (
    .A1(_0348_),
    .A2(_0352_),
    .B1(_0347_),
    .Y(dat_o[5])
  );
  sky130_fd_sc_hd__a21oi_1 _0674_ (
    .A1(IM_REG[4]),
    .A2(_0270_),
    .B1(_0266_),
    .Y(_0353_)
  );
  sky130_fd_sc_hd__nand2_1 _0675_ (
    .A(DIR_REG[4]),
    .B(_0217_),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__a22oi_1 _0676_ (
    .A1(IM_REG[4]),
    .A2(_0221_),
    .B1(_0268_),
    .B2(IC_REG[4]),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__a22oi_1 _0677_ (
    .A1(DATAO_REG[4]),
    .A2(_0228_),
    .B1(_0262_),
    .B2(bus_in[4]),
    .Y(_0356_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0678_ (
    .A1(_0197_),
    .A2(_0353_),
    .B1(_0354_),
    .C1(_0355_),
    .D1(_0356_),
    .Y(dat_o[4])
  );
  sky130_fd_sc_hd__nor2_1 _0679_ (
    .A(bus_in[3]),
    .B(_0263_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__a21oi_1 _0680_ (
    .A1(DATAO_REG[3]),
    .A2(_0228_),
    .B1(_0262_),
    .Y(_0358_)
  );
  sky130_fd_sc_hd__nor2_1 _0681_ (
    .A(IM_REG[3]),
    .B(_0332_),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__o22ai_1 _0682_ (
    .A1(IC_REG[3]),
    .A2(_0269_),
    .B1(_0281_),
    .B2(RIS_REG[3]),
    .Y(_0360_)
  );
  sky130_fd_sc_hd__o21ai_0 _0683_ (
    .A1(DIR_REG[3]),
    .A2(_0218_),
    .B1(_0229_),
    .Y(_0361_)
  );
  sky130_fd_sc_hd__or3_1 _0684_ (
    .A(_0359_),
    .B(_0360_),
    .C(_0361_),
    .X(_0362_)
  );
  sky130_fd_sc_hd__a21oi_1 _0685_ (
    .A1(_0358_),
    .A2(_0362_),
    .B1(_0357_),
    .Y(dat_o[3])
  );
  sky130_fd_sc_hd__nor2_1 _0686_ (
    .A(bus_in[2]),
    .B(_0263_),
    .Y(_0363_)
  );
  sky130_fd_sc_hd__a21oi_1 _0687_ (
    .A1(DATAO_REG[2]),
    .A2(_0228_),
    .B1(_0262_),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__nor2_1 _0688_ (
    .A(IM_REG[2]),
    .B(_0332_),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__o22ai_1 _0689_ (
    .A1(IC_REG[2]),
    .A2(_0269_),
    .B1(_0281_),
    .B2(RIS_REG[2]),
    .Y(_0366_)
  );
  sky130_fd_sc_hd__o21ai_0 _0690_ (
    .A1(DIR_REG[2]),
    .A2(_0218_),
    .B1(_0229_),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__or3_1 _0691_ (
    .A(_0365_),
    .B(_0366_),
    .C(_0367_),
    .X(_0368_)
  );
  sky130_fd_sc_hd__a21oi_1 _0692_ (
    .A1(_0364_),
    .A2(_0368_),
    .B1(_0363_),
    .Y(dat_o[2])
  );
  sky130_fd_sc_hd__nand2_1 _0693_ (
    .A(bus_in[1]),
    .B(_0262_),
    .Y(_0369_)
  );
  sky130_fd_sc_hd__o21ai_0 _0694_ (
    .A1(DATAO_REG[1]),
    .A2(_0229_),
    .B1(_0263_),
    .Y(_0370_)
  );
  sky130_fd_sc_hd__o221ai_1 _0695_ (
    .A1(RIS_REG[1]),
    .A2(_0267_),
    .B1(_0275_),
    .B2(IC_REG[1]),
    .C1(_0335_),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__nand2_1 _0696_ (
    .A(IM_REG[1]),
    .B(_0223_),
    .Y(_0372_)
  );
  sky130_fd_sc_hd__nand3_1 _0697_ (
    .A(RIS_REG[1]),
    .B(IM_REG[1]),
    .C(_0270_),
    .Y(_0373_)
  );
  sky130_fd_sc_hd__nand4_1 _0698_ (
    .A(_0218_),
    .B(_0371_),
    .C(_0372_),
    .D(_0373_),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__o21ai_0 _0699_ (
    .A1(DIR_REG[1]),
    .A2(_0218_),
    .B1(_0374_),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__o21ai_0 _0700_ (
    .A1(_0370_),
    .A2(_0375_),
    .B1(_0369_),
    .Y(dat_o[1])
  );
  sky130_fd_sc_hd__nand2_1 _0701_ (
    .A(bus_in[0]),
    .B(_0262_),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__o21ai_0 _0702_ (
    .A1(DATAO_REG[0]),
    .A2(_0229_),
    .B1(_0263_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__o221ai_1 _0703_ (
    .A1(RIS_REG[0]),
    .A2(_0267_),
    .B1(_0275_),
    .B2(IC_REG[0]),
    .C1(_0335_),
    .Y(_0378_)
  );
  sky130_fd_sc_hd__nand2_1 _0704_ (
    .A(IM_REG[0]),
    .B(_0223_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__nand2_1 _0705_ (
    .A(RIS_REG[0]),
    .B(IM_REG[0]),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0706_ (
    .A1(_0271_),
    .A2(_0380_),
    .B1(_0378_),
    .C1(_0218_),
    .D1(_0379_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__o21ai_0 _0707_ (
    .A1(DIR_REG[0]),
    .A2(_0218_),
    .B1(_0381_),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__o21ai_0 _0708_ (
    .A1(_0377_),
    .A2(_0382_),
    .B1(_0376_),
    .Y(dat_o[0])
  );
  sky130_fd_sc_hd__nor2_1 _0709_ (
    .A(_0208_),
    .B(_0269_),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__and2_0 _0710_ (
    .A(dat_i[30]),
    .B(_0383_),
    .X(_0000_[30])
  );
  sky130_fd_sc_hd__and2_0 _0711_ (
    .A(dat_i[29]),
    .B(_0383_),
    .X(_0000_[29])
  );
  sky130_fd_sc_hd__and2_0 _0712_ (
    .A(dat_i[28]),
    .B(_0383_),
    .X(_0000_[28])
  );
  sky130_fd_sc_hd__and2_0 _0713_ (
    .A(dat_i[27]),
    .B(_0383_),
    .X(_0000_[27])
  );
  sky130_fd_sc_hd__and2_0 _0714_ (
    .A(dat_i[26]),
    .B(_0383_),
    .X(_0000_[26])
  );
  sky130_fd_sc_hd__and2_0 _0715_ (
    .A(dat_i[25]),
    .B(_0383_),
    .X(_0000_[25])
  );
  sky130_fd_sc_hd__and2_0 _0716_ (
    .A(dat_i[24]),
    .B(_0383_),
    .X(_0000_[24])
  );
  sky130_fd_sc_hd__and2_0 _0717_ (
    .A(dat_i[23]),
    .B(_0383_),
    .X(_0000_[23])
  );
  sky130_fd_sc_hd__and2_0 _0718_ (
    .A(dat_i[22]),
    .B(_0383_),
    .X(_0000_[22])
  );
  sky130_fd_sc_hd__and2_0 _0719_ (
    .A(dat_i[21]),
    .B(_0383_),
    .X(_0000_[21])
  );
  sky130_fd_sc_hd__and2_0 _0720_ (
    .A(dat_i[20]),
    .B(_0383_),
    .X(_0000_[20])
  );
  sky130_fd_sc_hd__and2_0 _0721_ (
    .A(dat_i[19]),
    .B(_0383_),
    .X(_0000_[19])
  );
  sky130_fd_sc_hd__and2_0 _0722_ (
    .A(dat_i[18]),
    .B(_0383_),
    .X(_0000_[18])
  );
  sky130_fd_sc_hd__and2_0 _0723_ (
    .A(dat_i[16]),
    .B(_0383_),
    .X(_0000_[16])
  );
  sky130_fd_sc_hd__and2_0 _0724_ (
    .A(dat_i[15]),
    .B(_0383_),
    .X(_0000_[15])
  );
  sky130_fd_sc_hd__and2_0 _0725_ (
    .A(dat_i[14]),
    .B(_0383_),
    .X(_0000_[14])
  );
  sky130_fd_sc_hd__and2_0 _0726_ (
    .A(dat_i[13]),
    .B(_0383_),
    .X(_0000_[13])
  );
  sky130_fd_sc_hd__and2_0 _0727_ (
    .A(dat_i[12]),
    .B(_0383_),
    .X(_0000_[12])
  );
  sky130_fd_sc_hd__and2_0 _0728_ (
    .A(dat_i[11]),
    .B(_0383_),
    .X(_0000_[11])
  );
  sky130_fd_sc_hd__and2_0 _0729_ (
    .A(dat_i[10]),
    .B(_0383_),
    .X(_0000_[10])
  );
  sky130_fd_sc_hd__and2_0 _0730_ (
    .A(dat_i[9]),
    .B(_0383_),
    .X(_0000_[9])
  );
  sky130_fd_sc_hd__and2_0 _0731_ (
    .A(dat_i[8]),
    .B(_0383_),
    .X(_0000_[8])
  );
  sky130_fd_sc_hd__and2_0 _0732_ (
    .A(dat_i[7]),
    .B(_0383_),
    .X(_0000_[7])
  );
  sky130_fd_sc_hd__and2_0 _0733_ (
    .A(dat_i[6]),
    .B(_0383_),
    .X(_0000_[6])
  );
  sky130_fd_sc_hd__and2_0 _0734_ (
    .A(dat_i[5]),
    .B(_0383_),
    .X(_0000_[5])
  );
  sky130_fd_sc_hd__and2_0 _0735_ (
    .A(dat_i[4]),
    .B(_0383_),
    .X(_0000_[4])
  );
  sky130_fd_sc_hd__and2_0 _0736_ (
    .A(dat_i[3]),
    .B(_0383_),
    .X(_0000_[3])
  );
  sky130_fd_sc_hd__and2_0 _0737_ (
    .A(dat_i[17]),
    .B(_0383_),
    .X(_0000_[17])
  );
  sky130_fd_sc_hd__and2_0 _0738_ (
    .A(dat_i[2]),
    .B(_0383_),
    .X(_0000_[2])
  );
  sky130_fd_sc_hd__and2_0 _0739_ (
    .A(dat_i[1]),
    .B(_0383_),
    .X(_0000_[1])
  );
  sky130_fd_sc_hd__and2_0 _0740_ (
    .A(dat_i[0]),
    .B(_0383_),
    .X(_0000_[0])
  );
  sky130_fd_sc_hd__o21ai_0 _0741_ (
    .A1(IM_REG[30]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__o22ai_1 _0742_ (
    .A1(RIS_REG[30]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[30]),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__nand2_1 _0743_ (
    .A(RIS_REG[30]),
    .B(IM_REG[30]),
    .Y(_0386_)
  );
  sky130_fd_sc_hd__a211oi_1 _0744_ (
    .A1(_0270_),
    .A2(_0386_),
    .B1(_0385_),
    .C1(_0384_),
    .Y(dat_o[30])
  );
  sky130_fd_sc_hd__a21oi_1 _0745_ (
    .A1(IM_REG[29]),
    .A2(_0223_),
    .B1(RIS_REG[29]),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__o21ai_0 _0746_ (
    .A1(_0221_),
    .A2(_0270_),
    .B1(IM_REG[29]),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__a21oi_1 _0747_ (
    .A1(_0267_),
    .A2(_0388_),
    .B1(_0387_),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__a21o_1 _0748_ (
    .A1(IC_REG[29]),
    .A2(_0268_),
    .B1(_0389_),
    .X(dat_o[29])
  );
  sky130_fd_sc_hd__o21ai_0 _0749_ (
    .A1(IM_REG[28]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0390_)
  );
  sky130_fd_sc_hd__o22ai_1 _0750_ (
    .A1(RIS_REG[28]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[28]),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__a21oi_1 _0751_ (
    .A1(RIS_REG[28]),
    .A2(IM_REG[28]),
    .B1(_0271_),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__nor3_1 _0752_ (
    .A(_0390_),
    .B(_0391_),
    .C(_0392_),
    .Y(dat_o[28])
  );
  sky130_fd_sc_hd__o21ai_0 _0753_ (
    .A1(IM_REG[27]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0393_)
  );
  sky130_fd_sc_hd__o22ai_1 _0754_ (
    .A1(RIS_REG[27]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[27]),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__a21oi_1 _0755_ (
    .A1(RIS_REG[27]),
    .A2(IM_REG[27]),
    .B1(_0271_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__nor3_1 _0756_ (
    .A(_0393_),
    .B(_0394_),
    .C(_0395_),
    .Y(dat_o[27])
  );
  sky130_fd_sc_hd__nor2_1 _0757_ (
    .A(ack_o),
    .B(_0207_),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__o21ai_0 _0758_ (
    .A1(IM_REG[31]),
    .A2(_0224_),
    .B1(_0264_),
    .Y(_0396_)
  );
  sky130_fd_sc_hd__o22ai_1 _0759_ (
    .A1(RIS_REG[31]),
    .A2(_0267_),
    .B1(_0269_),
    .B2(IC_REG[31]),
    .Y(_0397_)
  );
  sky130_fd_sc_hd__a21oi_1 _0760_ (
    .A1(RIS_REG[31]),
    .A2(IM_REG[31]),
    .B1(_0271_),
    .Y(_0398_)
  );
  sky130_fd_sc_hd__nor3_1 _0761_ (
    .A(_0396_),
    .B(_0397_),
    .C(_0398_),
    .Y(dat_o[31])
  );
  sky130_fd_sc_hd__nand2_1 _0762_ (
    .A(RIS_REG[2]),
    .B(IM_REG[2]),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__nand2_1 _0763_ (
    .A(RIS_REG[22]),
    .B(IM_REG[22]),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__nand2_1 _0764_ (
    .A(RIS_REG[24]),
    .B(IM_REG[24]),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__a22oi_1 _0765_ (
    .A1(RIS_REG[14]),
    .A2(IM_REG[14]),
    .B1(IM_REG[17]),
    .B2(RIS_REG[17]),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__a222oi_1 _0766_ (
    .A1(RIS_REG[1]),
    .A2(IM_REG[1]),
    .B1(IM_REG[4]),
    .B2(RIS_REG[4]),
    .C1(IM_REG[29]),
    .C2(RIS_REG[29]),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__nand4_1 _0767_ (
    .A(_0286_),
    .B(_0306_),
    .C(_0402_),
    .D(_0403_),
    .Y(_0404_)
  );
  sky130_fd_sc_hd__a221oi_1 _0768_ (
    .A1(RIS_REG[11]),
    .A2(IM_REG[11]),
    .B1(IM_REG[20]),
    .B2(RIS_REG[20]),
    .C1(_0404_),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__a222oi_1 _0769_ (
    .A1(RIS_REG[6]),
    .A2(IM_REG[6]),
    .B1(IM_REG[8]),
    .B2(RIS_REG[8]),
    .C1(IM_REG[9]),
    .C2(RIS_REG[9]),
    .Y(_0406_)
  );
  sky130_fd_sc_hd__a222oi_1 _0770_ (
    .A1(RIS_REG[3]),
    .A2(IM_REG[3]),
    .B1(IM_REG[27]),
    .B2(RIS_REG[27]),
    .C1(RIS_REG[28]),
    .C2(IM_REG[28]),
    .Y(_0407_)
  );
  sky130_fd_sc_hd__a22oi_1 _0771_ (
    .A1(RIS_REG[31]),
    .A2(IM_REG[31]),
    .B1(RIS_REG[5]),
    .B2(IM_REG[5]),
    .Y(_0408_)
  );
  sky130_fd_sc_hd__nand4_1 _0772_ (
    .A(_0324_),
    .B(_0406_),
    .C(_0407_),
    .D(_0408_),
    .Y(_0409_)
  );
  sky130_fd_sc_hd__nand4_1 _0773_ (
    .A(_0300_),
    .B(_0386_),
    .C(_0399_),
    .D(_0401_),
    .Y(_0410_)
  );
  sky130_fd_sc_hd__nand4_1 _0774_ (
    .A(_0309_),
    .B(_0315_),
    .C(_0318_),
    .D(_0400_),
    .Y(_0411_)
  );
  sky130_fd_sc_hd__nand4_1 _0775_ (
    .A(_0272_),
    .B(_0278_),
    .C(_0292_),
    .D(_0380_),
    .Y(_0412_)
  );
  sky130_fd_sc_hd__nor4_1 _0776_ (
    .A(_0409_),
    .B(_0410_),
    .C(_0411_),
    .D(_0412_),
    .Y(_0413_)
  );
  sky130_fd_sc_hd__nand4_1 _0777_ (
    .A(_0297_),
    .B(_0334_),
    .C(_0405_),
    .D(_0413_),
    .Y(IRQ)
  );
  sky130_fd_sc_hd__and2_0 _0778_ (
    .A(dat_i[31]),
    .B(_0383_),
    .X(_0000_[31])
  );
  sky130_fd_sc_hd__clkinv_1 _0779_ (
    .A(rst_i),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__clkinv_1 _0780_ (
    .A(rst_i),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__clkinv_1 _0781_ (
    .A(rst_i),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__clkinv_1 _0782_ (
    .A(rst_i),
    .Y(_0006_)
  );
  sky130_fd_sc_hd__clkinv_1 _0783_ (
    .A(rst_i),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__clkinv_1 _0784_ (
    .A(rst_i),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__clkinv_1 _0785_ (
    .A(rst_i),
    .Y(_0009_)
  );
  sky130_fd_sc_hd__clkinv_1 _0786_ (
    .A(rst_i),
    .Y(_0010_)
  );
  sky130_fd_sc_hd__clkinv_1 _0787_ (
    .A(rst_i),
    .Y(_0011_)
  );
  sky130_fd_sc_hd__clkinv_1 _0788_ (
    .A(rst_i),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__clkinv_1 _0789_ (
    .A(rst_i),
    .Y(_0013_)
  );
  sky130_fd_sc_hd__clkinv_1 _0790_ (
    .A(rst_i),
    .Y(_0014_)
  );
  sky130_fd_sc_hd__clkinv_1 _0791_ (
    .A(rst_i),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__clkinv_1 _0792_ (
    .A(rst_i),
    .Y(_0016_)
  );
  sky130_fd_sc_hd__clkinv_1 _0793_ (
    .A(rst_i),
    .Y(_0017_)
  );
  sky130_fd_sc_hd__clkinv_1 _0794_ (
    .A(rst_i),
    .Y(_0018_)
  );
  sky130_fd_sc_hd__clkinv_1 _0795_ (
    .A(rst_i),
    .Y(_0019_)
  );
  sky130_fd_sc_hd__clkinv_1 _0796_ (
    .A(rst_i),
    .Y(_0020_)
  );
  sky130_fd_sc_hd__clkinv_1 _0797_ (
    .A(rst_i),
    .Y(_0021_)
  );
  sky130_fd_sc_hd__clkinv_1 _0798_ (
    .A(rst_i),
    .Y(_0022_)
  );
  sky130_fd_sc_hd__clkinv_1 _0799_ (
    .A(rst_i),
    .Y(_0023_)
  );
  sky130_fd_sc_hd__clkinv_1 _0800_ (
    .A(rst_i),
    .Y(_0024_)
  );
  sky130_fd_sc_hd__clkinv_1 _0801_ (
    .A(rst_i),
    .Y(_0025_)
  );
  sky130_fd_sc_hd__clkinv_1 _0802_ (
    .A(rst_i),
    .Y(_0026_)
  );
  sky130_fd_sc_hd__clkinv_1 _0803_ (
    .A(rst_i),
    .Y(_0027_)
  );
  sky130_fd_sc_hd__clkinv_1 _0804_ (
    .A(rst_i),
    .Y(_0028_)
  );
  sky130_fd_sc_hd__clkinv_1 _0805_ (
    .A(rst_i),
    .Y(_0029_)
  );
  sky130_fd_sc_hd__clkinv_1 _0806_ (
    .A(rst_i),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__clkinv_1 _0807_ (
    .A(rst_i),
    .Y(_0031_)
  );
  sky130_fd_sc_hd__clkinv_1 _0808_ (
    .A(rst_i),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__clkinv_1 _0809_ (
    .A(rst_i),
    .Y(_0033_)
  );
  sky130_fd_sc_hd__clkinv_1 _0810_ (
    .A(rst_i),
    .Y(_0034_)
  );
  sky130_fd_sc_hd__clkinv_1 _0811_ (
    .A(rst_i),
    .Y(_0035_)
  );
  sky130_fd_sc_hd__clkinv_1 _0812_ (
    .A(rst_i),
    .Y(_0036_)
  );
  sky130_fd_sc_hd__clkinv_1 _0813_ (
    .A(rst_i),
    .Y(_0037_)
  );
  sky130_fd_sc_hd__clkinv_1 _0814_ (
    .A(rst_i),
    .Y(_0038_)
  );
  sky130_fd_sc_hd__clkinv_1 _0815_ (
    .A(rst_i),
    .Y(_0039_)
  );
  sky130_fd_sc_hd__clkinv_1 _0816_ (
    .A(rst_i),
    .Y(_0040_)
  );
  sky130_fd_sc_hd__clkinv_1 _0817_ (
    .A(rst_i),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__clkinv_1 _0818_ (
    .A(rst_i),
    .Y(_0042_)
  );
  sky130_fd_sc_hd__clkinv_1 _0819_ (
    .A(rst_i),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__clkinv_1 _0820_ (
    .A(rst_i),
    .Y(_0044_)
  );
  sky130_fd_sc_hd__clkinv_1 _0821_ (
    .A(rst_i),
    .Y(_0045_)
  );
  sky130_fd_sc_hd__clkinv_1 _0822_ (
    .A(rst_i),
    .Y(_0046_)
  );
  sky130_fd_sc_hd__clkinv_1 _0823_ (
    .A(rst_i),
    .Y(_0047_)
  );
  sky130_fd_sc_hd__clkinv_1 _0824_ (
    .A(rst_i),
    .Y(_0048_)
  );
  sky130_fd_sc_hd__clkinv_1 _0825_ (
    .A(rst_i),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__clkinv_1 _0826_ (
    .A(rst_i),
    .Y(_0050_)
  );
  sky130_fd_sc_hd__clkinv_1 _0827_ (
    .A(rst_i),
    .Y(_0051_)
  );
  sky130_fd_sc_hd__clkinv_1 _0828_ (
    .A(rst_i),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__clkinv_1 _0829_ (
    .A(rst_i),
    .Y(_0053_)
  );
  sky130_fd_sc_hd__clkinv_1 _0830_ (
    .A(rst_i),
    .Y(_0054_)
  );
  sky130_fd_sc_hd__clkinv_1 _0831_ (
    .A(rst_i),
    .Y(_0055_)
  );
  sky130_fd_sc_hd__clkinv_1 _0832_ (
    .A(rst_i),
    .Y(_0056_)
  );
  sky130_fd_sc_hd__clkinv_1 _0833_ (
    .A(rst_i),
    .Y(_0057_)
  );
  sky130_fd_sc_hd__clkinv_1 _0834_ (
    .A(rst_i),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__clkinv_1 _0835_ (
    .A(rst_i),
    .Y(_0059_)
  );
  sky130_fd_sc_hd__clkinv_1 _0836_ (
    .A(rst_i),
    .Y(_0060_)
  );
  sky130_fd_sc_hd__clkinv_1 _0837_ (
    .A(rst_i),
    .Y(_0061_)
  );
  sky130_fd_sc_hd__clkinv_1 _0838_ (
    .A(rst_i),
    .Y(_0062_)
  );
  sky130_fd_sc_hd__clkinv_1 _0839_ (
    .A(rst_i),
    .Y(_0063_)
  );
  sky130_fd_sc_hd__clkinv_1 _0840_ (
    .A(rst_i),
    .Y(_0064_)
  );
  sky130_fd_sc_hd__clkinv_1 _0841_ (
    .A(rst_i),
    .Y(_0065_)
  );
  sky130_fd_sc_hd__clkinv_1 _0842_ (
    .A(rst_i),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__clkinv_1 _0843_ (
    .A(rst_i),
    .Y(_0067_)
  );
  sky130_fd_sc_hd__clkinv_1 _0844_ (
    .A(rst_i),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__clkinv_1 _0845_ (
    .A(rst_i),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__clkinv_1 _0846_ (
    .A(rst_i),
    .Y(_0070_)
  );
  sky130_fd_sc_hd__clkinv_1 _0847_ (
    .A(rst_i),
    .Y(_0071_)
  );
  sky130_fd_sc_hd__clkinv_1 _0848_ (
    .A(rst_i),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__clkinv_1 _0849_ (
    .A(rst_i),
    .Y(_0073_)
  );
  sky130_fd_sc_hd__clkinv_1 _0850_ (
    .A(rst_i),
    .Y(_0074_)
  );
  sky130_fd_sc_hd__clkinv_1 _0851_ (
    .A(rst_i),
    .Y(_0075_)
  );
  sky130_fd_sc_hd__clkinv_1 _0852_ (
    .A(rst_i),
    .Y(_0076_)
  );
  sky130_fd_sc_hd__clkinv_1 _0853_ (
    .A(rst_i),
    .Y(_0077_)
  );
  sky130_fd_sc_hd__clkinv_1 _0854_ (
    .A(rst_i),
    .Y(_0078_)
  );
  sky130_fd_sc_hd__clkinv_1 _0855_ (
    .A(rst_i),
    .Y(_0079_)
  );
  sky130_fd_sc_hd__clkinv_1 _0856_ (
    .A(rst_i),
    .Y(_0080_)
  );
  sky130_fd_sc_hd__clkinv_1 _0857_ (
    .A(rst_i),
    .Y(_0081_)
  );
  sky130_fd_sc_hd__clkinv_1 _0858_ (
    .A(rst_i),
    .Y(_0082_)
  );
  sky130_fd_sc_hd__clkinv_1 _0859_ (
    .A(rst_i),
    .Y(_0083_)
  );
  sky130_fd_sc_hd__clkinv_1 _0860_ (
    .A(rst_i),
    .Y(_0084_)
  );
  sky130_fd_sc_hd__clkinv_1 _0861_ (
    .A(rst_i),
    .Y(_0085_)
  );
  sky130_fd_sc_hd__clkinv_1 _0862_ (
    .A(rst_i),
    .Y(_0086_)
  );
  sky130_fd_sc_hd__clkinv_1 _0863_ (
    .A(rst_i),
    .Y(_0087_)
  );
  sky130_fd_sc_hd__clkinv_1 _0864_ (
    .A(rst_i),
    .Y(_0088_)
  );
  sky130_fd_sc_hd__clkinv_1 _0865_ (
    .A(rst_i),
    .Y(_0089_)
  );
  sky130_fd_sc_hd__clkinv_1 _0866_ (
    .A(rst_i),
    .Y(_0090_)
  );
  sky130_fd_sc_hd__clkinv_1 _0867_ (
    .A(rst_i),
    .Y(_0091_)
  );
  sky130_fd_sc_hd__clkinv_1 _0868_ (
    .A(rst_i),
    .Y(_0092_)
  );
  sky130_fd_sc_hd__clkinv_1 _0869_ (
    .A(rst_i),
    .Y(_0093_)
  );
  sky130_fd_sc_hd__clkinv_1 _0870_ (
    .A(rst_i),
    .Y(_0094_)
  );
  sky130_fd_sc_hd__clkinv_1 _0871_ (
    .A(rst_i),
    .Y(_0095_)
  );
  sky130_fd_sc_hd__clkinv_1 _0872_ (
    .A(rst_i),
    .Y(_0096_)
  );
  sky130_fd_sc_hd__clkinv_1 _0873_ (
    .A(rst_i),
    .Y(_0097_)
  );
  sky130_fd_sc_hd__clkinv_1 _0874_ (
    .A(rst_i),
    .Y(_0098_)
  );
  sky130_fd_sc_hd__clkinv_1 _0875_ (
    .A(rst_i),
    .Y(_0099_)
  );
  sky130_fd_sc_hd__clkinv_1 _0876_ (
    .A(rst_i),
    .Y(_0100_)
  );
  sky130_fd_sc_hd__clkinv_1 _0877_ (
    .A(rst_i),
    .Y(_0101_)
  );
  sky130_fd_sc_hd__clkinv_1 _0878_ (
    .A(rst_i),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__clkinv_1 _0879_ (
    .A(rst_i),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__clkinv_1 _0880_ (
    .A(rst_i),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__clkinv_1 _0881_ (
    .A(rst_i),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__clkinv_1 _0882_ (
    .A(rst_i),
    .Y(_0106_)
  );
  sky130_fd_sc_hd__clkinv_1 _0883_ (
    .A(rst_i),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__clkinv_1 _0884_ (
    .A(rst_i),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__clkinv_1 _0885_ (
    .A(rst_i),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__clkinv_1 _0886_ (
    .A(rst_i),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__clkinv_1 _0887_ (
    .A(rst_i),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__clkinv_1 _0888_ (
    .A(rst_i),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__clkinv_1 _0889_ (
    .A(rst_i),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__clkinv_1 _0890_ (
    .A(rst_i),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__clkinv_1 _0891_ (
    .A(rst_i),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__clkinv_1 _0892_ (
    .A(rst_i),
    .Y(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0893_ (
    .CLK(clk_i),
    .D(_0001_),
    .Q(ack_o),
    .RESET_B(_0108_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0894_ (
    .CLK(clk_i),
    .D(_0000_[0]),
    .Q(IC_REG[0]),
    .RESET_B(_0030_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0895_ (
    .CLK(clk_i),
    .D(_0000_[1]),
    .Q(IC_REG[1]),
    .RESET_B(_0031_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0896_ (
    .CLK(clk_i),
    .D(_0000_[2]),
    .Q(IC_REG[2]),
    .RESET_B(_0029_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0897_ (
    .CLK(clk_i),
    .D(_0000_[3]),
    .Q(IC_REG[3]),
    .RESET_B(_0028_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0898_ (
    .CLK(clk_i),
    .D(_0000_[4]),
    .Q(IC_REG[4]),
    .RESET_B(_0027_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0899_ (
    .CLK(clk_i),
    .D(_0000_[5]),
    .Q(IC_REG[5]),
    .RESET_B(_0026_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0900_ (
    .CLK(clk_i),
    .D(_0000_[6]),
    .Q(IC_REG[6]),
    .RESET_B(_0025_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0901_ (
    .CLK(clk_i),
    .D(_0000_[7]),
    .Q(IC_REG[7]),
    .RESET_B(_0024_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0902_ (
    .CLK(clk_i),
    .D(_0000_[8]),
    .Q(IC_REG[8]),
    .RESET_B(_0023_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0903_ (
    .CLK(clk_i),
    .D(_0000_[9]),
    .Q(IC_REG[9]),
    .RESET_B(_0022_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0904_ (
    .CLK(clk_i),
    .D(_0000_[10]),
    .Q(IC_REG[10]),
    .RESET_B(_0021_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0905_ (
    .CLK(clk_i),
    .D(_0000_[11]),
    .Q(IC_REG[11]),
    .RESET_B(_0020_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0906_ (
    .CLK(clk_i),
    .D(_0000_[12]),
    .Q(IC_REG[12]),
    .RESET_B(_0019_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0907_ (
    .CLK(clk_i),
    .D(_0000_[13]),
    .Q(IC_REG[13]),
    .RESET_B(_0018_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0908_ (
    .CLK(clk_i),
    .D(_0000_[14]),
    .Q(IC_REG[14]),
    .RESET_B(_0017_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0909_ (
    .CLK(clk_i),
    .D(_0000_[15]),
    .Q(IC_REG[15]),
    .RESET_B(_0016_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0910_ (
    .CLK(clk_i),
    .D(_0000_[16]),
    .Q(IC_REG[16]),
    .RESET_B(_0015_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0911_ (
    .CLK(clk_i),
    .D(_0000_[17]),
    .Q(IC_REG[17]),
    .RESET_B(_0014_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0912_ (
    .CLK(clk_i),
    .D(_0000_[18]),
    .Q(IC_REG[18]),
    .RESET_B(_0013_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0913_ (
    .CLK(clk_i),
    .D(_0000_[19]),
    .Q(IC_REG[19]),
    .RESET_B(_0012_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0914_ (
    .CLK(clk_i),
    .D(_0000_[20]),
    .Q(IC_REG[20]),
    .RESET_B(_0011_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0915_ (
    .CLK(clk_i),
    .D(_0000_[21]),
    .Q(IC_REG[21]),
    .RESET_B(_0010_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0916_ (
    .CLK(clk_i),
    .D(_0000_[22]),
    .Q(IC_REG[22]),
    .RESET_B(_0009_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0917_ (
    .CLK(clk_i),
    .D(_0000_[23]),
    .Q(IC_REG[23]),
    .RESET_B(_0008_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0918_ (
    .CLK(clk_i),
    .D(_0000_[24]),
    .Q(IC_REG[24]),
    .RESET_B(_0102_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0919_ (
    .CLK(clk_i),
    .D(_0000_[25]),
    .Q(IC_REG[25]),
    .RESET_B(_0007_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0920_ (
    .CLK(clk_i),
    .D(_0000_[26]),
    .Q(IC_REG[26]),
    .RESET_B(_0006_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0921_ (
    .CLK(clk_i),
    .D(_0000_[27]),
    .Q(IC_REG[27]),
    .RESET_B(_0005_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0922_ (
    .CLK(clk_i),
    .D(_0000_[28]),
    .Q(IC_REG[28]),
    .RESET_B(_0004_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0923_ (
    .CLK(clk_i),
    .D(_0000_[29]),
    .Q(IC_REG[29]),
    .RESET_B(_0003_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0924_ (
    .CLK(clk_i),
    .D(_0000_[30]),
    .Q(IC_REG[30]),
    .RESET_B(_0002_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0925_ (
    .CLK(clk_i),
    .D(_0000_[31]),
    .Q(IC_REG[31]),
    .RESET_B(_0113_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0926_ (
    .CLK(clk_i),
    .D(_0160_),
    .Q(DATAO_REG[0]),
    .RESET_B(_0076_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0927_ (
    .CLK(clk_i),
    .D(_0159_),
    .Q(DATAO_REG[1]),
    .RESET_B(_0075_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0928_ (
    .CLK(clk_i),
    .D(_0158_),
    .Q(DATAO_REG[2]),
    .RESET_B(_0074_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0929_ (
    .CLK(clk_i),
    .D(_0157_),
    .Q(DATAO_REG[3]),
    .RESET_B(_0073_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0930_ (
    .CLK(clk_i),
    .D(_0156_),
    .Q(DATAO_REG[4]),
    .RESET_B(_0072_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0931_ (
    .CLK(clk_i),
    .D(_0155_),
    .Q(DATAO_REG[5]),
    .RESET_B(_0071_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0932_ (
    .CLK(clk_i),
    .D(_0154_),
    .Q(DATAO_REG[6]),
    .RESET_B(_0070_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0933_ (
    .CLK(clk_i),
    .D(_0190_),
    .Q(DATAO_REG[7]),
    .RESET_B(_0107_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0934_ (
    .CLK(clk_i),
    .D(_0153_),
    .Q(IM_REG[0]),
    .RESET_B(_0069_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0935_ (
    .CLK(clk_i),
    .D(_0152_),
    .Q(IM_REG[1]),
    .RESET_B(_0068_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0936_ (
    .CLK(clk_i),
    .D(_0151_),
    .Q(IM_REG[2]),
    .RESET_B(_0067_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0937_ (
    .CLK(clk_i),
    .D(_0150_),
    .Q(IM_REG[3]),
    .RESET_B(_0066_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0938_ (
    .CLK(clk_i),
    .D(_0149_),
    .Q(IM_REG[4]),
    .RESET_B(_0065_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0939_ (
    .CLK(clk_i),
    .D(_0148_),
    .Q(IM_REG[5]),
    .RESET_B(_0064_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0940_ (
    .CLK(clk_i),
    .D(_0147_),
    .Q(IM_REG[6]),
    .RESET_B(_0063_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0941_ (
    .CLK(clk_i),
    .D(_0146_),
    .Q(IM_REG[7]),
    .RESET_B(_0062_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0942_ (
    .CLK(clk_i),
    .D(_0145_),
    .Q(IM_REG[8]),
    .RESET_B(_0061_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0943_ (
    .CLK(clk_i),
    .D(_0144_),
    .Q(IM_REG[9]),
    .RESET_B(_0060_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0944_ (
    .CLK(clk_i),
    .D(_0143_),
    .Q(IM_REG[10]),
    .RESET_B(_0059_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0945_ (
    .CLK(clk_i),
    .D(_0142_),
    .Q(IM_REG[11]),
    .RESET_B(_0058_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0946_ (
    .CLK(clk_i),
    .D(_0141_),
    .Q(IM_REG[12]),
    .RESET_B(_0057_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0947_ (
    .CLK(clk_i),
    .D(_0140_),
    .Q(IM_REG[13]),
    .RESET_B(_0056_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0948_ (
    .CLK(clk_i),
    .D(_0139_),
    .Q(IM_REG[14]),
    .RESET_B(_0055_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0949_ (
    .CLK(clk_i),
    .D(_0138_),
    .Q(IM_REG[15]),
    .RESET_B(_0054_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0950_ (
    .CLK(clk_i),
    .D(_0137_),
    .Q(IM_REG[16]),
    .RESET_B(_0053_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0951_ (
    .CLK(clk_i),
    .D(_0136_),
    .Q(IM_REG[17]),
    .RESET_B(_0052_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0952_ (
    .CLK(clk_i),
    .D(_0135_),
    .Q(IM_REG[18]),
    .RESET_B(_0051_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0953_ (
    .CLK(clk_i),
    .D(_0134_),
    .Q(IM_REG[19]),
    .RESET_B(_0050_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0954_ (
    .CLK(clk_i),
    .D(_0133_),
    .Q(IM_REG[20]),
    .RESET_B(_0049_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0955_ (
    .CLK(clk_i),
    .D(_0132_),
    .Q(IM_REG[21]),
    .RESET_B(_0048_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0956_ (
    .CLK(clk_i),
    .D(_0131_),
    .Q(IM_REG[22]),
    .RESET_B(_0047_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0957_ (
    .CLK(clk_i),
    .D(_0130_),
    .Q(IM_REG[23]),
    .RESET_B(_0046_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0958_ (
    .CLK(clk_i),
    .D(_0129_),
    .Q(IM_REG[24]),
    .RESET_B(_0045_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0959_ (
    .CLK(clk_i),
    .D(_0128_),
    .Q(IM_REG[25]),
    .RESET_B(_0044_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0960_ (
    .CLK(clk_i),
    .D(_0127_),
    .Q(IM_REG[26]),
    .RESET_B(_0043_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0961_ (
    .CLK(clk_i),
    .D(_0126_),
    .Q(IM_REG[27]),
    .RESET_B(_0042_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0962_ (
    .CLK(clk_i),
    .D(_0125_),
    .Q(IM_REG[28]),
    .RESET_B(_0041_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0963_ (
    .CLK(clk_i),
    .D(_0124_),
    .Q(IM_REG[29]),
    .RESET_B(_0040_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0964_ (
    .CLK(clk_i),
    .D(_0123_),
    .Q(IM_REG[30]),
    .RESET_B(_0039_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0965_ (
    .CLK(clk_i),
    .D(_0191_),
    .Q(IM_REG[31]),
    .RESET_B(_0109_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0966_ (
    .CLK(clk_i),
    .D(_0192_),
    .Q(RIS_REG[31]),
    .RESET_B(_0110_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0967_ (
    .CLK(clk_i),
    .D(_0186_),
    .Q(RIS_REG[30]),
    .RESET_B(_0103_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0968_ (
    .CLK(clk_i),
    .D(_0187_),
    .Q(RIS_REG[29]),
    .RESET_B(_0104_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0969_ (
    .CLK(clk_i),
    .D(_0196_),
    .Q(RIS_REG[28]),
    .RESET_B(_0115_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0970_ (
    .CLK(clk_i),
    .D(_0195_),
    .Q(RIS_REG[27]),
    .RESET_B(_0114_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0971_ (
    .CLK(clk_i),
    .D(_0188_),
    .Q(RIS_REG[26]),
    .RESET_B(_0105_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0972_ (
    .CLK(clk_i),
    .D(_0189_),
    .Q(RIS_REG[25]),
    .RESET_B(_0106_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0973_ (
    .CLK(clk_i),
    .D(_0161_),
    .Q(RIS_REG[24]),
    .RESET_B(_0077_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0974_ (
    .CLK(clk_i),
    .D(_0162_),
    .Q(RIS_REG[23]),
    .RESET_B(_0078_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0975_ (
    .CLK(clk_i),
    .D(_0163_),
    .Q(RIS_REG[22]),
    .RESET_B(_0079_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0976_ (
    .CLK(clk_i),
    .D(_0164_),
    .Q(RIS_REG[21]),
    .RESET_B(_0080_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0977_ (
    .CLK(clk_i),
    .D(_0165_),
    .Q(RIS_REG[20]),
    .RESET_B(_0081_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0978_ (
    .CLK(clk_i),
    .D(_0166_),
    .Q(RIS_REG[19]),
    .RESET_B(_0082_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0979_ (
    .CLK(clk_i),
    .D(_0167_),
    .Q(RIS_REG[18]),
    .RESET_B(_0083_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0980_ (
    .CLK(clk_i),
    .D(_0168_),
    .Q(RIS_REG[17]),
    .RESET_B(_0084_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0981_ (
    .CLK(clk_i),
    .D(_0169_),
    .Q(RIS_REG[16]),
    .RESET_B(_0085_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0982_ (
    .CLK(clk_i),
    .D(_0170_),
    .Q(RIS_REG[15]),
    .RESET_B(_0086_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0983_ (
    .CLK(clk_i),
    .D(_0171_),
    .Q(RIS_REG[14]),
    .RESET_B(_0087_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0984_ (
    .CLK(clk_i),
    .D(_0172_),
    .Q(RIS_REG[13]),
    .RESET_B(_0088_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0985_ (
    .CLK(clk_i),
    .D(_0173_),
    .Q(RIS_REG[12]),
    .RESET_B(_0089_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0986_ (
    .CLK(clk_i),
    .D(_0174_),
    .Q(RIS_REG[11]),
    .RESET_B(_0090_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0987_ (
    .CLK(clk_i),
    .D(_0175_),
    .Q(RIS_REG[10]),
    .RESET_B(_0091_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0988_ (
    .CLK(clk_i),
    .D(_0176_),
    .Q(RIS_REG[9]),
    .RESET_B(_0092_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0989_ (
    .CLK(clk_i),
    .D(_0177_),
    .Q(RIS_REG[8]),
    .RESET_B(_0093_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0990_ (
    .CLK(clk_i),
    .D(_0178_),
    .Q(RIS_REG[7]),
    .RESET_B(_0094_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0991_ (
    .CLK(clk_i),
    .D(_0179_),
    .Q(RIS_REG[6]),
    .RESET_B(_0095_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0992_ (
    .CLK(clk_i),
    .D(_0180_),
    .Q(RIS_REG[5]),
    .RESET_B(_0096_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0993_ (
    .CLK(clk_i),
    .D(_0181_),
    .Q(RIS_REG[4]),
    .RESET_B(_0097_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0994_ (
    .CLK(clk_i),
    .D(_0182_),
    .Q(RIS_REG[3]),
    .RESET_B(_0098_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0995_ (
    .CLK(clk_i),
    .D(_0183_),
    .Q(RIS_REG[2]),
    .RESET_B(_0099_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0996_ (
    .CLK(clk_i),
    .D(_0184_),
    .Q(RIS_REG[1]),
    .RESET_B(_0100_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0997_ (
    .CLK(clk_i),
    .D(_0185_),
    .Q(RIS_REG[0]),
    .RESET_B(_0101_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0998_ (
    .CLK(clk_i),
    .D(_0122_),
    .Q(DIR_REG[0]),
    .RESET_B(_0038_)
  );
  sky130_fd_sc_hd__dfrtp_1 _0999_ (
    .CLK(clk_i),
    .D(_0121_),
    .Q(DIR_REG[1]),
    .RESET_B(_0037_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1000_ (
    .CLK(clk_i),
    .D(_0120_),
    .Q(DIR_REG[2]),
    .RESET_B(_0036_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1001_ (
    .CLK(clk_i),
    .D(_0119_),
    .Q(DIR_REG[3]),
    .RESET_B(_0035_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1002_ (
    .CLK(clk_i),
    .D(_0118_),
    .Q(DIR_REG[4]),
    .RESET_B(_0034_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1003_ (
    .CLK(clk_i),
    .D(_0117_),
    .Q(DIR_REG[5]),
    .RESET_B(_0033_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1004_ (
    .CLK(clk_i),
    .D(_0116_),
    .Q(DIR_REG[6]),
    .RESET_B(_0032_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1005_ (
    .CLK(clk_i),
    .D(_0193_),
    .Q(DIR_REG[7]),
    .RESET_B(_0111_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1006_ (
    .CLK(clk_i),
    .D(_0194_),
    .Q(GCLK_REG),
    .RESET_B(_0112_)
  );
  ef_util_gating_cell clk_gate_cell (
    .clk(clk_i),
    .clk_en(GCLK_REG),
    .clk_o(clk)
  );
  EF_GPIO8 instance_to_wrap (
    .bus_in(bus_in),
    .bus_oe(DIR_REG),
    .bus_out(DATAO_REG),
    .clk(clk),
    .io_in(io_in),
    .io_oe(io_oe),
    .io_out(io_out),
    .pin0_hi(pin0_hi),
    .pin0_lo(pin0_lo),
    .pin0_ne(pin0_ne),
    .pin0_pe(pin0_pe),
    .pin1_hi(pin1_hi),
    .pin1_lo(pin1_lo),
    .pin1_ne(pin1_ne),
    .pin1_pe(pin1_pe),
    .pin2_hi(pin2_hi),
    .pin2_lo(pin2_lo),
    .pin2_ne(pin2_ne),
    .pin2_pe(pin2_pe),
    .pin3_hi(pin3_hi),
    .pin3_lo(pin3_lo),
    .pin3_ne(pin3_ne),
    .pin3_pe(pin3_pe),
    .pin4_hi(pin4_hi),
    .pin4_lo(pin4_lo),
    .pin4_ne(pin4_ne),
    .pin4_pe(pin4_pe),
    .pin5_hi(pin5_hi),
    .pin5_lo(pin5_lo),
    .pin5_ne(pin5_ne),
    .pin5_pe(pin5_pe),
    .pin6_hi(pin6_hi),
    .pin6_lo(pin6_lo),
    .pin6_ne(pin6_ne),
    .pin6_pe(pin6_pe),
    .pin7_hi(pin7_hi),
    .pin7_lo(pin7_lo),
    .pin7_ne(pin7_ne),
    .pin7_pe(pin7_pe),
    .rst_n(rst_n)
  );
  assign P7NE = pin7_ne;
  assign P6NE = pin6_ne;
  assign P5NE = pin5_ne;
  assign P4NE = pin4_ne;
  assign P3NE = pin3_ne;
  assign P2NE = pin2_ne;
  assign P1NE = pin1_ne;
  assign P0NE = pin0_ne;
  assign P7PE = pin7_pe;
  assign P6PE = pin6_pe;
  assign P5PE = pin5_pe;
  assign P4PE = pin4_pe;
  assign P3PE = pin3_pe;
  assign P2PE = pin2_pe;
  assign P1PE = pin1_pe;
  assign P0PE = pin0_pe;
  assign P7LO = pin7_lo;
  assign P6LO = pin6_lo;
  assign P5LO = pin5_lo;
  assign P4LO = pin4_lo;
  assign P3LO = pin3_lo;
  assign P2LO = pin2_lo;
  assign P1LO = pin1_lo;
  assign P0LO = pin0_lo;
  assign P7HI = pin7_hi;
  assign P6HI = pin6_hi;
  assign P5HI = pin5_hi;
  assign P4HI = pin4_hi;
  assign P3HI = pin3_hi;
  assign P2HI = pin2_hi;
  assign P1HI = pin1_hi;
  assign P0HI = pin0_hi;
  assign DATAI_WIRE = bus_in;
  assign bus_oe = DIR_REG;
  assign bus_out = DATAO_REG;
  assign clk_gated_en = GCLK_REG;
  assign clk_g = clk;
endmodule

module ef_util_gating_cell(clk, rst_n, clk_en, clk_o);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input clk_en;
  wire clk_en;
  output clk_o;
  wire clk_o;
  assign clk_o = clk;
endmodule

module ef_util_ned(clk, in, out);
  input clk;
  wire clk;
  input in;
  wire in;
  output out;
  wire out;
  wire last_in;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0_ (
    .A(last_in),
    .SLEEP(in),
    .X(out)
  );
  sky130_fd_sc_hd__dfxtp_1 _1_ (
    .CLK(clk),
    .D(in),
    .Q(last_in)
  );
endmodule

module ef_util_ped(clk, in, out);
  input clk;
  wire clk;
  input in;
  wire in;
  output out;
  wire out;
  wire last_in;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0_ (
    .A(in),
    .SLEEP(last_in),
    .X(out)
  );
  sky130_fd_sc_hd__dfxtp_1 _1_ (
    .CLK(clk),
    .D(in),
    .Q(last_in)
  );
endmodule

module ef_util_sync(clk, in, out);
  input clk;
  wire clk;
  input in;
  wire in;
  output out;
  wire out;
  wire [1:0] sync;
  sky130_fd_sc_hd__dfxtp_1 _0_ (
    .CLK(clk),
    .D(in),
    .Q(sync[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _1_ (
    .CLK(clk),
    .D(sync[0]),
    .Q(sync[1])
  );
  assign out = sync[1];
endmodule
