/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

module clk_rst_mgr(clk_i, rst_ni, user_clock_i, user_reset_n_i, wb_adr_i, wb_dat_i, wb_dat_o, wb_sel_i, wb_we_i, wb_stb_i, wb_cyc_i, wb_ack_o, wb_rst_n_o, cpu_rst_n_o, wdg_rst_req_i, sys_clk_o);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input user_clock_i;
  wire user_clock_i;
  input user_reset_n_i;
  wire user_reset_n_i;
  input [31:0] wb_adr_i;
  wire [31:0] wb_adr_i;
  input [31:0] wb_dat_i;
  wire [31:0] wb_dat_i;
  output [31:0] wb_dat_o;
  wire [31:0] wb_dat_o;
  input [3:0] wb_sel_i;
  wire [3:0] wb_sel_i;
  input wb_we_i;
  wire wb_we_i;
  input wb_stb_i;
  wire wb_stb_i;
  input wb_cyc_i;
  wire wb_cyc_i;
  output wb_ack_o;
  wire wb_ack_o;
  output wb_rst_n_o;
  wire wb_rst_n_o;
  output cpu_rst_n_o;
  wire cpu_rst_n_o;
  input wdg_rst_req_i;
  wire wdg_rst_req_i;
  output sys_clk_o;
  wire sys_clk_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire cpu_held;
  wire [4:0] cpu_rst_counter;
  wire [1:0] rst_sync;
  wire wdg_reset_occurred;
  sky130_fd_sc_hd__clkinv_1 _30_ (
    .A(cpu_rst_counter[4]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__clkinv_1 _31_ (
    .A(cpu_held),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand3_1 _32_ (
    .A(cpu_rst_counter[2]),
    .B(cpu_rst_counter[1]),
    .C(cpu_rst_counter[0]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2b_1 _33_ (
    .A_N(cpu_rst_counter[3]),
    .B(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _34_ (
    .A(rst_sync[1]),
    .SLEEP(wdg_rst_req_i),
    .X(_16_)
  );
  sky130_fd_sc_hd__nand2_1 _35_ (
    .A(cpu_rst_counter[4]),
    .B(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a21boi_0 _36_ (
    .A1(_12_),
    .A2(cpu_held),
    .B1_N(_16_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__clkinv_1 _37_ (
    .A(_18_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _38_ (
    .A(cpu_held),
    .B(_16_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor4bb_1 _39_ (
    .A(cpu_rst_counter[4]),
    .B(wdg_rst_req_i),
    .C_N(cpu_held),
    .D_N(rst_sync[1]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nand4_1 _40_ (
    .A(cpu_rst_counter[2]),
    .B(cpu_rst_counter[3]),
    .C(cpu_rst_counter[1]),
    .D(cpu_rst_counter[0]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a32o_1 _41_ (
    .A1(_15_),
    .A2(_20_),
    .A3(_21_),
    .B1(_18_),
    .B2(cpu_rst_counter[3]),
    .X(_02_)
  );
  sky130_fd_sc_hd__a21o_1 _42_ (
    .A1(cpu_rst_counter[1]),
    .A2(cpu_rst_counter[0]),
    .B1(cpu_rst_counter[2]),
    .X(_22_)
  );
  sky130_fd_sc_hd__a32o_1 _43_ (
    .A1(_14_),
    .A2(_20_),
    .A3(_22_),
    .B1(_18_),
    .B2(cpu_rst_counter[2]),
    .X(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _44_ (
    .A(cpu_rst_counter[1]),
    .B(cpu_rst_counter[0]),
    .X(_23_)
  );
  sky130_fd_sc_hd__a22o_1 _45_ (
    .A1(cpu_rst_counter[1]),
    .A2(_18_),
    .B1(_20_),
    .B2(_23_),
    .X(_04_)
  );
  sky130_fd_sc_hd__nor2_1 _46_ (
    .A(cpu_rst_counter[0]),
    .B(_20_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__a21oi_1 _47_ (
    .A1(cpu_rst_counter[0]),
    .A2(_00_),
    .B1(_24_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _48_ (
    .A(wb_cyc_i),
    .B(wb_stb_i),
    .Y(_25_)
  );
  sky130_fd_sc_hd__nor2_1 _49_ (
    .A(wb_ack_o),
    .B(_25_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor4bb_1 _50_ (
    .A(wb_we_i),
    .B(wb_ack_o),
    .C_N(wb_cyc_i),
    .D_N(wb_stb_i),
    .Y(_26_)
  );
  sky130_fd_sc_hd__nor2_1 _51_ (
    .A(wb_dat_o[1]),
    .B(_26_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a21oi_1 _52_ (
    .A1(_13_),
    .A2(_26_),
    .B1(_27_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _53_ (
    .A(wb_dat_o[0]),
    .B(_26_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a21oi_1 _54_ (
    .A1(rst_sync[1]),
    .A2(_26_),
    .B1(_28_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__o21ai_0 _55_ (
    .A1(_19_),
    .A2(_21_),
    .B1(_17_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _56_ (
    .A0(wb_dat_o[2]),
    .A1(wdg_reset_occurred),
    .S(_26_),
    .X(_09_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _57_ (
    .A(wdg_rst_req_i),
    .SLEEP(wdg_reset_occurred),
    .X(_10_)
  );
  sky130_fd_sc_hd__nand3_1 _58_ (
    .A(_13_),
    .B(cpu_rst_n_o),
    .C(_16_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__o21ai_0 _59_ (
    .A1(_12_),
    .A2(_19_),
    .B1(_29_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__dfrtp_1 _60_ (
    .CLK(clk_i),
    .D(_07_),
    .Q(wb_dat_o[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _61_ (
    .CLK(clk_i),
    .D(_06_),
    .Q(wb_dat_o[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _62_ (
    .CLK(clk_i),
    .D(_09_),
    .Q(wb_dat_o[2]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _63_ (
    .CLK(clk_i),
    .D(_05_),
    .Q(cpu_rst_counter[0]),
    .RESET_B(user_reset_n_i)
  );
  sky130_fd_sc_hd__dfrtp_1 _64_ (
    .CLK(clk_i),
    .D(_04_),
    .Q(cpu_rst_counter[1]),
    .RESET_B(user_reset_n_i)
  );
  sky130_fd_sc_hd__dfrtp_1 _65_ (
    .CLK(clk_i),
    .D(_03_),
    .Q(cpu_rst_counter[2]),
    .RESET_B(user_reset_n_i)
  );
  sky130_fd_sc_hd__dfrtp_1 _66_ (
    .CLK(clk_i),
    .D(_02_),
    .Q(cpu_rst_counter[3]),
    .RESET_B(user_reset_n_i)
  );
  sky130_fd_sc_hd__dfrtp_1 _67_ (
    .CLK(clk_i),
    .D(_08_),
    .Q(cpu_rst_counter[4]),
    .RESET_B(user_reset_n_i)
  );
  sky130_fd_sc_hd__dfrtp_1 _68_ (
    .CLK(clk_i),
    .D(_10_),
    .Q(wdg_reset_occurred),
    .RESET_B(user_reset_n_i)
  );
  sky130_fd_sc_hd__dfrtp_1 _69_ (
    .CLK(clk_i),
    .D(_11_),
    .Q(cpu_rst_n_o),
    .RESET_B(user_reset_n_i)
  );
  sky130_fd_sc_hd__dfrtp_1 _70_ (
    .CLK(clk_i),
    .D(_01_),
    .Q(wb_ack_o),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfstp_2 _71_ (
    .CLK(clk_i),
    .D(_00_),
    .Q(cpu_held),
    .SET_B(user_reset_n_i)
  );
  sky130_fd_sc_hd__dfrtp_1 _72_ (
    .CLK(clk_i),
    .D(1'h1),
    .Q(rst_sync[0]),
    .RESET_B(user_reset_n_i)
  );
  sky130_fd_sc_hd__dfrtp_1 _73_ (
    .CLK(clk_i),
    .D(rst_sync[0]),
    .Q(rst_sync[1]),
    .RESET_B(user_reset_n_i)
  );
  assign sys_clk_o = user_clock_i;
  assign wb_rst_n_o = rst_sync[1];
  assign wb_dat_o[31:3] = 29'h00000000;
endmodule
