/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

module EF_WDT32(clk, rst_n, WDTMR, WDTLOAD, WDTTO, WDTEN);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  output [31:0] WDTMR;
  wire [31:0] WDTMR;
  input [31:0] WDTLOAD;
  wire [31:0] WDTLOAD;
  output WDTTO;
  wire WDTTO;
  input WDTEN;
  wire WDTEN;
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  sky130_fd_sc_hd__clkinv_1 _064_ (
    .A(WDTLOAD[0]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _065_ (
    .A(WDTLOAD[31]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _066_ (
    .A(WDTMR[1]),
    .B(WDTMR[0]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__or4_1 _067_ (
    .A(WDTMR[2]),
    .B(WDTMR[3]),
    .C(WDTMR[1]),
    .D(WDTMR[0]),
    .X(_003_)
  );
  sky130_fd_sc_hd__nor3_1 _068_ (
    .A(WDTMR[4]),
    .B(WDTMR[5]),
    .C(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor4_1 _069_ (
    .A(WDTMR[6]),
    .B(WDTMR[4]),
    .C(WDTMR[5]),
    .D(_003_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2b_1 _070_ (
    .A_N(WDTMR[7]),
    .B(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _071_ (
    .A(WDTMR[8]),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor4b_1 _072_ (
    .A(WDTMR[7]),
    .B(WDTMR[8]),
    .C(WDTMR[9]),
    .D_N(_005_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _073_ (
    .A(_008_),
    .SLEEP(WDTMR[10]),
    .X(_009_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _074_ (
    .A(_009_),
    .SLEEP(WDTMR[11]),
    .X(_010_)
  );
  sky130_fd_sc_hd__nor4b_1 _075_ (
    .A(WDTMR[10]),
    .B(WDTMR[11]),
    .C(WDTMR[12]),
    .D_N(_008_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2b_1 _076_ (
    .A_N(WDTMR[13]),
    .B(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _077_ (
    .A(WDTMR[14]),
    .B(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor4b_1 _078_ (
    .A(WDTMR[13]),
    .B(WDTMR[14]),
    .C(WDTMR[15]),
    .D_N(_011_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2b_1 _079_ (
    .A_N(WDTMR[16]),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _080_ (
    .A(WDTMR[17]),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor4b_1 _081_ (
    .A(WDTMR[16]),
    .B(WDTMR[17]),
    .C(WDTMR[18]),
    .D_N(_014_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2b_1 _082_ (
    .A_N(WDTMR[19]),
    .B(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _083_ (
    .A(WDTMR[20]),
    .B(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor4b_1 _084_ (
    .A(WDTMR[19]),
    .B(WDTMR[20]),
    .C(WDTMR[21]),
    .D_N(_017_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2b_1 _085_ (
    .A_N(WDTMR[22]),
    .B(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _086_ (
    .A(WDTMR[23]),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor4b_1 _087_ (
    .A(WDTMR[22]),
    .B(WDTMR[23]),
    .C(WDTMR[24]),
    .D_N(_020_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2b_1 _088_ (
    .A_N(WDTMR[25]),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _089_ (
    .A(WDTMR[26]),
    .B(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__or4b_1 _090_ (
    .A(WDTMR[25]),
    .B(WDTMR[26]),
    .C(WDTMR[27]),
    .D_N(_023_),
    .X(_026_)
  );
  sky130_fd_sc_hd__or3_1 _091_ (
    .A(WDTMR[28]),
    .B(WDTMR[29]),
    .C(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _092_ (
    .A(WDTMR[30]),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o21a_1 _093_ (
    .A1(WDTMR[30]),
    .A2(_027_),
    .B1(WDTEN),
    .X(_029_)
  );
  sky130_fd_sc_hd__o31a_1 _094_ (
    .A1(WDTMR[30]),
    .A2(WDTMR[31]),
    .A3(_027_),
    .B1(WDTEN),
    .X(_030_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _095_ (
    .A1_N(WDTLOAD[30]),
    .A2_N(_030_),
    .B1(_029_),
    .B2(_028_),
    .Y(_000_[30])
  );
  sky130_fd_sc_hd__o21ai_0 _096_ (
    .A1(WDTMR[28]),
    .A2(_026_),
    .B1(WDTMR[29]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand3_1 _097_ (
    .A(WDTEN),
    .B(_027_),
    .C(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__o21a_1 _098_ (
    .A1(WDTLOAD[29]),
    .A2(_030_),
    .B1(_032_),
    .X(_000_[29])
  );
  sky130_fd_sc_hd__xnor2_1 _099_ (
    .A(WDTMR[28]),
    .B(_026_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(WDTLOAD[28]),
    .A1(_033_),
    .S(_030_),
    .X(_000_[28])
  );
  sky130_fd_sc_hd__xor2_1 _101_ (
    .A(WDTMR[27]),
    .B(_025_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(WDTLOAD[27]),
    .A1(_034_),
    .S(_030_),
    .X(_000_[27])
  );
  sky130_fd_sc_hd__xnor2_1 _103_ (
    .A(WDTMR[26]),
    .B(_024_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(WDTLOAD[26]),
    .A1(_035_),
    .S(_030_),
    .X(_000_[26])
  );
  sky130_fd_sc_hd__xor2_1 _105_ (
    .A(WDTMR[25]),
    .B(_023_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(WDTLOAD[25]),
    .A1(_036_),
    .S(_030_),
    .X(_000_[25])
  );
  sky130_fd_sc_hd__xor2_1 _107_ (
    .A(WDTMR[24]),
    .B(_022_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _108_ (
    .A0(WDTLOAD[24]),
    .A1(_037_),
    .S(_030_),
    .X(_000_[24])
  );
  sky130_fd_sc_hd__xnor2_1 _109_ (
    .A(WDTMR[23]),
    .B(_021_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _110_ (
    .A0(WDTLOAD[23]),
    .A1(_038_),
    .S(_030_),
    .X(_000_[23])
  );
  sky130_fd_sc_hd__xor2_1 _111_ (
    .A(WDTMR[22]),
    .B(_020_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(WDTLOAD[22]),
    .A1(_039_),
    .S(_030_),
    .X(_000_[22])
  );
  sky130_fd_sc_hd__xor2_1 _113_ (
    .A(WDTMR[21]),
    .B(_019_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _114_ (
    .A0(WDTLOAD[21]),
    .A1(_040_),
    .S(_030_),
    .X(_000_[21])
  );
  sky130_fd_sc_hd__xnor2_1 _115_ (
    .A(WDTMR[20]),
    .B(_018_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _116_ (
    .A0(WDTLOAD[20]),
    .A1(_041_),
    .S(_030_),
    .X(_000_[20])
  );
  sky130_fd_sc_hd__xor2_1 _117_ (
    .A(WDTMR[19]),
    .B(_017_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _118_ (
    .A0(WDTLOAD[19]),
    .A1(_042_),
    .S(_030_),
    .X(_000_[19])
  );
  sky130_fd_sc_hd__xor2_1 _119_ (
    .A(WDTMR[18]),
    .B(_016_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _120_ (
    .A0(WDTLOAD[18]),
    .A1(_043_),
    .S(_030_),
    .X(_000_[18])
  );
  sky130_fd_sc_hd__xnor2_1 _121_ (
    .A(WDTMR[17]),
    .B(_015_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _122_ (
    .A0(WDTLOAD[17]),
    .A1(_044_),
    .S(_030_),
    .X(_000_[17])
  );
  sky130_fd_sc_hd__xor2_1 _123_ (
    .A(WDTMR[16]),
    .B(_014_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _124_ (
    .A0(WDTLOAD[16]),
    .A1(_045_),
    .S(_030_),
    .X(_000_[16])
  );
  sky130_fd_sc_hd__xor2_1 _125_ (
    .A(WDTMR[15]),
    .B(_013_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _126_ (
    .A0(WDTLOAD[15]),
    .A1(_046_),
    .S(_030_),
    .X(_000_[15])
  );
  sky130_fd_sc_hd__xnor2_1 _127_ (
    .A(WDTMR[14]),
    .B(_012_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _128_ (
    .A0(WDTLOAD[14]),
    .A1(_047_),
    .S(_030_),
    .X(_000_[14])
  );
  sky130_fd_sc_hd__xor2_1 _129_ (
    .A(WDTMR[13]),
    .B(_011_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _130_ (
    .A0(WDTLOAD[13]),
    .A1(_048_),
    .S(_030_),
    .X(_000_[13])
  );
  sky130_fd_sc_hd__xor2_1 _131_ (
    .A(WDTMR[12]),
    .B(_010_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _132_ (
    .A0(WDTLOAD[12]),
    .A1(_049_),
    .S(_030_),
    .X(_000_[12])
  );
  sky130_fd_sc_hd__xor2_1 _133_ (
    .A(WDTMR[11]),
    .B(_009_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _134_ (
    .A0(WDTLOAD[11]),
    .A1(_050_),
    .S(_030_),
    .X(_000_[11])
  );
  sky130_fd_sc_hd__xor2_1 _135_ (
    .A(WDTMR[10]),
    .B(_008_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _136_ (
    .A0(WDTLOAD[10]),
    .A1(_051_),
    .S(_030_),
    .X(_000_[10])
  );
  sky130_fd_sc_hd__xor2_1 _137_ (
    .A(WDTMR[9]),
    .B(_007_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _138_ (
    .A0(WDTLOAD[9]),
    .A1(_052_),
    .S(_030_),
    .X(_000_[9])
  );
  sky130_fd_sc_hd__xnor2_1 _139_ (
    .A(WDTMR[8]),
    .B(_006_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _140_ (
    .A0(WDTLOAD[8]),
    .A1(_053_),
    .S(_030_),
    .X(_000_[8])
  );
  sky130_fd_sc_hd__xor2_1 _141_ (
    .A(WDTMR[7]),
    .B(_005_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _142_ (
    .A0(WDTLOAD[7]),
    .A1(_054_),
    .S(_030_),
    .X(_000_[7])
  );
  sky130_fd_sc_hd__xor2_1 _143_ (
    .A(WDTMR[6]),
    .B(_004_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _144_ (
    .A0(WDTLOAD[6]),
    .A1(_055_),
    .S(_030_),
    .X(_000_[6])
  );
  sky130_fd_sc_hd__o21ai_0 _145_ (
    .A1(WDTMR[4]),
    .A2(_003_),
    .B1(WDTMR[5]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2b_1 _146_ (
    .A_N(_004_),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(WDTLOAD[5]),
    .A1(_057_),
    .S(_030_),
    .X(_000_[5])
  );
  sky130_fd_sc_hd__xnor2_1 _148_ (
    .A(WDTMR[4]),
    .B(_003_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _149_ (
    .A0(WDTLOAD[4]),
    .A1(_058_),
    .S(_030_),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__o31ai_1 _150_ (
    .A1(WDTMR[2]),
    .A2(WDTMR[1]),
    .A3(WDTMR[0]),
    .B1(WDTMR[3]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(_003_),
    .B(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _152_ (
    .A0(WDTLOAD[3]),
    .A1(_060_),
    .S(_030_),
    .X(_000_[3])
  );
  sky130_fd_sc_hd__xor2_1 _153_ (
    .A(WDTMR[2]),
    .B(_002_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _154_ (
    .A0(WDTLOAD[2]),
    .A1(_061_),
    .S(_030_),
    .X(_000_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _155_ (
    .A(WDTMR[1]),
    .B(WDTMR[0]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _156_ (
    .A0(WDTLOAD[1]),
    .A1(_062_),
    .S(_030_),
    .X(_000_[1])
  );
  sky130_fd_sc_hd__mux2i_1 _157_ (
    .A0(_063_),
    .A1(WDTMR[0]),
    .S(_030_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__nor4b_1 _158_ (
    .A(WDTMR[30]),
    .B(_027_),
    .C(WDTMR[31]),
    .D_N(WDTEN),
    .Y(WDTTO)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _159_ (
    .A1_N(WDTMR[31]),
    .A2_N(_029_),
    .B1(_030_),
    .B2(_001_),
    .Y(_000_[31])
  );
  sky130_fd_sc_hd__dfrtp_1 _160_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(WDTMR[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _161_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(WDTMR[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _162_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(WDTMR[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _163_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(WDTMR[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _164_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(WDTMR[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _165_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(WDTMR[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(WDTMR[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _167_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(WDTMR[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(WDTMR[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _169_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(WDTMR[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _170_ (
    .CLK(clk),
    .D(_000_[10]),
    .Q(WDTMR[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _171_ (
    .CLK(clk),
    .D(_000_[11]),
    .Q(WDTMR[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _172_ (
    .CLK(clk),
    .D(_000_[12]),
    .Q(WDTMR[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _173_ (
    .CLK(clk),
    .D(_000_[13]),
    .Q(WDTMR[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _174_ (
    .CLK(clk),
    .D(_000_[14]),
    .Q(WDTMR[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _175_ (
    .CLK(clk),
    .D(_000_[15]),
    .Q(WDTMR[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _176_ (
    .CLK(clk),
    .D(_000_[16]),
    .Q(WDTMR[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _177_ (
    .CLK(clk),
    .D(_000_[17]),
    .Q(WDTMR[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _178_ (
    .CLK(clk),
    .D(_000_[18]),
    .Q(WDTMR[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _179_ (
    .CLK(clk),
    .D(_000_[19]),
    .Q(WDTMR[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _180_ (
    .CLK(clk),
    .D(_000_[20]),
    .Q(WDTMR[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _181_ (
    .CLK(clk),
    .D(_000_[21]),
    .Q(WDTMR[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _182_ (
    .CLK(clk),
    .D(_000_[22]),
    .Q(WDTMR[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _183_ (
    .CLK(clk),
    .D(_000_[23]),
    .Q(WDTMR[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _184_ (
    .CLK(clk),
    .D(_000_[24]),
    .Q(WDTMR[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _185_ (
    .CLK(clk),
    .D(_000_[25]),
    .Q(WDTMR[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _186_ (
    .CLK(clk),
    .D(_000_[26]),
    .Q(WDTMR[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _187_ (
    .CLK(clk),
    .D(_000_[27]),
    .Q(WDTMR[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _188_ (
    .CLK(clk),
    .D(_000_[28]),
    .Q(WDTMR[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _189_ (
    .CLK(clk),
    .D(_000_[29]),
    .Q(WDTMR[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _190_ (
    .CLK(clk),
    .D(_000_[30]),
    .Q(WDTMR[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _191_ (
    .CLK(clk),
    .D(_000_[31]),
    .Q(WDTMR[31]),
    .RESET_B(rst_n)
  );
endmodule

module EF_WDT32_WB(clk_i, rst_i, adr_i, dat_i, dat_o, sel_i, cyc_i, stb_i, ack_o, we_i, IRQ);
  input clk_i;
  wire clk_i;
  input rst_i;
  wire rst_i;
  input [31:0] adr_i;
  wire [31:0] adr_i;
  input [31:0] dat_i;
  wire [31:0] dat_i;
  output [31:0] dat_o;
  wire [31:0] dat_o;
  input [3:0] sel_i;
  wire [3:0] sel_i;
  input cyc_i;
  wire cyc_i;
  input stb_i;
  wire stb_i;
  output ack_o;
  wire ack_o;
  input we_i;
  wire we_i;
  output IRQ;
  wire IRQ;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire [0:0] GCLK_REG;
  wire [0:0] IC_REG;
  wire [0:0] IM_REG;
  wire [0:0] MIS_REG;
  wire [0:0] RIS_REG;
  wire [0:0] WDTEN;
  wire [31:0] WDTLOAD;
  wire [31:0] WDTMR;
  wire [0:0] WDTTO;
  wire clk;
  wire clk_g;
  wire clk_gated_en;
  wire [0:0] control_REG;
  wire [31:0] load_REG;
  wire rst_n;
  wire [31:0] timer_WIRE;
  wire [0:0] wdtto;
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(load_REG[0]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(rst_i),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _166_ (
    .A(IC_REG),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _167_ (
    .A(RIS_REG),
    .B(WDTTO),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _168_ (
    .A(IC_REG),
    .B(_078_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _169_ (
    .A(cyc_i),
    .B(stb_i),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand3_1 _170_ (
    .A(we_i),
    .B(cyc_i),
    .C(stb_i),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor3b_1 _171_ (
    .A(adr_i[0]),
    .B(adr_i[1]),
    .C_N(adr_i[3]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor4b_1 _172_ (
    .A(adr_i[0]),
    .B(adr_i[1]),
    .C(adr_i[2]),
    .D_N(adr_i[3]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor3_1 _173_ (
    .A(adr_i[6]),
    .B(adr_i[7]),
    .C(adr_i[5]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor4_1 _174_ (
    .A(adr_i[6]),
    .B(adr_i[7]),
    .C(adr_i[4]),
    .D(adr_i[5]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__or4_1 _175_ (
    .A(adr_i[6]),
    .B(adr_i[7]),
    .C(adr_i[4]),
    .D(adr_i[5]),
    .X(_085_)
  );
  sky130_fd_sc_hd__nor4_1 _176_ (
    .A(adr_i[10]),
    .B(adr_i[11]),
    .C(adr_i[8]),
    .D(adr_i[9]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor4_1 _177_ (
    .A(adr_i[14]),
    .B(adr_i[15]),
    .C(adr_i[12]),
    .D(adr_i[13]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__and3_1 _178_ (
    .A(_084_),
    .B(_086_),
    .C(_087_),
    .X(_088_)
  );
  sky130_fd_sc_hd__and2_0 _179_ (
    .A(_082_),
    .B(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__nor2b_1 _180_ (
    .A(_080_),
    .B_N(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__mux2_1 _181_ (
    .A0(control_REG),
    .A1(dat_i[0]),
    .S(_090_),
    .X(_074_)
  );
  sky130_fd_sc_hd__nand4_1 _182_ (
    .A(adr_i[10]),
    .B(adr_i[11]),
    .C(adr_i[8]),
    .D(adr_i[9]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand4_1 _183_ (
    .A(adr_i[14]),
    .B(adr_i[15]),
    .C(adr_i[12]),
    .D(adr_i[13]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _185_ (
    .A(adr_i[4]),
    .SLEEP(_080_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nor4_1 _186_ (
    .A(adr_i[0]),
    .B(adr_i[1]),
    .C(adr_i[3]),
    .D(adr_i[2]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand4_1 _187_ (
    .A(_083_),
    .B(_093_),
    .C(_094_),
    .D(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__mux2_1 _188_ (
    .A0(dat_i[0]),
    .A1(GCLK_REG),
    .S(_096_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor4b_1 _189_ (
    .A(adr_i[0]),
    .B(adr_i[1]),
    .C(adr_i[3]),
    .D_N(adr_i[2]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__and2_0 _190_ (
    .A(_088_),
    .B(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__nor2b_1 _191_ (
    .A(_080_),
    .B_N(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__mux2_1 _192_ (
    .A0(load_REG[31]),
    .A1(dat_i[31]),
    .S(_099_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nor3_1 _193_ (
    .A(_085_),
    .B(_091_),
    .C(_092_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand3_1 _194_ (
    .A(_084_),
    .B(_093_),
    .C(_095_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _195_ (
    .A(_080_),
    .B(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__mux2_1 _196_ (
    .A0(IM_REG),
    .A1(dat_i[0]),
    .S(_102_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(dat_i[0]),
    .B(_099_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o21ai_0 _198_ (
    .A1(_076_),
    .A2(_099_),
    .B1(_103_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _199_ (
    .A0(load_REG[1]),
    .A1(dat_i[1]),
    .S(_099_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _200_ (
    .A0(load_REG[2]),
    .A1(dat_i[2]),
    .S(_099_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_1 _201_ (
    .A0(load_REG[3]),
    .A1(dat_i[3]),
    .S(_099_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _202_ (
    .A0(load_REG[4]),
    .A1(dat_i[4]),
    .S(_099_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _203_ (
    .A0(load_REG[5]),
    .A1(dat_i[5]),
    .S(_099_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _204_ (
    .A0(load_REG[6]),
    .A1(dat_i[6]),
    .S(_099_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _205_ (
    .A0(load_REG[7]),
    .A1(dat_i[7]),
    .S(_099_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _206_ (
    .A0(load_REG[8]),
    .A1(dat_i[8]),
    .S(_099_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _207_ (
    .A0(load_REG[9]),
    .A1(dat_i[9]),
    .S(_099_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _208_ (
    .A0(load_REG[10]),
    .A1(dat_i[10]),
    .S(_099_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _209_ (
    .A0(load_REG[11]),
    .A1(dat_i[11]),
    .S(_099_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _210_ (
    .A0(load_REG[12]),
    .A1(dat_i[12]),
    .S(_099_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _211_ (
    .A0(load_REG[13]),
    .A1(dat_i[13]),
    .S(_099_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _212_ (
    .A0(load_REG[14]),
    .A1(dat_i[14]),
    .S(_099_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _213_ (
    .A0(load_REG[15]),
    .A1(dat_i[15]),
    .S(_099_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _214_ (
    .A0(load_REG[16]),
    .A1(dat_i[16]),
    .S(_099_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _215_ (
    .A0(load_REG[17]),
    .A1(dat_i[17]),
    .S(_099_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _216_ (
    .A0(load_REG[18]),
    .A1(dat_i[18]),
    .S(_099_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _217_ (
    .A0(load_REG[19]),
    .A1(dat_i[19]),
    .S(_099_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _218_ (
    .A0(load_REG[20]),
    .A1(dat_i[20]),
    .S(_099_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _219_ (
    .A0(load_REG[21]),
    .A1(dat_i[21]),
    .S(_099_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _220_ (
    .A0(load_REG[22]),
    .A1(dat_i[22]),
    .S(_099_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _221_ (
    .A0(load_REG[23]),
    .A1(dat_i[23]),
    .S(_099_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _222_ (
    .A0(load_REG[24]),
    .A1(dat_i[24]),
    .S(_099_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _223_ (
    .A0(load_REG[25]),
    .A1(dat_i[25]),
    .S(_099_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _224_ (
    .A0(load_REG[26]),
    .A1(dat_i[26]),
    .S(_099_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _225_ (
    .A0(load_REG[27]),
    .A1(dat_i[27]),
    .S(_099_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _226_ (
    .A0(load_REG[28]),
    .A1(dat_i[28]),
    .S(_099_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _227_ (
    .A0(load_REG[29]),
    .A1(dat_i[29]),
    .S(_099_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _228_ (
    .A0(load_REG[30]),
    .A1(dat_i[30]),
    .S(_099_),
    .X(_040_)
  );
  sky130_fd_sc_hd__and2_0 _229_ (
    .A(_088_),
    .B(_095_),
    .X(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(_088_),
    .B(_095_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _231_ (
    .A(WDTMR[6]),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21oi_1 _232_ (
    .A1(load_REG[6]),
    .A2(_098_),
    .B1(_104_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_081_),
    .B(_100_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a211oi_1 _234_ (
    .A1(_097_),
    .A2(_100_),
    .B1(_098_),
    .C1(_089_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand3_1 _235_ (
    .A(_101_),
    .B(_108_),
    .C(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a21oi_1 _236_ (
    .A1(_107_),
    .A2(_110_),
    .B1(_106_),
    .Y(dat_o[6])
  );
  sky130_fd_sc_hd__nor2_1 _237_ (
    .A(WDTMR[5]),
    .B(_105_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a21oi_1 _238_ (
    .A1(load_REG[5]),
    .A2(_098_),
    .B1(_104_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21oi_1 _239_ (
    .A1(_110_),
    .A2(_112_),
    .B1(_111_),
    .Y(dat_o[5])
  );
  sky130_fd_sc_hd__a22o_1 _240_ (
    .A1(load_REG[4]),
    .A2(_098_),
    .B1(_104_),
    .B2(WDTMR[4]),
    .X(dat_o[4])
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(WDTMR[3]),
    .B(_105_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a21oi_1 _242_ (
    .A1(load_REG[3]),
    .A2(_098_),
    .B1(_104_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a21oi_1 _243_ (
    .A1(_110_),
    .A2(_114_),
    .B1(_113_),
    .Y(dat_o[3])
  );
  sky130_fd_sc_hd__nor2_1 _244_ (
    .A(WDTMR[2]),
    .B(_105_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a21oi_1 _245_ (
    .A1(load_REG[2]),
    .A2(_098_),
    .B1(_104_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21oi_1 _246_ (
    .A1(_110_),
    .A2(_116_),
    .B1(_115_),
    .Y(dat_o[2])
  );
  sky130_fd_sc_hd__nor2_1 _247_ (
    .A(WDTMR[13]),
    .B(_105_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a21oi_1 _248_ (
    .A1(load_REG[13]),
    .A2(_098_),
    .B1(_104_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _249_ (
    .A1(_110_),
    .A2(_118_),
    .B1(_117_),
    .Y(dat_o[13])
  );
  sky130_fd_sc_hd__nor2_1 _250_ (
    .A(WDTMR[12]),
    .B(_105_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21oi_1 _251_ (
    .A1(load_REG[12]),
    .A2(_098_),
    .B1(_104_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a21oi_1 _252_ (
    .A1(_110_),
    .A2(_120_),
    .B1(_119_),
    .Y(dat_o[12])
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(WDTMR[11]),
    .B(_105_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(load_REG[11]),
    .A2(_098_),
    .B1(_104_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a21oi_1 _255_ (
    .A1(_110_),
    .A2(_122_),
    .B1(_121_),
    .Y(dat_o[11])
  );
  sky130_fd_sc_hd__nor2_1 _256_ (
    .A(WDTMR[10]),
    .B(_105_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a21oi_1 _257_ (
    .A1(load_REG[10]),
    .A2(_098_),
    .B1(_104_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a21oi_1 _258_ (
    .A1(_110_),
    .A2(_124_),
    .B1(_123_),
    .Y(dat_o[10])
  );
  sky130_fd_sc_hd__a21oi_1 _259_ (
    .A1(_076_),
    .A2(_098_),
    .B1(_104_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a21oi_1 _260_ (
    .A1(control_REG),
    .A2(_089_),
    .B1(_098_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__and2_0 _261_ (
    .A(RIS_REG),
    .B(IM_REG),
    .X(IRQ)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _262_ (
    .A(_097_),
    .SLEEP(IRQ),
    .X(_127_)
  );
  sky130_fd_sc_hd__o21ai_0 _263_ (
    .A1(_095_),
    .A2(_127_),
    .B1(_100_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _264_ (
    .A(RIS_REG),
    .B(_082_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o2111ai_1 _265_ (
    .A1(_077_),
    .A2(_082_),
    .B1(_100_),
    .C1(_129_),
    .D1(_081_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a32oi_1 _266_ (
    .A1(IM_REG),
    .A2(_095_),
    .A3(_100_),
    .B1(_128_),
    .B2(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o21ai_0 _267_ (
    .A1(_089_),
    .A2(_131_),
    .B1(_126_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a22o_1 _268_ (
    .A1(WDTMR[0]),
    .A2(_104_),
    .B1(_125_),
    .B2(_132_),
    .X(dat_o[0])
  );
  sky130_fd_sc_hd__a22o_1 _269_ (
    .A1(load_REG[20]),
    .A2(_098_),
    .B1(_104_),
    .B2(WDTMR[20]),
    .X(dat_o[20])
  );
  sky130_fd_sc_hd__nor2_1 _270_ (
    .A(WDTMR[1]),
    .B(_105_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a21oi_1 _271_ (
    .A1(load_REG[1]),
    .A2(_098_),
    .B1(_104_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _272_ (
    .A1(_110_),
    .A2(_134_),
    .B1(_133_),
    .Y(dat_o[1])
  );
  sky130_fd_sc_hd__nor2_1 _273_ (
    .A(WDTMR[19]),
    .B(_105_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a21oi_1 _274_ (
    .A1(load_REG[19]),
    .A2(_098_),
    .B1(_104_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a21oi_1 _275_ (
    .A1(_110_),
    .A2(_136_),
    .B1(_135_),
    .Y(dat_o[19])
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(WDTMR[30]),
    .B(_105_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a21oi_1 _277_ (
    .A1(load_REG[30]),
    .A2(_098_),
    .B1(_104_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a21oi_1 _278_ (
    .A1(_110_),
    .A2(_138_),
    .B1(_137_),
    .Y(dat_o[30])
  );
  sky130_fd_sc_hd__a22o_1 _279_ (
    .A1(load_REG[29]),
    .A2(_098_),
    .B1(_104_),
    .B2(WDTMR[29]),
    .X(dat_o[29])
  );
  sky130_fd_sc_hd__nor2_1 _280_ (
    .A(WDTMR[28]),
    .B(_105_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _281_ (
    .A1(load_REG[28]),
    .A2(_098_),
    .B1(_104_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a21oi_1 _282_ (
    .A1(_110_),
    .A2(_140_),
    .B1(_139_),
    .Y(dat_o[28])
  );
  sky130_fd_sc_hd__nor2_1 _283_ (
    .A(WDTMR[27]),
    .B(_105_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21oi_1 _284_ (
    .A1(load_REG[27]),
    .A2(_098_),
    .B1(_104_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _285_ (
    .A1(_110_),
    .A2(_142_),
    .B1(_141_),
    .Y(dat_o[27])
  );
  sky130_fd_sc_hd__nor2_1 _286_ (
    .A(WDTMR[23]),
    .B(_105_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21oi_1 _287_ (
    .A1(load_REG[23]),
    .A2(_098_),
    .B1(_104_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a21oi_1 _288_ (
    .A1(_110_),
    .A2(_144_),
    .B1(_143_),
    .Y(dat_o[23])
  );
  sky130_fd_sc_hd__a22o_1 _289_ (
    .A1(load_REG[22]),
    .A2(_098_),
    .B1(_104_),
    .B2(WDTMR[22]),
    .X(dat_o[22])
  );
  sky130_fd_sc_hd__nor2_1 _290_ (
    .A(WDTMR[21]),
    .B(_105_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _291_ (
    .A1(load_REG[21]),
    .A2(_098_),
    .B1(_104_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a21oi_1 _292_ (
    .A1(_110_),
    .A2(_146_),
    .B1(_145_),
    .Y(dat_o[21])
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(WDTMR[16]),
    .B(_105_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a21oi_1 _294_ (
    .A1(load_REG[16]),
    .A2(_098_),
    .B1(_104_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a21oi_1 _295_ (
    .A1(_110_),
    .A2(_148_),
    .B1(_147_),
    .Y(dat_o[16])
  );
  sky130_fd_sc_hd__nor2_1 _296_ (
    .A(WDTMR[18]),
    .B(_105_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a21oi_1 _297_ (
    .A1(load_REG[18]),
    .A2(_098_),
    .B1(_104_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a21oi_1 _298_ (
    .A1(_110_),
    .A2(_150_),
    .B1(_149_),
    .Y(dat_o[18])
  );
  sky130_fd_sc_hd__nor2_1 _299_ (
    .A(WDTMR[15]),
    .B(_105_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21oi_1 _300_ (
    .A1(load_REG[15]),
    .A2(_098_),
    .B1(_104_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__a21oi_1 _301_ (
    .A1(_110_),
    .A2(_152_),
    .B1(_151_),
    .Y(dat_o[15])
  );
  sky130_fd_sc_hd__nor2_1 _302_ (
    .A(WDTMR[26]),
    .B(_105_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_1 _303_ (
    .A1(load_REG[26]),
    .A2(_098_),
    .B1(_104_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a21oi_1 _304_ (
    .A1(_110_),
    .A2(_154_),
    .B1(_153_),
    .Y(dat_o[26])
  );
  sky130_fd_sc_hd__a22o_1 _305_ (
    .A1(load_REG[17]),
    .A2(_098_),
    .B1(_104_),
    .B2(WDTMR[17]),
    .X(dat_o[17])
  );
  sky130_fd_sc_hd__nor2_1 _306_ (
    .A(WDTMR[31]),
    .B(_105_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a21oi_1 _307_ (
    .A1(load_REG[31]),
    .A2(_098_),
    .B1(_104_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a21oi_1 _308_ (
    .A1(_110_),
    .A2(_156_),
    .B1(_155_),
    .Y(dat_o[31])
  );
  sky130_fd_sc_hd__a22o_1 _309_ (
    .A1(load_REG[14]),
    .A2(_098_),
    .B1(_104_),
    .B2(WDTMR[14]),
    .X(dat_o[14])
  );
  sky130_fd_sc_hd__nor2_1 _310_ (
    .A(WDTMR[25]),
    .B(_105_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a21oi_1 _311_ (
    .A1(load_REG[25]),
    .A2(_098_),
    .B1(_104_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a21oi_1 _312_ (
    .A1(_110_),
    .A2(_158_),
    .B1(_157_),
    .Y(dat_o[25])
  );
  sky130_fd_sc_hd__nor2_1 _313_ (
    .A(ack_o),
    .B(_079_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _314_ (
    .A(WDTMR[9]),
    .B(_105_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a21oi_1 _315_ (
    .A1(load_REG[9]),
    .A2(_098_),
    .B1(_104_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _316_ (
    .A1(_110_),
    .A2(_160_),
    .B1(_159_),
    .Y(dat_o[9])
  );
  sky130_fd_sc_hd__a22o_1 _317_ (
    .A1(load_REG[8]),
    .A2(_098_),
    .B1(_104_),
    .B2(WDTMR[8]),
    .X(dat_o[8])
  );
  sky130_fd_sc_hd__nor2_1 _318_ (
    .A(WDTMR[7]),
    .B(_105_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a21oi_1 _319_ (
    .A1(load_REG[7]),
    .A2(_098_),
    .B1(_104_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a21oi_1 _320_ (
    .A1(_110_),
    .A2(_162_),
    .B1(_161_),
    .Y(dat_o[7])
  );
  sky130_fd_sc_hd__a22o_1 _321_ (
    .A1(load_REG[24]),
    .A2(_098_),
    .B1(_104_),
    .B2(WDTMR[24]),
    .X(dat_o[24])
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(dat_i[0]),
    .B(adr_i[2]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nor3_1 _323_ (
    .A(_080_),
    .B(_108_),
    .C(_163_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _324_ (
    .A(rst_i),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _325_ (
    .A(rst_i),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _326_ (
    .A(rst_i),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _327_ (
    .A(rst_i),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _328_ (
    .A(rst_i),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _329_ (
    .A(rst_i),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _330_ (
    .A(rst_i),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _331_ (
    .A(rst_i),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _332_ (
    .A(rst_i),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _333_ (
    .A(rst_i),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _334_ (
    .A(rst_i),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _335_ (
    .A(rst_i),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _336_ (
    .A(rst_i),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _337_ (
    .A(rst_i),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _338_ (
    .A(rst_i),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _339_ (
    .A(rst_i),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _340_ (
    .A(rst_i),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _341_ (
    .A(rst_i),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _342_ (
    .A(rst_i),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _343_ (
    .A(rst_i),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _344_ (
    .A(rst_i),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _345_ (
    .A(rst_i),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _346_ (
    .A(rst_i),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _347_ (
    .A(rst_i),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _348_ (
    .A(rst_i),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(rst_i),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _350_ (
    .A(rst_i),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(rst_i),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _352_ (
    .A(rst_i),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _353_ (
    .A(rst_i),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _354_ (
    .A(rst_i),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _355_ (
    .A(rst_i),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _356_ (
    .A(rst_i),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _357_ (
    .A(rst_i),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _358_ (
    .A(rst_i),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _359_ (
    .A(rst_i),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _360_ (
    .A(rst_i),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _361_ (
    .A(rst_i),
    .Y(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _362_ (
    .CLK(clk_i),
    .D(_045_),
    .Q(load_REG[25]),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfrtp_1 _363_ (
    .CLK(clk_i),
    .D(_044_),
    .Q(load_REG[26]),
    .RESET_B(_006_)
  );
  sky130_fd_sc_hd__dfrtp_1 _364_ (
    .CLK(clk_i),
    .D(_043_),
    .Q(load_REG[27]),
    .RESET_B(_005_)
  );
  sky130_fd_sc_hd__dfrtp_1 _365_ (
    .CLK(clk_i),
    .D(_042_),
    .Q(load_REG[28]),
    .RESET_B(_004_)
  );
  sky130_fd_sc_hd__dfrtp_1 _366_ (
    .CLK(clk_i),
    .D(_041_),
    .Q(load_REG[29]),
    .RESET_B(_003_)
  );
  sky130_fd_sc_hd__dfrtp_1 _367_ (
    .CLK(clk_i),
    .D(_040_),
    .Q(load_REG[30]),
    .RESET_B(_002_)
  );
  sky130_fd_sc_hd__dfrtp_1 _368_ (
    .CLK(clk_i),
    .D(_072_),
    .Q(load_REG[31]),
    .RESET_B(_035_)
  );
  sky130_fd_sc_hd__dfrtp_1 _369_ (
    .CLK(clk_i),
    .D(_073_),
    .Q(GCLK_REG),
    .RESET_B(_036_)
  );
  sky130_fd_sc_hd__dfrtp_1 _370_ (
    .CLK(clk_i),
    .D(_074_),
    .Q(control_REG),
    .RESET_B(_038_)
  );
  sky130_fd_sc_hd__dfrtp_1 _371_ (
    .CLK(clk_i),
    .D(_075_),
    .Q(RIS_REG),
    .RESET_B(_039_)
  );
  sky130_fd_sc_hd__dfrtp_1 _372_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(ack_o),
    .RESET_B(_034_)
  );
  sky130_fd_sc_hd__dfrtp_1 _373_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(IC_REG),
    .RESET_B(_037_)
  );
  sky130_fd_sc_hd__dfrtp_1 _374_ (
    .CLK(clk_i),
    .D(_071_),
    .Q(IM_REG),
    .RESET_B(_033_)
  );
  sky130_fd_sc_hd__dfrtp_1 _375_ (
    .CLK(clk_i),
    .D(_070_),
    .Q(load_REG[0]),
    .RESET_B(_032_)
  );
  sky130_fd_sc_hd__dfrtp_1 _376_ (
    .CLK(clk_i),
    .D(_069_),
    .Q(load_REG[1]),
    .RESET_B(_031_)
  );
  sky130_fd_sc_hd__dfrtp_1 _377_ (
    .CLK(clk_i),
    .D(_068_),
    .Q(load_REG[2]),
    .RESET_B(_030_)
  );
  sky130_fd_sc_hd__dfrtp_1 _378_ (
    .CLK(clk_i),
    .D(_067_),
    .Q(load_REG[3]),
    .RESET_B(_029_)
  );
  sky130_fd_sc_hd__dfrtp_1 _379_ (
    .CLK(clk_i),
    .D(_066_),
    .Q(load_REG[4]),
    .RESET_B(_028_)
  );
  sky130_fd_sc_hd__dfrtp_1 _380_ (
    .CLK(clk_i),
    .D(_065_),
    .Q(load_REG[5]),
    .RESET_B(_027_)
  );
  sky130_fd_sc_hd__dfrtp_1 _381_ (
    .CLK(clk_i),
    .D(_064_),
    .Q(load_REG[6]),
    .RESET_B(_026_)
  );
  sky130_fd_sc_hd__dfrtp_1 _382_ (
    .CLK(clk_i),
    .D(_063_),
    .Q(load_REG[7]),
    .RESET_B(_025_)
  );
  sky130_fd_sc_hd__dfrtp_1 _383_ (
    .CLK(clk_i),
    .D(_062_),
    .Q(load_REG[8]),
    .RESET_B(_024_)
  );
  sky130_fd_sc_hd__dfrtp_1 _384_ (
    .CLK(clk_i),
    .D(_061_),
    .Q(load_REG[9]),
    .RESET_B(_023_)
  );
  sky130_fd_sc_hd__dfrtp_1 _385_ (
    .CLK(clk_i),
    .D(_060_),
    .Q(load_REG[10]),
    .RESET_B(_022_)
  );
  sky130_fd_sc_hd__dfrtp_1 _386_ (
    .CLK(clk_i),
    .D(_059_),
    .Q(load_REG[11]),
    .RESET_B(_021_)
  );
  sky130_fd_sc_hd__dfrtp_1 _387_ (
    .CLK(clk_i),
    .D(_058_),
    .Q(load_REG[12]),
    .RESET_B(_020_)
  );
  sky130_fd_sc_hd__dfrtp_1 _388_ (
    .CLK(clk_i),
    .D(_057_),
    .Q(load_REG[13]),
    .RESET_B(_019_)
  );
  sky130_fd_sc_hd__dfrtp_1 _389_ (
    .CLK(clk_i),
    .D(_056_),
    .Q(load_REG[14]),
    .RESET_B(_018_)
  );
  sky130_fd_sc_hd__dfrtp_1 _390_ (
    .CLK(clk_i),
    .D(_055_),
    .Q(load_REG[15]),
    .RESET_B(_017_)
  );
  sky130_fd_sc_hd__dfrtp_1 _391_ (
    .CLK(clk_i),
    .D(_054_),
    .Q(load_REG[16]),
    .RESET_B(_016_)
  );
  sky130_fd_sc_hd__dfrtp_1 _392_ (
    .CLK(clk_i),
    .D(_053_),
    .Q(load_REG[17]),
    .RESET_B(_015_)
  );
  sky130_fd_sc_hd__dfrtp_1 _393_ (
    .CLK(clk_i),
    .D(_052_),
    .Q(load_REG[18]),
    .RESET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_1 _394_ (
    .CLK(clk_i),
    .D(_051_),
    .Q(load_REG[19]),
    .RESET_B(_013_)
  );
  sky130_fd_sc_hd__dfrtp_1 _395_ (
    .CLK(clk_i),
    .D(_050_),
    .Q(load_REG[20]),
    .RESET_B(_012_)
  );
  sky130_fd_sc_hd__dfrtp_1 _396_ (
    .CLK(clk_i),
    .D(_049_),
    .Q(load_REG[21]),
    .RESET_B(_011_)
  );
  sky130_fd_sc_hd__dfrtp_1 _397_ (
    .CLK(clk_i),
    .D(_048_),
    .Q(load_REG[22]),
    .RESET_B(_010_)
  );
  sky130_fd_sc_hd__dfrtp_1 _398_ (
    .CLK(clk_i),
    .D(_047_),
    .Q(load_REG[23]),
    .RESET_B(_009_)
  );
  sky130_fd_sc_hd__dfrtp_1 _399_ (
    .CLK(clk_i),
    .D(_046_),
    .Q(load_REG[24]),
    .RESET_B(_008_)
  );
  ef_util_gating_cell clk_gate_cell (
    .clk(clk_i),
    .clk_en(GCLK_REG),
    .clk_o(clk)
  );
  EF_WDT32 instance_to_wrap (
    .WDTEN(control_REG),
    .WDTLOAD(load_REG),
    .WDTMR(WDTMR),
    .WDTTO(WDTTO),
    .clk(clk),
    .rst_n(rst_n)
  );
  assign wdtto = WDTTO;
  assign MIS_REG = IRQ;
  assign timer_WIRE = WDTMR;
  assign WDTEN = control_REG;
  assign WDTLOAD = load_REG;
  assign clk_gated_en = GCLK_REG;
  assign clk_g = clk;
endmodule

module ef_util_gating_cell(clk, rst_n, clk_en, clk_o);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input clk_en;
  wire clk_en;
  output clk_o;
  wire clk_o;
  assign clk_o = clk;
endmodule
