/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

module caravel_wrapper(clk_i, rst_ni, wb_adr_i, wb_dat_i, wb_dat_o, wb_sel_i, wb_we_i, wb_stb_i, wb_cyc_i, wb_ack_o, la_data_in_i, la_data_out_o, la_oenb_i, io_in_i, irq_caravel_o, ready_i);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input [31:0] wb_adr_i;
  wire [31:0] wb_adr_i;
  input [31:0] wb_dat_i;
  wire [31:0] wb_dat_i;
  output [31:0] wb_dat_o;
  wire [31:0] wb_dat_o;
  input [3:0] wb_sel_i;
  wire [3:0] wb_sel_i;
  input wb_we_i;
  wire wb_we_i;
  input wb_stb_i;
  wire wb_stb_i;
  input wb_cyc_i;
  wire wb_cyc_i;
  output wb_ack_o;
  wire wb_ack_o;
  input [127:0] la_data_in_i;
  wire [127:0] la_data_in_i;
  output [127:0] la_data_out_o;
  wire [127:0] la_data_out_o;
  input [127:0] la_oenb_i;
  wire [127:0] la_oenb_i;
  input [37:0] io_in_i;
  wire [37:0] io_in_i;
  output irq_caravel_o;
  wire irq_caravel_o;
  input ready_i;
  wire ready_i;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire [31:0] bridge_data;
  wire bridge_valid;
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(bridge_data[28]),
    .A1(la_data_in_i[28]),
    .S(ready_i),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _101_ (
    .A0(bridge_data[27]),
    .A1(la_data_in_i[27]),
    .S(ready_i),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(bridge_data[26]),
    .A1(la_data_in_i[26]),
    .S(ready_i),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _103_ (
    .A0(bridge_data[25]),
    .A1(la_data_in_i[25]),
    .S(ready_i),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(bridge_data[24]),
    .A1(la_data_in_i[24]),
    .S(ready_i),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _105_ (
    .A0(bridge_data[23]),
    .A1(la_data_in_i[23]),
    .S(ready_i),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(bridge_data[22]),
    .A1(la_data_in_i[22]),
    .S(ready_i),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _107_ (
    .A0(bridge_data[21]),
    .A1(la_data_in_i[21]),
    .S(ready_i),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _108_ (
    .A0(bridge_data[20]),
    .A1(la_data_in_i[20]),
    .S(ready_i),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _109_ (
    .A0(bridge_data[19]),
    .A1(la_data_in_i[19]),
    .S(ready_i),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _110_ (
    .A0(bridge_data[18]),
    .A1(la_data_in_i[18]),
    .S(ready_i),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _111_ (
    .A0(bridge_data[17]),
    .A1(la_data_in_i[17]),
    .S(ready_i),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(bridge_data[16]),
    .A1(la_data_in_i[16]),
    .S(ready_i),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _113_ (
    .A0(bridge_data[15]),
    .A1(la_data_in_i[15]),
    .S(ready_i),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _114_ (
    .A0(bridge_data[14]),
    .A1(la_data_in_i[14]),
    .S(ready_i),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _115_ (
    .A0(bridge_data[13]),
    .A1(la_data_in_i[13]),
    .S(ready_i),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _116_ (
    .A0(bridge_data[12]),
    .A1(la_data_in_i[12]),
    .S(ready_i),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _117_ (
    .A0(bridge_data[11]),
    .A1(la_data_in_i[11]),
    .S(ready_i),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _118_ (
    .A0(bridge_data[10]),
    .A1(la_data_in_i[10]),
    .S(ready_i),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _119_ (
    .A0(bridge_data[9]),
    .A1(la_data_in_i[9]),
    .S(ready_i),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _120_ (
    .A0(bridge_data[8]),
    .A1(la_data_in_i[8]),
    .S(ready_i),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _121_ (
    .A0(bridge_data[7]),
    .A1(la_data_in_i[7]),
    .S(ready_i),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _122_ (
    .A0(bridge_data[6]),
    .A1(la_data_in_i[6]),
    .S(ready_i),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _123_ (
    .A0(bridge_data[5]),
    .A1(la_data_in_i[5]),
    .S(ready_i),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _124_ (
    .A0(bridge_data[4]),
    .A1(la_data_in_i[4]),
    .S(ready_i),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _125_ (
    .A0(bridge_data[3]),
    .A1(la_data_in_i[3]),
    .S(ready_i),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _126_ (
    .A0(bridge_data[2]),
    .A1(la_data_in_i[2]),
    .S(ready_i),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _127_ (
    .A0(bridge_data[1]),
    .A1(la_data_in_i[1]),
    .S(ready_i),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _128_ (
    .A0(bridge_data[0]),
    .A1(la_data_in_i[0]),
    .S(ready_i),
    .X(_030_)
  );
  sky130_fd_sc_hd__and4b_1 _129_ (
    .A_N(wb_ack_o),
    .B(wb_cyc_i),
    .C(wb_stb_i),
    .D(ready_i),
    .X(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _130_ (
    .A(wb_we_i),
    .B(_001_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _131_ (
    .A0(wb_dat_i[30]),
    .A1(la_data_out_o[30]),
    .S(_098_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _132_ (
    .A0(wb_dat_i[29]),
    .A1(la_data_out_o[29]),
    .S(_098_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _133_ (
    .A0(wb_dat_i[28]),
    .A1(la_data_out_o[28]),
    .S(_098_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _134_ (
    .A0(wb_dat_i[27]),
    .A1(la_data_out_o[27]),
    .S(_098_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _135_ (
    .A0(wb_dat_i[26]),
    .A1(la_data_out_o[26]),
    .S(_098_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _136_ (
    .A0(wb_dat_i[25]),
    .A1(la_data_out_o[25]),
    .S(_098_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _137_ (
    .A0(wb_dat_i[24]),
    .A1(la_data_out_o[24]),
    .S(_098_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _138_ (
    .A0(wb_dat_i[23]),
    .A1(la_data_out_o[23]),
    .S(_098_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _139_ (
    .A0(wb_dat_i[22]),
    .A1(la_data_out_o[22]),
    .S(_098_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _140_ (
    .A0(wb_dat_i[21]),
    .A1(la_data_out_o[21]),
    .S(_098_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _141_ (
    .A0(wb_dat_i[20]),
    .A1(la_data_out_o[20]),
    .S(_098_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _142_ (
    .A0(wb_dat_i[19]),
    .A1(la_data_out_o[19]),
    .S(_098_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _143_ (
    .A0(wb_dat_i[18]),
    .A1(la_data_out_o[18]),
    .S(_098_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _144_ (
    .A0(wb_dat_i[17]),
    .A1(la_data_out_o[17]),
    .S(_098_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _145_ (
    .A0(wb_dat_i[16]),
    .A1(la_data_out_o[16]),
    .S(_098_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _146_ (
    .A0(wb_dat_i[15]),
    .A1(la_data_out_o[15]),
    .S(_098_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(wb_dat_i[14]),
    .A1(la_data_out_o[14]),
    .S(_098_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _148_ (
    .A0(wb_dat_i[13]),
    .A1(la_data_out_o[13]),
    .S(_098_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _149_ (
    .A0(wb_dat_i[12]),
    .A1(la_data_out_o[12]),
    .S(_098_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _150_ (
    .A0(wb_dat_i[11]),
    .A1(la_data_out_o[11]),
    .S(_098_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _151_ (
    .A0(wb_dat_i[10]),
    .A1(la_data_out_o[10]),
    .S(_098_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _152_ (
    .A0(wb_dat_i[9]),
    .A1(la_data_out_o[9]),
    .S(_098_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _153_ (
    .A0(wb_dat_i[8]),
    .A1(la_data_out_o[8]),
    .S(_098_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _154_ (
    .A0(wb_dat_i[7]),
    .A1(la_data_out_o[7]),
    .S(_098_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _155_ (
    .A0(wb_dat_i[6]),
    .A1(la_data_out_o[6]),
    .S(_098_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _156_ (
    .A0(wb_dat_i[5]),
    .A1(la_data_out_o[5]),
    .S(_098_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _157_ (
    .A0(wb_dat_i[4]),
    .A1(la_data_out_o[4]),
    .S(_098_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _158_ (
    .A0(wb_dat_i[3]),
    .A1(la_data_out_o[3]),
    .S(_098_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _159_ (
    .A0(wb_dat_i[2]),
    .A1(la_data_out_o[2]),
    .S(_098_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _160_ (
    .A0(wb_dat_i[1]),
    .A1(la_data_out_o[1]),
    .S(_098_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _161_ (
    .A0(wb_dat_i[0]),
    .A1(la_data_out_o[0]),
    .S(_098_),
    .X(_061_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _162_ (
    .A(_001_),
    .SLEEP(wb_we_i),
    .X(_099_)
  );
  sky130_fd_sc_hd__mux2_1 _163_ (
    .A0(wb_dat_o[30]),
    .A1(bridge_data[30]),
    .S(_099_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _164_ (
    .A0(wb_dat_o[29]),
    .A1(bridge_data[29]),
    .S(_099_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _165_ (
    .A0(wb_dat_o[28]),
    .A1(bridge_data[28]),
    .S(_099_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _166_ (
    .A0(wb_dat_o[27]),
    .A1(bridge_data[27]),
    .S(_099_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _167_ (
    .A0(wb_dat_o[26]),
    .A1(bridge_data[26]),
    .S(_099_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _168_ (
    .A0(wb_dat_o[25]),
    .A1(bridge_data[25]),
    .S(_099_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _169_ (
    .A0(wb_dat_o[24]),
    .A1(bridge_data[24]),
    .S(_099_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_1 _170_ (
    .A0(wb_dat_o[23]),
    .A1(bridge_data[23]),
    .S(_099_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _171_ (
    .A0(wb_dat_o[22]),
    .A1(bridge_data[22]),
    .S(_099_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _172_ (
    .A0(wb_dat_o[21]),
    .A1(bridge_data[21]),
    .S(_099_),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2_1 _173_ (
    .A0(wb_dat_o[20]),
    .A1(bridge_data[20]),
    .S(_099_),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2_1 _174_ (
    .A0(wb_dat_o[19]),
    .A1(bridge_data[19]),
    .S(_099_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _175_ (
    .A0(wb_dat_o[18]),
    .A1(bridge_data[18]),
    .S(_099_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _176_ (
    .A0(wb_dat_o[17]),
    .A1(bridge_data[17]),
    .S(_099_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _177_ (
    .A0(wb_dat_o[16]),
    .A1(bridge_data[16]),
    .S(_099_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_1 _178_ (
    .A0(wb_dat_o[15]),
    .A1(bridge_data[15]),
    .S(_099_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2_1 _179_ (
    .A0(wb_dat_o[14]),
    .A1(bridge_data[14]),
    .S(_099_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _180_ (
    .A0(wb_dat_o[13]),
    .A1(bridge_data[13]),
    .S(_099_),
    .X(_079_)
  );
  sky130_fd_sc_hd__mux2_1 _181_ (
    .A0(wb_dat_o[12]),
    .A1(bridge_data[12]),
    .S(_099_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _182_ (
    .A0(wb_dat_o[11]),
    .A1(bridge_data[11]),
    .S(_099_),
    .X(_081_)
  );
  sky130_fd_sc_hd__mux2_1 _183_ (
    .A0(wb_dat_o[10]),
    .A1(bridge_data[10]),
    .S(_099_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_1 _184_ (
    .A0(wb_dat_o[9]),
    .A1(bridge_data[9]),
    .S(_099_),
    .X(_083_)
  );
  sky130_fd_sc_hd__mux2_1 _185_ (
    .A0(wb_dat_o[8]),
    .A1(bridge_data[8]),
    .S(_099_),
    .X(_084_)
  );
  sky130_fd_sc_hd__mux2_1 _186_ (
    .A0(wb_dat_o[7]),
    .A1(bridge_data[7]),
    .S(_099_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_1 _187_ (
    .A0(wb_dat_o[6]),
    .A1(bridge_data[6]),
    .S(_099_),
    .X(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _188_ (
    .A0(wb_dat_o[5]),
    .A1(bridge_data[5]),
    .S(_099_),
    .X(_087_)
  );
  sky130_fd_sc_hd__mux2_1 _189_ (
    .A0(wb_dat_o[4]),
    .A1(bridge_data[4]),
    .S(_099_),
    .X(_088_)
  );
  sky130_fd_sc_hd__mux2_1 _190_ (
    .A0(wb_dat_o[3]),
    .A1(bridge_data[3]),
    .S(_099_),
    .X(_089_)
  );
  sky130_fd_sc_hd__mux2_1 _191_ (
    .A0(wb_dat_o[2]),
    .A1(bridge_data[2]),
    .S(_099_),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_1 _192_ (
    .A0(wb_dat_o[1]),
    .A1(bridge_data[1]),
    .S(_099_),
    .X(_091_)
  );
  sky130_fd_sc_hd__mux2_1 _193_ (
    .A0(wb_dat_o[0]),
    .A1(bridge_data[0]),
    .S(_099_),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_1 _194_ (
    .A0(bridge_data[31]),
    .A1(la_data_in_i[31]),
    .S(ready_i),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux2_1 _195_ (
    .A0(bridge_data[30]),
    .A1(la_data_in_i[30]),
    .S(ready_i),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_1 _196_ (
    .A0(wb_dat_o[31]),
    .A1(bridge_data[31]),
    .S(_099_),
    .X(_095_)
  );
  sky130_fd_sc_hd__mux2_1 _197_ (
    .A0(bridge_data[29]),
    .A1(la_data_in_i[29]),
    .S(ready_i),
    .X(_096_)
  );
  sky130_fd_sc_hd__and2_0 _198_ (
    .A(ready_i),
    .B(bridge_valid),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _199_ (
    .A0(wb_dat_i[31]),
    .A1(la_data_out_o[31]),
    .S(_098_),
    .X(_097_)
  );
  sky130_fd_sc_hd__dfrtp_1 _200_ (
    .CLK(clk_i),
    .D(_092_),
    .Q(wb_dat_o[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _201_ (
    .CLK(clk_i),
    .D(_091_),
    .Q(wb_dat_o[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _202_ (
    .CLK(clk_i),
    .D(_090_),
    .Q(wb_dat_o[2]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _203_ (
    .CLK(clk_i),
    .D(_089_),
    .Q(wb_dat_o[3]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _204_ (
    .CLK(clk_i),
    .D(_088_),
    .Q(wb_dat_o[4]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _205_ (
    .CLK(clk_i),
    .D(_087_),
    .Q(wb_dat_o[5]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _206_ (
    .CLK(clk_i),
    .D(_086_),
    .Q(wb_dat_o[6]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _207_ (
    .CLK(clk_i),
    .D(_085_),
    .Q(wb_dat_o[7]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _208_ (
    .CLK(clk_i),
    .D(_084_),
    .Q(wb_dat_o[8]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _209_ (
    .CLK(clk_i),
    .D(_083_),
    .Q(wb_dat_o[9]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _210_ (
    .CLK(clk_i),
    .D(_082_),
    .Q(wb_dat_o[10]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _211_ (
    .CLK(clk_i),
    .D(_081_),
    .Q(wb_dat_o[11]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _212_ (
    .CLK(clk_i),
    .D(_080_),
    .Q(wb_dat_o[12]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _213_ (
    .CLK(clk_i),
    .D(_079_),
    .Q(wb_dat_o[13]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _214_ (
    .CLK(clk_i),
    .D(_078_),
    .Q(wb_dat_o[14]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _215_ (
    .CLK(clk_i),
    .D(_077_),
    .Q(wb_dat_o[15]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _216_ (
    .CLK(clk_i),
    .D(_076_),
    .Q(wb_dat_o[16]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _217_ (
    .CLK(clk_i),
    .D(_075_),
    .Q(wb_dat_o[17]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _218_ (
    .CLK(clk_i),
    .D(_074_),
    .Q(wb_dat_o[18]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _219_ (
    .CLK(clk_i),
    .D(_073_),
    .Q(wb_dat_o[19]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _220_ (
    .CLK(clk_i),
    .D(_072_),
    .Q(wb_dat_o[20]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _221_ (
    .CLK(clk_i),
    .D(_071_),
    .Q(wb_dat_o[21]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _222_ (
    .CLK(clk_i),
    .D(_070_),
    .Q(wb_dat_o[22]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _223_ (
    .CLK(clk_i),
    .D(_069_),
    .Q(wb_dat_o[23]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _224_ (
    .CLK(clk_i),
    .D(_068_),
    .Q(wb_dat_o[24]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _225_ (
    .CLK(clk_i),
    .D(_067_),
    .Q(wb_dat_o[25]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _226_ (
    .CLK(clk_i),
    .D(_066_),
    .Q(wb_dat_o[26]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _227_ (
    .CLK(clk_i),
    .D(_065_),
    .Q(wb_dat_o[27]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _228_ (
    .CLK(clk_i),
    .D(_064_),
    .Q(wb_dat_o[28]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _229_ (
    .CLK(clk_i),
    .D(_063_),
    .Q(wb_dat_o[29]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _230_ (
    .CLK(clk_i),
    .D(_062_),
    .Q(wb_dat_o[30]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _231_ (
    .CLK(clk_i),
    .D(_095_),
    .Q(wb_dat_o[31]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _232_ (
    .CLK(clk_i),
    .D(_061_),
    .Q(la_data_out_o[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _233_ (
    .CLK(clk_i),
    .D(_060_),
    .Q(la_data_out_o[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _234_ (
    .CLK(clk_i),
    .D(_059_),
    .Q(la_data_out_o[2]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _235_ (
    .CLK(clk_i),
    .D(_058_),
    .Q(la_data_out_o[3]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _236_ (
    .CLK(clk_i),
    .D(_057_),
    .Q(la_data_out_o[4]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _237_ (
    .CLK(clk_i),
    .D(_056_),
    .Q(la_data_out_o[5]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _238_ (
    .CLK(clk_i),
    .D(_055_),
    .Q(la_data_out_o[6]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _239_ (
    .CLK(clk_i),
    .D(_054_),
    .Q(la_data_out_o[7]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _240_ (
    .CLK(clk_i),
    .D(_053_),
    .Q(la_data_out_o[8]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _241_ (
    .CLK(clk_i),
    .D(_052_),
    .Q(la_data_out_o[9]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _242_ (
    .CLK(clk_i),
    .D(_051_),
    .Q(la_data_out_o[10]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _243_ (
    .CLK(clk_i),
    .D(_050_),
    .Q(la_data_out_o[11]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _244_ (
    .CLK(clk_i),
    .D(_049_),
    .Q(la_data_out_o[12]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _245_ (
    .CLK(clk_i),
    .D(_048_),
    .Q(la_data_out_o[13]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _246_ (
    .CLK(clk_i),
    .D(_047_),
    .Q(la_data_out_o[14]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _247_ (
    .CLK(clk_i),
    .D(_046_),
    .Q(la_data_out_o[15]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _248_ (
    .CLK(clk_i),
    .D(_045_),
    .Q(la_data_out_o[16]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _249_ (
    .CLK(clk_i),
    .D(_044_),
    .Q(la_data_out_o[17]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _250_ (
    .CLK(clk_i),
    .D(_043_),
    .Q(la_data_out_o[18]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _251_ (
    .CLK(clk_i),
    .D(_042_),
    .Q(la_data_out_o[19]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _252_ (
    .CLK(clk_i),
    .D(_041_),
    .Q(la_data_out_o[20]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _253_ (
    .CLK(clk_i),
    .D(_040_),
    .Q(la_data_out_o[21]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _254_ (
    .CLK(clk_i),
    .D(_039_),
    .Q(la_data_out_o[22]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _255_ (
    .CLK(clk_i),
    .D(_038_),
    .Q(la_data_out_o[23]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _256_ (
    .CLK(clk_i),
    .D(_037_),
    .Q(la_data_out_o[24]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _257_ (
    .CLK(clk_i),
    .D(_036_),
    .Q(la_data_out_o[25]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _258_ (
    .CLK(clk_i),
    .D(_035_),
    .Q(la_data_out_o[26]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _259_ (
    .CLK(clk_i),
    .D(_034_),
    .Q(la_data_out_o[27]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _260_ (
    .CLK(clk_i),
    .D(_033_),
    .Q(la_data_out_o[28]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _261_ (
    .CLK(clk_i),
    .D(_032_),
    .Q(la_data_out_o[29]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _262_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(la_data_out_o[30]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _263_ (
    .CLK(clk_i),
    .D(_097_),
    .Q(la_data_out_o[31]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _264_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(bridge_data[0]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _265_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(bridge_data[1]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _266_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(bridge_data[2]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _267_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(bridge_data[3]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _268_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(bridge_data[4]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _269_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(bridge_data[5]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _270_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(bridge_data[6]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _271_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(bridge_data[7]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _272_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(bridge_data[8]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _273_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(bridge_data[9]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _274_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(bridge_data[10]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _275_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(bridge_data[11]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _276_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(bridge_data[12]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _277_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(bridge_data[13]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _278_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(bridge_data[14]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _279_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(bridge_data[15]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _280_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(bridge_data[16]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _281_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(bridge_data[17]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _282_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(bridge_data[18]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _283_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(bridge_data[19]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _284_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(bridge_data[20]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _285_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(bridge_data[21]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _286_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(bridge_data[22]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _287_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(bridge_data[23]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _288_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(bridge_data[24]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _289_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(bridge_data[25]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _290_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(bridge_data[26]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _291_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(bridge_data[27]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _292_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(bridge_data[28]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _293_ (
    .CLK(clk_i),
    .D(_096_),
    .Q(bridge_data[29]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _294_ (
    .CLK(clk_i),
    .D(_094_),
    .Q(bridge_data[30]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _295_ (
    .CLK(clk_i),
    .D(_093_),
    .Q(bridge_data[31]),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _296_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(wb_ack_o),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _297_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(irq_caravel_o),
    .RESET_B(rst_ni)
  );
  sky130_fd_sc_hd__dfrtp_1 _298_ (
    .CLK(clk_i),
    .D(ready_i),
    .Q(bridge_valid),
    .RESET_B(rst_ni)
  );
  assign la_data_out_o[127:32] = 96'h000000000000000000000000;
endmodule
